{
 "title": "Rebuffer Rate",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "query": {
     "query": "label_values(analytics_logs_playtime_ms_sum,user_id)"
    }
   },
   {
    "name": "playback_id",
    "query": {
     "query": "label_values(analytics_logs_playtime_ms_sum{user_id=~\"$user_id\"},playback_id)"
    }
   },
   {
    "name": "continent",
    "query": {
     "query": "label_values(analytics_logs_playtime_ms_sum{user_id=~\"$user_id\", playback_id=~\"$playback_id\"},continent)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(analytics_logs_playtime_ms_sum{user_id=~\"$user_id\", playback_id=~\"$playback_id\", continent=~\"$continent\"},region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global rebuffer rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg (\n    increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    / \n    (\n        increase(analytics_logs_playtime_ms_sum{user_id=~\"${user_id}\", playback_id=~\"${playback_id}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n        + \n        increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    )\n) * 100",
     "legendFormat": "global rebuffer rate"
    }
   ]
  },
  {
   "title": "Rebuffer rate by catalyst server region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(region) (\n    increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    / \n    (\n        increase(analytics_logs_playtime_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n        +\n        increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebuffer rate by viewer's continent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(continent) (\n    increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    /\n    (\n        increase(analytics_logs_playtime_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n        +\n        increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebuffer rate by catalyst node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(catalyst_node) (\n    increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    /\n    (\n        increase(analytics_logs_playtime_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n        +\n        increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebuffer rate by playback ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(playback_id) (\n    increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    / \n    ((\n        increase(analytics_logs_playtime_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n        +\n        increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    ))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebuffer rate by studio user ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(user_id) (\n    increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    /\n    (\n        increase(analytics_logs_playtime_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n        +\n        increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m])\n    )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "playtime vs rebuffer time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(analytics_logs_buffer_time_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m]))",
     "legendFormat": "rebuffer"
    },
    {
     "expr": "sum(increase(analytics_logs_playtime_ms_sum{user_id=~\"${user_id:pipe}\", playback_id=~\"${playback_id:pipe}\", continent=~\"${continent:pipe}\", region=~\"${region:pipe}\"}[1m]))",
     "legendFormat": "playtime"
    }
   ]
  }
 ]
}