version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /config-generator
    versioning-strategy: increase
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
