{
 "title": "2023-04-29 Investigation",
 "time": { "from": "2023-04-29T08:52:37.000Z", "to": "2023-04-29T14:15:44.000Z" },
 "panels": [
  {
   "title": "Stream trigger timeout",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |~ \"timed out after\"[1m])) by (region)"
    }
   ]
  },
  {
   "title": "Total Viewers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (mist_sessions{catalyst=\"true\", sessType=\"viewers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "catalyst-api logs by region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |~ \"catalyst-api\" [1m])) by (region)"
    }
   ]
  },
  {
   "title": "Threads by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(container_threads{pod!=\"\"}) by (region, instance)",
     "legendFormat": "{{ region }}-{{instance }}"
    }
   ]
  },
  {
   "title": "Excessive Threads by Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(container_threads{pod!=\"\"}) by (region, instance, pod) > 5000",
     "legendFormat": "{{ region }}-{{instance }}-{{ pod }}"
    }
   ]
  },
  {
   "title": "Lot Radio Origin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "mist_sessions{sessType=\"incoming\", stream=~\"video(rec)?\\\\+85c28sa2o8wppm58\"} > 0",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Stream trigger timeout",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_time{catalyst_node=~\".*studio\"}[15m])) by (trigger) / on(trigger) sum(rate(mist_trigger_count{catalyst_node=~\".*studio\"}[15m])) by (trigger)",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  {
   "title": "Broadcaster Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |~ \"Node type bctr node ID\"[5m])) by (pod, region)",
     "legendFormat": "{{ region }}-{{pod}}"
    }
   ]
  },
  {
   "title": "Segmentation Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |~ \"livepeer-catalyst-api\" |~ \"PUT /lp-us-catalyst-vod-com\"[1m])) by (region)"
    }
   ]
  }
 ]
}