{
 "title": "Access Control Playback",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "VOD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(region) (rate(catalyst_playback_request_duration_seconds_count{success=\"true\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "avg by(region, status_code) (rate(catalyst_playback_request_duration_seconds_count{success=\"false\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Times (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "avg by(region) (increase(catalyst_playback_request_duration_seconds_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}