{
 "title": "Ai Monitoring [WIP]",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stream_id",
    "label": "Stream ID",
    "query": "SELECT se.stream_id\nFROM network_events.stream_status AS se;"
   }
  ]
 },
 "panels": [
  {
   "title": "Stream Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Streams Online",
     "type": "stat",
     "description": "This chart displays the current count of online streams",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) AS online_count\nFROM network_events.stream_status\nWHERE state = 'ONLINE' AND\n      last_input_time_ts >= now() - INTERVAL 30 SECOND;"
      }
     ]
    },
    {
     "title": "Stream Error Logs",
     "type": "table",
     "description": "This chart displays the most recent events related to errors and restarts within the streaming system.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT \n    stream_id, \n    timestamp_ts, \n    restart_count,\n    event_type, \n    message,  \n    gateway,\n    type, \n    capability, \n    pipeline, \n    pipeline_id, \n    params, \n    orchestrator_address, \n    orchestrator_url\nFROM \n    network_events.stream_events\nWHERE \n    sub_type IN ('error', 'restart')\n    AND $__timeFilter(timestamp_ts)\nORDER BY \n    timestamp_ts DESC\nLIMIT 100;\n"
      }
     ]
    },
    {
     "title": "Stream Status [Error/Restart Count with Stream ID]",
     "type": "table",
     "description": "This visualizes the count of'restart' and 'error' events for the latest 15 distinct streams in the network_events.stream_events dataset.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \n    stream_id, \n    countIf(event_type = 'restart') AS restart_count,\n    countIf(event_type = 'error') AS error_count\nFROM (\n    SELECT DISTINCT stream_id\n    FROM network_events.stream_events\n    WHERE event_type IN ('restart', 'error')\n    ORDER BY timestamp_ts DESC\n    LIMIT 15\n) AS latest_streams\nJOIN network_events.stream_events USING (stream_id)\nGROUP BY stream_id\nORDER BY stream_id ASC;\n"
      }
     ]
    },
    {
     "title": "Stream Health",
     "type": "timeseries",
     "description": "This chart visualizes the counts of 'restart' and 'error' events occurring in a stream over time\n\nRestart Count: This metric indicates the number of times a 'restart' event occurred within the specified minute. A higher count may suggest frequent restarts, which could indicate potential issues with service stability or performance.\n\nError Count: This metric represents the number of 'error' events logged during the same minute. An increase in error counts may signal underlying problems that require investigation, such as system failures or misconfigurations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\ntoStartOfMinute(se.timestamp_ts) AS timestamp_ts,\nse.stream_id,\nss.state,\nsum(se.restart_count) AS Restart_Count,\ncountIf(se.sub_type = 'error') AS Error_Count\n\nFROM\nnetwork_events.stream_events AS se\nJOIN\nnetwork_events.stream_status AS ss ON se.stream_id = ss.stream_id\nWHERE\nse.stream_id IN (SELECT DISTINCT stream_id FROM network_events.stream_events)\nAND $__timeFilter(se.timestamp_ts)\nGROUP BY\ntimestamp_ts, se.stream_id, ss.state\nORDER BY\ntimestamp_ts ASC;"
      }
     ]
    }
   ]
  },
  { "title": "CPU Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage (> 50%)",
   "type": "timeseries",
   "description": "This chart visualizes the CPU usage percentage for nodes in specified regions, with a threshold set at 80%.\n\nA CPU usage percentage greater than 80% indicates that the system is heavily loaded, with most of the CPU resources actively in use.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance, region) (irate(node_cpu_seconds_total{region =~ \".*-ai$\", mode=\"idle\", instance=~\".+:9100\"}[1m])) * 100 * on(instance) group_left(nodename) node_uname_info) \n",
     "legendFormat": "{{region}}-{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Memory Usage (> 50%)",
   "type": "timeseries",
   "description": "This visualizes the count of'restart' and 'error' events for the latest 15 distinct streams in the network_events.stream_events dataset.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{region=~\".*-ai$\"} + node_memory_Buffers_bytes{region=~\".*-ai$\"} + node_memory_Cached_bytes{region=~\".*-ai$\"}) / node_memory_MemTotal_bytes{region=~\".*-ai$\"} * on(region) group_left(nodename) node_uname_info",
     "legendFormat": "{{region}}-{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "This  indicates how much of the total disk capacity is being utilized.\n\nA higher percentage indicates that a significant portion of the disk space is in use, which may suggest that the filesystem is nearing capacity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", region=~\".*-ai$\"} - node_filesystem_avail_bytes{mountpoint=\"/\", region=~\".*-ai$\"}) / node_filesystem_size_bytes{mountpoint=\"/\", region=~\".*-ai$\"} * 100",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Ingest Disk I/O Per Minute",
   "type": "timeseries",
   "description": "This shows the disk I/O performance for various regions, specifically focusing on the rates of data being written to and read from disk.\n\nNormal Operation:-\nWhen the disk write and read rates are within expected ranges based on usage over time , the system is functioning normally. You should see stable lines on the graph, indicating consistent disk I/O performance.\n\nHigh Disk Write/Read Rates:- If the lines show significantly high values, it may indicate heavy disk usage. This could be due data ingestion processes. \n\nSudden spikes or drops in disk I/O can indicate issues that need further investigation of the node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{region=~\".*-ai$\"}[1m])) by (region) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPUs",
     "type": "stat",
     "description": "Number of GPUs in use and the total number of GPUs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(DCGM_FI_DEV_GPU_UTIL{gpu!=\"\"} > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(DCGM_FI_DEV_POWER_USAGE{gpu!=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage",
     "type": "timeseries",
     "description": "Shows how much VRAM is being used to store data and buffers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "{{Hostname}}/{{modelName}}" }
     ]
    },
    {
     "title": "GPU Temperature >75°C - Celsius",
     "type": "timeseries",
     "description": "Indicates how hot the GPU is running. 75°C is set as the warning  and ≥85°C should be alerted. Below 5°C should also indicate an issue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{node_name}}/{{modelName}}" }
     ]
    },
    {
     "title": "GPU Power Usage ",
     "type": "timeseries",
     "description": "Shows how much electricity the GPU is consuming - higher usage indicates more intensive workloads",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "kwattm" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE",
       "legendFormat": "{{node_name}}/{{UUID}}/{{modelName}}"
      }
     ]
    },
    {
     "title": "GPU Utilization ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (\n  Hostname, \n  UUID, \n  gpu, \n  instance, \n  modelName, \n  node_name, \n  region\n) (\n    DCGM_FI_DEV_GPU_UTIL\n)",
       "legendFormat": "{{node_name}}({{UUID}})({{modelName}})"
      }
     ]
    }
   ]
  }
 ]
}