{
 "title": "AI Overview (Livestream)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "All Gateway Logs", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "MediaMTX unsupported codec",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"mediamtx\"} |~ `the stream doesn't contain any supported codec|closed: codec`"
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Error Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(normalized_error_code) (label_replace(increase(livepeer_ai_request_errors{pipeline=~\"live-.*\"}[$__rate_interval]), \"normalized_error_code\", \"no orchestrators available\", \"error_code\", \"no orchestrators available.*\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Orchestrators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Orchestrator Capacity by Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{node_type=\"orch\", livepeer_node_type=\"prod-livepeer-orchestrator\"}) by (livepeerversion) + sum(livepeer_versions{job=\"orchestrator\",region=~\"td_eu-prod|td_us-prod\"}) by (livepeerversion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-Use Orchestrators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum (livepeer_ai_current_live_pipelines)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Capacity Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(pipeline, model_name) (increase(livepeer_ai_request_errors{error_code=~\"no orchestrators available.*\", pipeline=~\"live-.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}