{
 "title": "Airbyte",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "job_failed_by_release_stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "job_failed_by_release_stage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Activities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "activity_normalization{job=\"worker\"}",
     "legendFormat": "__auto"
    },
    { "expr": "activity_replication", "legendFormat": "__auto" },
    { "expr": "activity_discover_catalog", "legendFormat": "__auto" },
    { "expr": "activity_refresh_schema", "legendFormat": "__auto" },
    {},
    { "expr": "attempt_completed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "record_schema_validation_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "record_schema_validation_error", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "replication_records_synced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "replication_records_synced", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Abnormal syncs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "num_abnormal_scheduled_syncs{job=\"metrics-reporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}