{
 "title": "Alerts - Nodes",
 "description": "Alerts for Nodes using prometheus and node_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [
  "alerts",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Nodes CPU Usage (> 50%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance, region) (irate(node_cpu_seconds_total{region != \"eu-metrics\", mode=\"idle\", instance=~\".+:9100\"}[1m])) * 100 * on(instance) group_left(nodename) node_uname_info) \n",
     "legendFormat": "{{region}}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "Nodes Memory Usage (> 50%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{region!=\"eu-metrics\"} - node_memory_MemFree_bytes{region!=\"eu-metrics\"} - node_memory_Buffers_bytes{region!=\"eu-metrics\"} - node_memory_Cached_bytes{region!=\"eu-metrics\"}) / node_memory_MemTotal_bytes{nodename!~\"eu-metrics-.*\"} * on(instance, region) group_left(nodename) node_uname_info\n\n\n",
     "legendFormat": "{{ region }}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{region!=\"eu-metrics\"} * on(instance, region) group_left(nodename) node_uname_info\n\n\n",
     "legendFormat": "{{ region }}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{region!=\"eu-metrics\"} * on(instance, region) group_left(nodename) node_uname_info\n\n\n",
     "legendFormat": "{{ region }}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "Nodes Disk Usage (> 90%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (region, mountpoint, nodename) (\n    ((100.0 - 100 * ((node_filesystem_avail_bytes[1m] / 1000 / 1000 ) / (node_filesystem_size_bytes{mountpoint != \"/var/mnt/core-dump-handler/cores\", mountpoint != \"/home/data/core-dump-handler/cores\", mountpoint !~ \"/run/k3s.+\", region=~\"lax|mdw|nyc|sao|lon|fra|prg|sin|ams\"}[1m]  / 1024 / 1024))))\n        * on(instance) group_left(nodename) node_uname_info\n    )",
     "legendFormat": "{{region}}-{{nodename}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Node Processes Running > 40",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (region, nodename) (\n        node_procs_running{} \n        * on(instance) group_left(nodename) node_uname_info\n    )",
     "legendFormat": "{{ region }}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "System Load (1m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (region, nodename) (\n        node_load1{} \n        * on(instance) group_left(nodename) node_uname_info\n    )",
     "legendFormat": "{{ region }}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "blk_update_request: I/O error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"systemd-journal\", unit!=\"ssh.service\"}  |~ \"blk_update_request: I/O error\"[1m])) by (region, node_name)",
     "legendFormat": "{{ region }}-{{ node_name }}"
    }
   ]
  },
  {
   "title": "watchdog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"systemd-journal\", unit=\"\"} |~ \"watchdog\"[1m])) by (node_name, region)",
     "legendFormat": "{{ region }}-{{ node_name }}"
    }
   ]
  },
  {
   "title": "k3s CRASHED",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"systemd-journal\", unit= \"init.scope\"} |= \"Stopped Lightweight Kubernetes\"[1m])) by (node_name, region)",
     "legendFormat": "{{ region }}-{{ node_name }}"
    }
   ]
  },
  {
   "title": "oom-killer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"systemd-journal\"} |~ \"invoked oom-killer\"[1m])) by (node_name, region)",
     "legendFormat": "{{ region }}-{{ node_name }}"
    }
   ]
  },
  {
   "title": "leaderelection lost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"systemd-journal\", unit= \"k3s.service\"} |~ \"leaderelection lost\"[1m])) by (node_name, region)",
     "legendFormat": "{{ region }}-{{ node_name }}"
    }
   ]
  }
 ]
}