{
 "title": "Analytics Monitoring Dashboard",
 "description": "Monitoring Dashboard for Critical Analytics Workflows",
 "tags": [
  "discord",
  "engagement",
  "analytics",
  "viewership"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Catalyst <> Analytics Postgres Write Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=\"catalyst\"} |= `error writing postgres metrics` [5m]))",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Viewership Cron Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job_name) (increase(kube_job_status_failed{job_name=~\"prod-analytics-dbt-.*\"}[$__interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "quantile(.5, mist_transcode_latency[5m]) / 1000 + quantile(.5, mist_transcode_jitter[5m])/ 1000 + quantile(.5, mist_latency[5m]) / 1000",
     "legendFormat": "Total latency for transcoded tracks"
    },
    {
     "expr": "quantile(.5, mist_latency[5m]) / 1000",
     "legendFormat": "Replication latency"
    }
   ]
  },
  {
   "title": "Viewership DBT Cron Log Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({region=\"analytics\", app=\"prod-analytics-dbt\"} [5m]))",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Successful Viewership Cron Runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(kube_job_status_succeeded{job_name=~\"prod-analytics-dbt-.*\"}[$__interval]))",
     "legendFormat": "kube_pod_status_ready"
    }
   ]
  },
  {
   "title": "analytics-dbt logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"prod-analytics-dbt\"}"
    }
   ]
  }
 ]
}