{
 "title": "App Versions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Catalyst", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Catalyst API (Standalone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version) (version{app=\"catalyst-api\", kubernetes_name!=\"prod-task-runner\",app_kubernetes_io_name=\"catalyst-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalyst API (Catalyst Live)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version) (version{app=\"catalyst-api\", kubernetes_name!=\"prod-task-runner\",catalyst=\"true\", region!=\"atl\", region!=\"mad\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalyst API (Catalyst VOD)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version) (version{app=\"catalyst-api\", kubernetes_name!=\"prod-task-runner\",catalyst=\"true\", region=~\"atl|mad\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task runner",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (version) (livepeer_task_runner_version{livepeer_live_app=~\".+-task-runner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MistServer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(version{app=\"MistServer\"}) by (version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Studio API",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (version) (version{app=\"studio-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "go-livepeer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "go-livepeer (Catalyst Broadcasters)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{catalyst=\"true\"}) by (livepeerversion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-livepeer (Non-Recording Broadcasters)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{catalyst!=\"true\", node_type=\"bctr\", livepeer_node_type!~\".+-livepeer-recording\"}) by (livepeerversion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-livepeer (Recording Broadcasters)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{catalyst!=\"true\", node_type=\"bctr\", livepeer_node_type=~\".+-livepeer-recording\"}) by (livepeerversion)",
     "legendFormat": "{{ livepeerversion }}"
    }
   ]
  },
  {
   "title": "go-livepeer (Orchestrator)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{node_type=\"orch\"}) by (livepeerversion)",
     "legendFormat": "{{ livepeerversion }}"
    }
   ]
  },
  {
   "title": "go-livepeer (AI Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{catalyst!=\"true\", node_type=\"bctr\", livepeer_node_type=~\".+-livepeer-ai-gateway\"}) by (livepeerversion)",
     "legendFormat": "{{ livepeerversion }}"
    }
   ]
  },
  {
   "title": "Concurrent Versions by App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "count by (app) (\n    sum by (version, app) (\n        label_replace(\n            label_replace(\n                label_replace(\n                    {__name__=~\".*versions?\"}, \n                    \"app\", \"$1\", \"livepeer_live_app\", \"(.+)\"\n                ), \"app\", \"$1\", \"livepeer_node_type\", \"(.+)\"\n            ), \"version\", \"$1\", \"livepeerversion\", \"(.+)\"\n        )\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}