{
 "title": "BGP Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(kube_node_info, region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "\"Connection Rejected\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container = \"metallb-speaker\"} |~ \"Connection Rejected\"[1m])) by (region, node_name)",
     "legendFormat": "{{ region }}-{{ node_name }}"
    }
   ]
  },
  {
   "title": "\"Administrative Shutdown\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container = \"metallb-speaker\"} |~ \"Administrative Shutdown\"[1m])) by (region, node_name)",
     "legendFormat": "{{ region }}-{{ node_name }}"
    }
   ]
  },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 } },
  {
   "title": "Mist PUSH_REWRITE triggers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"mist\", region =~ \"$region\"} |~ \"Executing PUSH_REWRITE trigger\"[10m])) by (region, node_name)",
     "legendFormat": "{{ region }}-{{ node_name }}"
    }
   ]
  },
  {
   "title": "metallb-speaker \"failed to connect to peer\"",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"metallb-speaker\", region =~ \"$region\"} |~ \"failed to connect to peer\" | json [1m])) by (region, node_name, error)",
     "legendFormat": "{{ region }}-{{ node_name }} {{error}}"
    }
   ]
  }
 ]
}