{
 "title": "Broadcaster Introspection (Marco's)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "${region:text} - Regional Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total unique manifests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by (manifestID) (count_over_time( {region=~\"$region\"} |= \"Selecting new orchestrator\" | pattern \"<_> manifestID=<manifestID> <_>\" [$__range])))",
     "legendFormat": "Streams"
    },
    {
     "expr": "sum(count_over_time( {region=~\"$region\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=<orchTo> <_> manifestID=<manifestID>\" [$__range]))",
     "legendFormat": "Swaps"
    }
   ]
  },
  {
   "title": "Swaps per manifestID",
   "type": "timeseries",
   "description": "Only considers streams with at least one swap",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum by (manifestID) (count_over_time( {region=~\"$region\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=<orchTo> <_> manifestID=<manifestID>\" [15m]))",
     "legendFormat": "{{manifestID}}"
    }
   ]
  },
  {
   "title": "Swaps by Orchestrator serviceUri",
   "type": "piechart",
   "description": "Counts the amount of times B's in the given region switch away from a given Orchestrator serviceUri in the past 24h",
   "gridPos": { "h": 20, "w": 9, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (orchFrom) (count_over_time( {region=~\"$region\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=<orchTo> <_> manifestID=<manifestID>\" [$__range]))",
     "legendFormat": "{{orchFrom}}"
    }
   ]
  },
  {
   "title": "Swaps per manifestID",
   "type": "piechart",
   "gridPos": { "h": 20, "w": 9, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(count_over_time( {region=~\"$region\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=<orchTo> <_> manifestID=<manifestID>\" [$__range])) by (manifestID)",
     "legendFormat": "{{manifestID}}"
    }
   ]
  },
  {
   "title": "${region:text} - Regional Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orchestrator Swaps raw",
     "type": "logs",
     "description": "Formatted log lines of Orchestrator swaps happening in the past 24h",
     "gridPos": { "h": 20, "w": 20, "x": 2, "y": 31 },
     "targets": [
      {
       "expr": "{region=~\"$region\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=<orchTo> <_> manifestID=<manifestID>\" | line_format \"Swapped stream {{.manifestID}} from Orchestrator {{.orchFrom}} to {{.orchTo}}\"",
       "maxLines": 2000
      }
     ]
    }
   ]
  },
  {
   "title": "Global Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Streams",
     "type": "stat",
     "description": "(in the past 6 hours)",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (region) ( count by (manifestID, region) (count_over_time( {container=\"broadcaster\"} |= \"Selecting new orchestrator\" | pattern \"<_> manifestID=<manifestID> <_>\" [$__range])))",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Total Swaps",
     "type": "stat",
     "description": "(in the past 6 hours)",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_over_time( {container=\"broadcaster\"} |= \"Swapping from\" [$__range])",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Hourly Swapped from",
     "type": "timeseries",
     "description": "Swapped away from this Orchestrator service uri",
     "gridPos": { "h": 9, "w": 11, "x": 1, "y": 43 },
     "targets": [
      {
       "expr": "count by (orchFrom) (count_over_time( {container=\"broadcaster\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=<orchTo> <_> manifestID=<manifestID>\" [1h]))",
       "legendFormat": "{{manifestID}}"
      }
     ]
    },
    {
     "title": "Hourly swapped to",
     "type": "timeseries",
     "description": "Swapped to this Orchestrator service uri",
     "gridPos": { "h": 9, "w": 11, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "count by (orchTo) (count_over_time( {container=\"broadcaster\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=[<orchTo>] <_> manifestID=<manifestID>\" [1h]))",
       "legendFormat": "{{manifestID}}"
      }
     ]
    },
    {
     "title": "Swaps per ManifestID",
     "type": "piechart",
     "description": "Swaps in a 15 minute period",
     "gridPos": { "h": 22, "w": 9, "x": 2, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "( count by (manifestID) (count_over_time( {container=\"broadcaster\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=<orchTo> <_> manifestID=<manifestID>\" [$__range])))",
       "legendFormat": "{{manifestID}}"
      }
     ]
    },
    {
     "title": "Swaps by Orchestrator serviceUri",
     "type": "piechart",
     "description": "Only considers streams which have at least one swap",
     "gridPos": { "h": 22, "w": 9, "x": 13, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "( count by (orchFrom) (count_over_time( {container=\"broadcaster\"} |= \"Swapping from\" | pattern \"<_> orch=<orchFrom> <_> orch=<orchTo> <_> manifestID=<manifestID>\" [$__range])))",
       "legendFormat": "{{orchFrom}}"
      }
     ]
    }
   ]
  }
 ]
}