{
 "title": "Broadcaster introspection logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs per region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(region) (count_over_time({region=~\".+\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs per clientIP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(clientIP) (count_over_time({region=~\".+\"} | logfmt [$__auto]))",
     "legendFormat": "{{ clientIP }}"
    }
   ]
  },
  {
   "title": "\"[PublicLogs]\" broadcaster logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{region=~\".+\"}"
    }
   ]
  },
  {
   "title": "loki report gateway logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{app=\"loki-distributed\", pod=~\"prod-loki-distributed-report-gateway.*\"} != `POST /loki/api/v1/push`"
    }
   ]
  }
 ]
}