{
 "title": "Burning Man",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "exclude", "label": "Exclude streams:", "query": ".+-test" }
  ]
 },
 "panels": [
  {
   "title": "Current Viewers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (mist_sessions{catalyst=\"true\", sessType=\"viewers\", user_id=\"30e0492e-ff0c-4ca5-982f-af1e7f627c0d\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Viewers by Region",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(mist_sessions{user_id=\"30e0492e-ff0c-4ca5-982f-af1e7f627c0d\", catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\", stream!~\"$exclude\"}) by (region)",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Current Streams",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (mist_sessions{catalyst=\"true\", sessType=\"incoming\", user_id=\"30e0492e-ff0c-4ca5-982f-af1e7f627c0d\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Viewers by stream",
   "type": "timeseries",
   "description": "Viewer sessions as reported by mist for each active stream",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", user_id=\"30e0492e-ff0c-4ca5-982f-af1e7f627c0d\", sessType=\"viewers\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\", stream!~\"catalyst_vod.+\"}[1m] ) by (stream) or on() vector(0), \"playback_id\", \"$1\", \"stream\", \".*[+](.*)\")",
     "legendFormat": "{{playback_id}}"
    }
   ]
  },
  {
   "title": "Viewers by Node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "sum(mist_sessions{user_id=\"30e0492e-ff0c-4ca5-982f-af1e7f627c0d\", catalyst=\"true\", sessType=\"viewers\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\"}[1m] ) by (catalyst_node) ",
     "legendFormat": "{{ stream }}"
    }
   ]
  }
 ]
}