{
 "title": "Catalyst Multi-Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "exclude", "label": "Exclude streams:", "query": ".+-test" }
  ]
 },
 "panels": [
  {
   "title": "Current Viewers",
   "type": "stat",
   "description": "Shows the total number of active viewer sessions across Catalyst nodes, excluding streams matching the exclude filter.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Current Streams",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (mist_sessions{catalyst=\"true\", sessType=\"incoming\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Nodes Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mist_cpu{catalyst=\"true\"})"
    }
   ]
  },
  {
   "title": "Viewers by stream",
   "type": "timeseries",
   "description": "Viewer sessions as reported by mist for each active stream",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\", stream!~\"catalyst_vod.+\"}[1m] ) by (stream) or on() vector(0), \"playback_id\", \"$1\", \"stream\", \".*[+](.*)\")",
     "legendFormat": "{{playback_id}}"
    }
   ]
  },
  {
   "title": "Viewers by user_id",
   "type": "timeseries",
   "description": "Viewer sessions as reported by catalyst for each active streaming user",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\", stream!~\"catalyst_vod.+\"}[1m] ) by (user_id)",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Current Streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum (mist_sessions{catalyst=\"true\", sessType=\"incoming\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Streams by User ID",
   "type": "timeseries",
   "description": "Shows incoming Catalyst stream activity grouped by user ID to identify heavy users, distribution of load, and user-specific spikes or drops over time.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sum (mist_sessions{catalyst=\"true\", sessType=\"incoming\", stream!~\"$exclude\"}) by (user_id)"
    }
   ]
  },
  {
   "title": "Viewers by Region",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\", stream!~\"$exclude\"}) by (region)",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Viewers by Protocol",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "sum(mist_outputs{catalyst_node=~\".*studio\"}) by (output)",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Total Viewers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "sum (mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Key duration mismatch; disconnecting (mist)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"catalyst\"} |~ \"FAIL: onFail\" |~ \"Key duration mismatch; disconnecting\" | pattern \"<_> '<_>+<playback_id>': Key duration mismatch; disconnecting <ip> to recover\"[30m])) by (playback_id)",
     "legendFormat": "{{ playback_id }}"
    }
   ]
  },
  {
   "title": "Viewers per Node",
   "type": "timeseries",
   "description": "Shows active viewer sessions over time for each Catalyst node, helping compare load distribution and spot node-level anomalies.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\"}[1m] ) by (catalyst_node) ",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "count(mist_cpu{catalyst=\"true\"}) ",
     "legendFormat": "{{ catalyst_node }}"
    }
   ]
  },
  {
   "title": "VoD Segments Transcoded",
   "type": "timeseries",
   "description": "vod_transcoded_segments",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(catalyst_node) (increase(vod_transcoded_segments[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"Could not retrieve\" replications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"Could not retrieve.*https://\" | pattern \"<_> https://<host>/\"[5m])) by (host)",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "sum(count_over_time({app=\"ingress-nginx\", namespace=\"default\", stream=\"stderr\"} != \"sent data after final chunk\" |~ \"[error]\" | pattern `<_> upstream: \"<protocol>://<ip>:<port>/<code>.<ext>\", host: \"<upstreamHost>:<upstreamPort>\"` | port = \"4242\" | ext = \"json\"[1m])) by (upstreamHost)",
     "legendFormat": "{{ upstreamHost }}"
    }
   ]
  },
  {
   "title": "Incoming Streams by Node",
   "type": "timeseries",
   "description": "Shows incoming stream session activity per node to compare load distribution and spot imbalances or abnormal spikes across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"incoming\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\"}[1m] ) by (catalyst_node) ",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Could not find serf member",
   "type": "timeseries",
   "description": "If this is occurring a lot, the pod that nodes can't find needs to be deleted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |~ \"could not find serf member\" | logfmt[5m])) by (name)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Node Count (by node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "count(mist_cpu{catalyst=\"true\"}) by (catalyst_node) or on() vector(0)",
     "legendFormat": "{{ catalyst_node }}"
    }
   ]
  },
  {
   "title": "Shutting down on Serf client failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"Shutting down on Serf client failure\"[1m])) by (region, pod)",
     "legendFormat": "{{ region }}-{{ pod }}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Loss detected (mist)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"catalyst\"} |~ \"Packet loss detected\" | pattern \"<_> MistOutTSSRT:<playback_id> \"[1m])) by (playback_id)",
     "legendFormat": "{{ playback_id }}"
    },
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"catalyst\"} |~ \"Packet loss detected\" | pattern \"<_> MistOutTSSRT:<playback_id> \"[1m]))",
     "legendFormat": "{{ playback_id }}"
    }
   ]
  },
  {
   "title": "Gated HLS Sessions (mist)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"not allowed\"[1m])) by (region)",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "videorec with no audio selection (mist)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum(count_over_time(\n  {app=\"catalyst\", namespace=\"default\"}\n  |~ \"MistProcLivepeer\"\n  |~ \"videorec\"\n  |~ \"Adding 1 tracks\"\n  | pattern \"<_> MistProcLivepeer:videorec+<playbackId> <_> MEDIUM: Adding 1 tracks\"[1m]\n)) by (playbackId)"
    }
   ]
  },
  {
   "title": "Global configuration options not ready (mist)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"Global configuration options not ready\"[1m])) by (region, pod)",
     "legendFormat": "{{ region }}-{{ pod }}"
    }
   ]
  },
  {
   "title": "TTFF - 75th Percentile (BigQuery)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "dataset": "analytics",
     "location": "US",
     "project": "livepeer-analytics",
     "rawSql": "SELECT \ntimestamp_trunc(time, hour) _hour,\nAPPROX_QUANTILES(`source`.`ttff_ms`, 100)[OFFSET(75)] AS `TTFF_75th_Percentile`\n\nFROM (\n  select *\n  FROM `analytics.playback`\n  LEFT JOIN `analytics.studio_users` `Studio_Users` ON `analytics.playback`.`user_id` = `Studio_Users`.`user_id`\n\n  WHERE (`Studio_Users`.`internal` = FALSE\n     AND `analytics.playback`.`play_intent` = TRUE)\n  ) `source` \n  \nWHERE (\n  `source`.`type` = 'asset' \n  AND unix_millis(time) >= ${__from} and unix_millis(time) <= ${__to} \n  )\nGROUP BY 1 \n\nORDER BY 1 desc\n\n\n"
    }
   ]
  },
  {
   "title": "Upload Success (BigQuery)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "analytics",
     "location": "US",
     "project": "livepeer-analytics",
     "rawSql": "select \ntimestamp_trunc(a.created_at_ts, hour) as _hour,\navg(success) as upload_success \n\nfrom analytics.studio_assets as a join analytics.studio_users as u \non a.user_id = u.user_id \n\nwhere not u.internal \nand not u.suspended \nand not excusable_error\nand a.created_at_ms >= ${__from}\nand a.created_at_ms <= ${__to}\n\ngroup by 1\norder by 1 desc"
    }
   ]
  },
  {
   "title": "Log count by app",
   "type": "timeseries",
   "description": "Shows how many log lines are produced by a given kubernetes application.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "sum by (app, container) (\n  rate(\n    {app=~\".+\", region!=\"sandbox\"}\n    [$__auto]\n  )\n)",
     "legendFormat": "{{app}} - {{container}}",
     "splitDuration": "15m"
    }
   ]
  },
  {
   "title": "Live Stream Success Rate (BigQuery)",
   "type": "timeseries",
   "description": "Tracks the hourly share of completed live stream sessions without errors, excluding suspended users or deleted media, to gauge overall streaming reliability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "analytics",
     "location": "US",
     "project": "livepeer-analytics",
     "rawSql": "\nSELECT timestamp_trunc(`analytics.nginx_session_summaries`.`end_session_ts`, hour, 'UTC') AS `end_session_ts`, \n(CAST(sum(CASE WHEN `analytics.nginx_session_summaries`.`any_error` = FALSE THEN 1 ELSE 0.0 END) AS float64) / CASE WHEN count(*) = 0 THEN NULL ELSE count(*) END) AS `Stream_Success_Rate`\nFROM `analytics.nginx_session_summaries`\nWHERE (\n  `analytics.nginx_session_summaries`.`media_deleted_or_suspended` = FALSE\n  AND `analytics.nginx_session_summaries`.`user_suspended` = FALSE \n  and unix_millis(end_session_ts) >= ${__from}\n  and unix_millis(end_session_ts) <= ${__to}\n  )\nGROUP BY `end_session_ts`\nORDER BY `end_session_ts` ASC"
    }
   ]
  }
 ]
}