{
 "title": "Catabalancer",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Request durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(request_type,success) (increase(catabalancer_request_duration_sum[5m])) / count by(request_type, success) (increase(catabalancer_request_duration_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\"catalyst.*\"} |= \"catabalancer\" |~ \"err|fail\""
    }
   ]
  },
  {
   "title": "Metric send loop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(region, pod) (increase(catabalancer_send_metric_duration_sum[5m])) / count by(region, pod) (increase(catabalancer_send_metric_duration_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB metric send duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(region, pod) (increase(catabalancer_send_db_duration_sum[5m])) / count by(region, pod) (increase(catabalancer_send_metric_duration_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stale data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(nodeID) (rate({app=\"catalyst-api\"} |~ `catabalancer skipping stale data while refreshing` | logfmt [$__auto]))"
    },
    {
     "expr": "sum by(nodeName) (rate({app=\"catalyst-api\"} |~ `stale stream info|stale metrics` | logfmt [$__auto]))"
    }
   ]
  }
 ]
}