{
 "title": "Catalyst Node Inspector",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": ".+" },
   { "name": "pod", "query": "prod-catalyst-.+" }
  ]
 },
 "panels": [
  {
   "title": "Incoming Streams",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(mist_sessions{sessType=\"incoming\", pod=~\"$pod\", region=~\"$region\", stream=~\".*vod.*\"} > 0) by (region, pod)",
     "legendFormat": "{{region}}-{{pod}}"
    },
    {
     "expr": "sum(mist_sessions{sessType=\"incoming\", pod=~\"$pod\", region=~\"$region\", stream!~\".*vod.*\"} > 0) by (region, pod)",
     "legendFormat": "{{region}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Viewer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(mist_sessions{pod=~\"$pod\", region=~\"$region\", sessType=\"viewers\"} > 0) by (region, pod, sessType)",
     "legendFormat": "{{region}}-{{pod}} ({{sessType}})"
    }
   ]
  },
  {
   "title": "VoD Segments Transcoded (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(region, pod) (increase(vod_transcoded_segments{pod=~\"$pod\", region=~\"$region\"}[1m]))",
     "legendFormat": "{{ region }}-{{ pod }}"
    }
   ]
  },
  {
   "title": "Log Lines by Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(\n  {region=~\"$region\", pod=~\"$pod\"}\n  | regexp \"^\\\\[?(?P<timestamp>[0-9- :]+)\\\\] ?(?P<process>[a-zA-Z0-9-_]+)\"\n[1m])) by (process)",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_cpu{catalyst_node=~\"${region}-${pod}.lp-playback.studio\"}[30s])/10) by (catalyst_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(avg_over_time(mist_mem_used{catalyst_node=~\"${region}-${pod}.lp-playback.studio\"}[180s])/10) by (catalyst_node)\n/ \nsum(avg_over_time(mist_mem_total{catalyst_node=~\"${region}-${pod}.lp-playback.studio\"}[180s])/10) by (catalyst_node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}