{
 "title": "confluent kafka monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(confluent_kafka_server_retained_bytes, kafka_id)"
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": "label_values(confluent_kafka_server_retained_bytes, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server utilization percentage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "confluent_kafka_server_cluster_load_percent * 100",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_partition_count{kafka_id=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Average active connections",
   "type": "stat",
   "description": "Average active connections",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(confluent_kafka_server_active_connection_count{kafka_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Number of active authenticated connections per user/service-account",
   "type": "timeseries",
   "description": "Number of active authenticated connections by principal_id (Filtering more than 10 active connections)\nprincipal_id is the authentication principal (Confluent Cloud User or Service Account)",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_active_connection_count{kafka_id=~\"$cluster\"}) by (principal_id) >= 10",
     "legendFormat": "{{principal_id}}"
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consumer Group Lag Offsets",
   "type": "timeseries",
   "description": "Number of pending read offsets per consumer group id not considering consumer group that starts with _confluent-ksql or connect-snk",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(consumer_group_id, topic) (confluent_kafka_server_consumer_lag_offsets{kafka_id=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages received by topic",
   "type": "timeseries",
   "description": "The delta count of records received. Each sample is the number of records received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(kafka_id, topic) (confluent_kafka_server_received_records{kafka_id=~\"$cluster\", topic=~\"$topic\"}) > 0",
     "legendFormat": "[{{kafka_id}}] {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes received by topic",
   "type": "timeseries",
   "description": "The delta count of bytes of the customer's data received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (kafka_id, topic) (confluent_kafka_server_received_bytes{kafka_id=~\"$cluster\",topic=~\"$topic\"}) > 0",
     "legendFormat": "[{{kafka_id}}] {{topic}}"
    }
   ]
  }
 ]
}