{
 "title": "Content classification",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Top Soccer Streams",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(avg by(manifest_id) (livepeer_segment_scene_class_prob{seg_class_name=\"soccer\"} > 0.5))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Adult Streams",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(avg by(manifest_id) (livepeer_segment_scene_class_prob{seg_class_name=\"adult\"} > 0.5))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Content detection events per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(count(livepeer_segment_scene_class_prob{}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}