{
 "title": "CPU / viewers",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   { "name": "CPUThreshold", "label": "CPU Threshold", "query": "10,20,30,40,50,60,70,80,90" },
   {
    "name": "ViewersPerNodeThreshold",
    "label": "Viewers Per Node Threshold",
    "query": "0,50,100,150,200,250,300,350,400,450,500,550,600,650,700,750,800,850,900,950,1000"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance, region) (irate(node_cpu_seconds_total{region != \"eu-metrics\", mode=\"idle\", instance=~\".+:9100\"}[1m])) * 100 * on(instance) group_left(nodename) node_uname_info) > $CPUThreshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "> $ViewersPerNodeThreshold viewer per node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\", stream!~\"$exclude\"}) by (node_name, region) > $ViewersPerNodeThreshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "viewers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\", stream!~\"$exclude\"}[1m] ) by (stream) or on() vector(0), \"stream_id\", \"$1\", \"stream\", \".*\\\\+(.*)\") > $ViewersPerNodeThreshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Origin server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "count by(node_name, region) (mist_sessions{sessType=\"incoming\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VoD Segments Transcoded",
   "type": "timeseries",
   "description": "vod_transcoded_segments",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(catalyst_node) (increase(vod_transcoded_segments[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}