{
 "title": "Fishtank",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ROOMS",
    "query": ".*fca9fz1pvns5f7qv,.*3eb4mll2jrdt99jb,.*31b47qeszq0xueoo,.*f9934rpx9wkuoulf,.*68b8mdxle4jtgwfe,.*526d2dcxd0lr6i4z,.*f3c1n4zuqsqy6wvb,.*6f06zkobg5cgxc95,.*1d12zldyh0jmhqxd,.*e618njb23zzsrw24,.*9b10xxzabnbd2zon,.*7ab7jmupinhio7wo,.*aa496s10brdddagd,.*f03393v3pti4z7ok,.*854cx0awr3bpmxz"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Viewers per room",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\"${ROOMS:pipe}\"}[1m] ) by (stream) or on() vector(0), \"stream_id\", \"$1\", \"stream\", \".*\\\\+(.*)\")",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Viewers per region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\"${ROOMS:pipe}\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Viewers per node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\"${ROOMS:pipe}\"}[1m] ) by (catalyst_node) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}