{
 "title": "Global Usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ingest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Streams by Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"}) by (region)",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Transcoding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Segments Transcoded per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_transcoded_total{node_type=\"orch\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Segments Transcoded per second by region (Broadcaster Report)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"prod-livepeer-broadcaster.+\"} |~ \"Successfully transcoded segment\" | pattern \"<_> orchestrator=https://<orch_region>-\"[1m])) by (orch_region)",
     "legendFormat": "{{ orch_region }}"
    }
   ]
  },
  {
   "title": "Segments Transcoded per second by region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum by (region) (rate(livepeer_segment_transcoded_total{node_type=\"orch\"}[$__rate_interval]))",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Real-time ratio p95 by broadcaster region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum by (le, region) (rate(livepeer_http_client_segment_transcoded_realtime_ratio_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Real-time ratio p95 by orchestrator region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum by (le, region) (rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Playback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Playback requests per minute per region",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum (count_over_time(\n  {app=\"traefik\"} \n  | json \n  | __error__!=\"JSONParserErr\"\n  | RequestMethod=\"GET\"\n  | RequestPath=~\"/hls/.+\" [10m])) by (region) / 10"
    }
   ]
  },
  {
   "title": "Highest Playback Traffic Streams (past 10min)",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum (count_over_time({app=\"traefik\"}  \n  | json \n  | __error__!=\"JSONParserErr\"\n  | RequestMethod=\"GET\"\n  | RequestPath=~\"/hls/.+\"\n  | regexp \".+/hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\" \n  | regexp \".+playback-792e3a71a26-(?P<mist_instance>.+)-livepeer-com@kubernetes.+\" [10m])\n) by (playback_id, region, mist_instance) / 10"
    }
   ]
  }
 ]
}