{
 "title": "high IO issue",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datapacket_instance",
    "label": "Datapacket instance",
    "query": "All : .+, dp2495 : 185.246.209.222:9100, dp4392 : 185.246.209.224:9100, dp4611 : 185.246.209.223:9100, dp8312 : 79.127.221.98:9100, dp12606 : 79.127.221.97:9100, dp8128 : 79.127.197.177:9100, dp12551 : 79.127.197.178:9100, dp9334 : 79.127.199.49:9100, dp18052 : 79.127.199.50:9100, dp1856 : 143.244.61.193:9100, dp3214 : 143.244.60.234:9100, dp5631 : 143.244.60.233:9100, dp5773 : 89.187.181.163:9100, dp13079 : 79.127.201.97:9100, dp19409 : 79.127.201.98:9100, dp6442 : 138.199.36.76:9100, dp7744 : 195.181.174.186:9100, dp4821 : 195.181.174.33:9100, dp5254 : 169.150.243.18:9100, dp6281 : 143.244.33.56:9100, dp9532 : 169.150.243.19:9100, dp9534 : 169.150.243.17:9100, dp7009 : 169.150.243.20:9100, dp6883 : 79.127.219.1:9100, dp10448 : 79.127.219.2:9100, dp3366 : 79.127.219.9:9100, dp12589 : 79.127.219.3:9100, dp6448 : 84.17.50.98:9100, dp6449 : 84.17.50.99:9100, dp6638 : 185.59.221.179:9100, dp1312 : 212.102.38.92:9100, dp5585 : 89.187.185.251:9100, dp6179 : 89.187.185.153:9100, dp6748 : 138.199.4.161:9100, dp12874 : 121.127.46.158:9100, dp6247 : 121.127.47.9,"
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(kube_node_labels{region!=\"analytics\"},region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "etcd operation took too longer than 1s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(node_name, region) (rate({job=\"systemd-journal\", region=~\"${region:pipe}\",  node_name=~\"${datapacket_instance:text}\"} |~ `took too long.*[0-9]s\",\"expected` [$__auto]))\n\n"
    }
   ]
  },
  {
   "title": "node_disk_io_time_weighted_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(region, instance) (increase(node_disk_io_time_weighted_seconds_total{instance=~\"${datapacket_instance:pipe:value}\", region=~\"${region:pipe}\"}[$__interval]))",
     "legendFormat": "{{region}} {{ instance }}"
    }
   ]
  },
  {
   "title": "node_disk_write_time_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(region, instance) (increase(node_disk_write_time_seconds_total{instance=~\"${datapacket_instance:pipe:value}\", region=~\"${region:pipe}\"}[$__interval]))",
     "legendFormat": "{{region}} {{ instance }}"
    }
   ]
  }
 ]
}