{
 "title": "kubernetes Restarts Issue",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(kube_node_labels{region!=\"analytics\", region!=\"eu-metrics\"},region)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{region!=\"analytics\", region!=\"eu-metrics\", region=~\"$region\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "kube_endpoint_address_not_ready (cause of 5XX)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(endpoint, region) (kube_endpoint_address_not_ready{node_name=~\"${node:pipe}\", region=~\"${region:pipe}\"}) > 0\n\n",
     "legendFormat": "{{region}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "kubernetes restarted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count by(node_name, region) (rate({job=\"systemd-journal\", region=~\"${region:pipe}\", node_name=~\"${node:pipe}\"} |~ `Started Lightweight Kubernetes` [$__auto]))",
     "legendFormat": "{{region}}-{{node_name}}"
    }
   ]
  },
  {
   "title": "catalyst logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"catalyst\", region=~\"${region:pipe}\", node_name=~\"${node:pipe}\"}"
    }
   ]
  },
  {
   "title": "etcd operation took too longer than 1s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count by(node_name, region) (rate({job=\"systemd-journal\", region=~\"${region:pipe}\", node_name=~\"${node:pipe}\"} |~ `took too long.*[0-9]s\",\"expected` [$__auto]))",
     "legendFormat": "{{region}}-{{node_name}}"
    }
   ]
  },
  {
   "title": "etcd operation took too longer than 100ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "count by(node_name, region) (rate({job=\"systemd-journal\", region=~\"${region:pipe}\", node_name=~\"${node:pipe}\"} |~ `took too long.*[0-9]` [$__auto]))",
     "legendFormat": "{{region}}-{{node_name}}"
    }
   ]
  },
  {
   "title": "systemd-journal logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", region=~\"${region:pipe}\", node_name=~\"${node:pipe}\"}"
    }
   ]
  },
  {
   "title": "node_disk_io_time_weighted_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(region, nodename) (increase(node_disk_io_time_weighted_seconds_total{nodename=~\"${node:pipe}\", region=~\"${region:pipe}\"} * on(instance) group_left(nodename) (node_uname_info)))",
     "legendFormat": "{{region}}-{{nodename}}"
    }
   ]
  },
  {
   "title": "node_disk_write_time_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum by(region, nodename) (increase(node_disk_write_time_seconds_total{nodename=~\"${node:pipe}\", region=~\"${region:pipe}\"} * on(instance) group_left(nodename) (node_uname_info)))",
     "legendFormat": "{{region}}-{{nodename}}"
    }
   ]
  },
  {
   "title": "container_fs_writes_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "sum by(region, instance, container) (increase(container_fs_writes_bytes_total{instance=~\"${node:pipe}\", region=~\"${region:pipe}\"}))",
     "legendFormat": "{{region}}-{{instance}}-{{container}}"
    }
   ]
  }
 ]
}