{
 "title": "kube-nodes-connected",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Remote timeouts connecting to this node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {app=\"kube-nodes-connected\"}\n    |= \"NODE_TIMEOUT\"\n    | logfmt\n    [15s]\n  )\n) by (remoteNode, region)",
     "legendFormat": "{{region}}-{{remoteNode}}"
    }
   ]
  },
  {
   "title": "Remote timeouts connecting FROM this node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {app=\"kube-nodes-connected\"}\n    |= \"NODE_TIMEOUT\"\n    | logfmt\n    [15s]\n  )\n) by (localNode, region)",
     "legendFormat": "{{region}}-{{localNode}}"
    }
   ]
  },
  {
   "title": "Missing Flannel Annotations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_annotations{annotation_flannel_alpha_coreos_com_backend_data=\"\"}",
     "legendFormat": "{{region}}-{{ node }}"
    }
   ]
  }
 ]
}