{
 "title": "Livestreaming Reliability Overview",
 "description": "All the best graphs for checking livestreaming reliability ❤",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resource usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max(mist_shm_used{catalyst_node=~\".*studio\"} / mist_shm_total{catalyst_node=~\".*studio\"} * 100) by (region) >\nmax(avg_over_time(mist_cpu{catalyst_node=~\".*studio\"}[3m])/10) by (region) >\nmax(mist_mem_used{catalyst_node=~\".*studio\"} / mist_mem_total{catalyst_node=~\".*studio\"} * 100) by (region))\nor\n(max(mist_mem_used{catalyst_node=~\".*studio\"} / mist_mem_total{catalyst_node=~\".*studio\"} * 100) by (region) >\nmax(mist_shm_used{catalyst_node=~\".*studio\"} / mist_shm_total{catalyst_node=~\".*studio\"} * 100) by (region) >\nmax(avg_over_time(mist_cpu{catalyst_node=~\".*studio\"}[3m])/10) by (region))\nor\n(max(avg_over_time(mist_cpu{catalyst_node=~\".*studio\"}[3m])/10) by (region) >\nmax(mist_shm_used{catalyst_node=~\".*studio\"} / mist_shm_total{catalyst_node=~\".*studio\"} * 100) by (region) >\nmax(mist_mem_used{catalyst_node=~\".*studio\"} / mist_mem_total{catalyst_node=~\".*studio\"} * 100) by (region))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 1 },
   "options": {
    "content": "This is the maximum of the shared memory, general RAM and CPU used on the nodes, as a percentage. If this nears 100%, that means there aren't enough servers in that region to handle the load. If it nears 0% that means there isn't enough load to warrant the current deployment size."
   }
  },
  {
   "title": "Transcode timeouts / second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"catalyst\"} |= \"MistProcLivepeer\" |= \"timed out after\")[2m])) by (region)/120",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Transcode timeouts",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "This should be zero/blank if all is running perfectly. The livestreams automatically abort and retry if a timeout occurs, but multiple timeouts in a row will drastically affect player experience."
   }
  },
  {
   "title": "Viewers by region",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mist_sessions{sessType=\"viewers\",catalyst_node=~\".*studio\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Viewers",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 11 },
   "options": {
    "content": "Tracks active viewers by region. In general, sudden changes here indicate a potential problem (or popular stream starting/stopping)."
   }
  },
  {
   "title": "Viewers by protocol",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mist_outputs{catalyst_node=~\".*studio\",output!=\"\"}) by (output)",
     "legendFormat": "{{region}} {{output}}"
    }
   ]
  },
  {
   "title": "Trigger failure rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_fails{catalyst_node=~\".*studio\"}[15m])) by (region, trigger) / on(region, trigger) sum(rate(mist_trigger_count{catalyst_node=~\".*studio\"}[15m])) by (region, trigger) > 0",
     "legendFormat": "{{region}}: {{trigger}}"
    }
   ]
  },
  {
   "title": "Trigger failures",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 21 },
   "options": {
    "content": "Trigger failures indicate a problem with integration between the media server and the systems surrounding it. Depending on the trigger affected, there may or may not be noticible degradation of service. The most important ones are `USER_NEW` (handles viewer authorization) and `PUSH_REWRITE` (handles incoming push authorization)."
   }
  },
  {
   "title": "Reconnects per 10 minutes per user by region",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{catalyst_node=~\".*studio\",sessType=\"viewers\"}[10m])) by (region)\n/\n(sum(mist_sessions{catalyst_node=~\".*studio\",sessType=\"viewers\"}) by (region) > 25)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Reconnects",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 21 },
   "options": {
    "content": "This basically shows new connections to regions as a fraction of the total viewers. Consider it a view of connection \"stickiness\", where anything under 1 is generally \"very good and the higher above 1 the worse it is. People refreshing the page (or, well, not liking the stream contents) will cause this number to go up."
   }
  },
  { "title": "Source Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Percentage healthy streams",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(mist_health_count{health=\"good\"}) by (region) / (sum(mist_health_count) by (region))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time((sum(mist_health_count{health=\"good\"}) / sum(mist_health_count))[1h])",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Healthy streams",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 32 },
   "options": {
    "content": "This measures whether the configuration of the incoming stream is correct (e.g. user error).\nIf there is something wrong with the input that makes streaming it smoothly tricky/hard/impossible, the stream is considered unhealthy.\nStreams without problems are considered healthy. It's actually possible to query the corresponding node over API to get _why_ a stream is unhealthy, as well!"
   }
  },
  {
   "title": "Incoming streams by region and health",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mist_health_count) by (region,health)",
     "legendFormat": "{{region}} {{health}}"
    }
   ]
  },
  {
   "title": "Healthy streams, current",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 32 },
   "options": {
    "content": "The same data as on the left, but:\n- Raw values\n- Color-coded for visibility\n- Only the most recent datapoint"
   }
  },
  { "title": "Edge Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Flawless playback percentage per region",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(mist_playux_perfect) by (region) / ((sum(mist_playux_bad) by (region) + sum(mist_playux_okay) by (region) + sum(mist_playux_perfect) by (region)) > 25)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flawless playback",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 43 },
   "options": {
    "content": "Every concurrent viewer is given a score of \"bad\", \"okay\" and \"perfect\".\nThis graph tracks regions with 25+ viewers and shows what percentage of them had a \"perfect\" score, over time. If this is around 90%, that's considered a good result.\nMuch below it _can_ indicate a problem.\nIt's normal for this to never reach 100%, as it would require **every** viewer to have good hardware **and** a good connection, which is not likely to happen."
   }
  },
  {
   "title": "Latency pulling from other regions, averaged across all regions/all streams",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(mist_latency < 30000 > -30000) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}