{
 "title": "Loki Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Default",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unrecoverable Orchestrators",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\".*prod.+orchestrator.*\"} |= \"Unrecoverable state\" [150s])) by (region, pod)",
     "legendFormat": "{{region}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Excessive MistProcLivepeer restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (manifest_id, region, pod) (count_over_time(\n  {app=\"mist\", container=\"mist\"} \n  |= \"Starting process: /usr/bin/MistProcLivepeer\" \n  | pattern `<_>\"source\":\"video<_>+<manifest_id>\"` [4m]\n)) > 1",
     "legendFormat": "{{manifest_id}} @ {{region}}-{{pod}}"
    }
   ]
  },
  {
   "title": "RabbitMQ broken client credentials",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"prod-.+\",app!=\"prod-monitoring\"} |= \"username or password not allowed\" [1m])) by (app, region)",
     "legendFormat": "{{region}}-{{app}}"
    }
   ]
  },
  {
   "title": "Tasks/VOD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Queue Accumulation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "count by (region) (count by (region, taskId) (\n  count_over_time({app=\"prod-livepeer-api\",region!=\"sin\"} |= \"publishing message to task.trigger\" | pattern \"<_>task.trigger.<type>.<taskId> on exchange<_>\" [15m])\n))\n- \ncount by (region) (count by (region, taskId) (\n  count_over_time({app=\"prod-task-runner\"} |= \"Starting task\" | logfmt | label_format taskId=id [15m])\n))"
    }
   ]
  },
  {
   "title": "Poison Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "count by (id, region) (count_over_time({app=\"prod-task-runner\"} |= \"Starting task\" | logfmt [2h])) > 3"
    }
   ]
  },
  {
   "title": "Assets with considerable start_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max_over_time(\n    {app=\"prod-task-runner\"} \n    |= \"Probed video file\"\n    | logfmt \n    | maxStreamStartTime > 0.1 \n    | unwrap maxStreamStartTime [10m]\n) by (assetId)",
     "legendFormat": "{{ assetId }}"
    }
   ]
  },
  {
   "title": "Task failures by region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"prod-livepeer-api\"} |= \"publishing message to events.task.failed\" != \"\\\"retries\\\":0\" [2m])) by (region)"
    }
   ]
  },
  {
   "title": "Recent VOD task internal errors",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "{app=\"prod-task-runner\"} |= \"Task handler processed task\" \n| logfmt | error != \"%!q(<nil>)\" | unretriable=\"false\" \n| line_format \"{{ .error }}\""
    }
   ]
  }
 ]
}