{
 "title": "Mainnet Wallet Funds",
 "description": "Panels for monitoring the deposit amount available in the wallets used for mainnet jobs. Both transcoding and AI.",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Deposit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Video Gateways (Broadcasters) Deposit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "avg(\n    livepeer_gateway_deposit{livepeer_live_app=\"prod-livepeer-broadcaster\"} # standalone broadcasters\n    or livepeer_gateway_deposit{job=\"broadcaster\"} # catalyst nodes\n) / 1e9 # ETH (livepeer_gateway_deposit metric in gwei)",
     "legendFormat": "0xc3c7...e61E"
    }
   ]
  },
  {
   "title": "AI Gateways Deposit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "avg(livepeer_gateway_deposit{livepeer_live_app=\"prod-livepeer-ai-gateway\"}) / 1e9 # ETH (metric in gwei)",
     "legendFormat": "0xca33...7fef"
    }
   ]
  },
  { "title": "Reserve", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Video Gateways (Broadcasters) Reserve",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "avg(\n    livepeer_gateway_reserve{livepeer_live_app=\"prod-livepeer-broadcaster\"} # standalone broadcasters\n    or livepeer_gateway_reserve{job=\"broadcaster\"} # catalyst nodes\n) / 1e9 # ETH (metric in gwei)",
     "legendFormat": "0xc3c7...e61E"
    }
   ]
  },
  {
   "title": "AI Gateways Reserve",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "avg(livepeer_gateway_reserve{livepeer_live_app=\"prod-livepeer-ai-gateway\"}) / 1e9 # ETH (metric in gwei)",
     "legendFormat": "0xca33...7fef"
    }
   ]
  },
  {
   "title": "Engineering Wallet",
   "type": "timeseries",
   "description": "Delayed 5 minutes from the actual blockchain state",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "avg by(address, wallet) (last_over_time(livepeer_eth_wallet_balance_wei[$__interval])) / 1000000000000000000",
     "legendFormat": "{{ wallet }} {{ address }}"
    }
   ]
  }
 ]
}