{
 "title": "MediaGuard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "✅ Prod MediaGuard successes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(test) (count_over_time(media_guard_successes_count{ecosystem=\"live\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "❌ Prod MediaGuard failures ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(test) (count_over_time(media_guard_failures_count{ecosystem=\"live\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prod MediaGuard logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"default/prod-media-guard\"}"
    }
   ]
  },
  {
   "title": "Prod MediaGuard runtime (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(test) (increase(media_guard_test_time_seconds{quantile=\"0.99\", ecosystem=\"live\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Staging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "✅ Staging MediaGuard successes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(test) (count_over_time(media_guard_successes_count{ecosystem=\"monster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "❌ Staging MediaGuard failures ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(test) (count_over_time(media_guard_failures_count{ecosystem=\"monster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staging MediaGuard logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{job=\"default/staging-media-guard\"}"
    }
   ]
  },
  {
   "title": "Staging MediaGuard runtime (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "max by(test) (max_over_time(media_guard_test_time_seconds{quantile=\"0.99\", ecosystem=\"monster\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}