{
 "title": "Memory Sluething",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node" }
  ]
 },
 "panels": [
  {
   "title": "MEMORY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{}) / 1024/ 1024 / 1024 * on(instance) group_left(nodename) node_uname_info{nodename=\"$node\"}",
     "legendFormat": "node_memory"
    },
    {
     "expr": "mist_mem_used{node_name=\"$node\"} / 1024 / 1024",
     "legendFormat": "mist_mem_used"
    },
    {
     "expr": "mist_mem_total{node_name=\"$node\"} / 1024 / 1024",
     "legendFormat": "mist_mem_total"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_cpu{node_name=\"$node\"}[180s])/10)",
     "legendFormat": "mist_cpu"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=~\"true\", node=\"$node\"} > 0)",
     "legendFormat": "ready=true"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=~\"false\", node=\"$node\"} > 0)",
     "legendFormat": "ready=false"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=~\"unknown\", node=\"$node\"} > 0)",
     "legendFormat": "ready=unknown"
    }
   ]
  },
  {
   "title": "Node Identity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mist_cpu{node_name=\"$node\"} * 0 + 1",
     "legendFormat": "{{ catalyst_node }}"
    }
   ]
  },
  {
   "title": "OOM Killer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({node_name=\"$node\", job=\"systemd-journal\", unit=\"\"} |~ \"invoked oom-killer\"[1m]))",
     "legendFormat": "OOM Killer"
    }
   ]
  },
  {
   "title": "Logs by Unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({node_name=\"$node\", job=\"systemd-journal\"} [1m])) ",
     "legendFormat": "{{ unit }}"
    }
   ]
  },
  {
   "title": "Incoming Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(mist_sessions{node_name=\"$node\", sessType=\"incoming\"})",
     "legendFormat": "Stream Count"
    }
   ]
  }
 ]
}