{
 "title": "Mist instance health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "srv",
    "label": "Mist instance",
    "query": {
     "query": "label_values(mist_mem_total,catalyst_node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mist_cpu{catalyst_node=\"$srv\"} / 10",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mist_mem_used{catalyst_node=\"$srv\"} / mist_mem_total{catalyst_node=\"$srv\"} * 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "mist_shm_used{catalyst_node=\"$srv\"} / mist_shm_total{catalyst_node=\"$srv\"} * 100",
     "legendFormat": "SHM"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "increase(mist_logs{catalyst_node=\"$srv\"}[30s]) / 30",
     "legendFormat": "Logs per second"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mist_sessions_total{catalyst_node=\"$srv\"}",
     "legendFormat": "{{sessType}}"
    }
   ]
  },
  {
   "title": "Version running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "version{app=\"MistServer\",catalyst_node=\"$srv\"}",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}