{
 "title": "Mist Trigger overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "lookat",
    "label": "Split by",
    "query": "Region : region, Node : catalyst_node, Trigger : trigger"
   }
  ]
 },
 "panels": [
  {
   "title": "Trigger failure rate",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_fails{catalyst_node=~\".*studio\"}[15m])) by ($lookat) / on($lookat) sum(rate(mist_trigger_count{catalyst_node=~\".*studio\"}[15m])) by ($lookat)",
     "legendFormat": "{{$lookat}}"
    }
   ]
  },
  {
   "title": "Trigger runtime",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_time{catalyst_node=~\".*studio\"}[15m])) by ($lookat) / on($lookat) sum(rate(mist_trigger_count{catalyst_node=~\".*studio\"}[15m])) by ($lookat)",
     "legendFormat": "{{$lookat}}"
    }
   ]
  },
  {
   "title": "Trigger rate",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_count{catalyst_node=~\".*studio\"}[10m])) by ($lookat)",
     "legendFormat": "{{$lookat}}"
    }
   ]
  }
 ]
}