{
 "title": "Mist packet loss",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(mist_packets_total,region)"
    }
   },
   {
    "name": "catalyst_node",
    "query": {
     "query": "label_values(mist_packets_total{region=~\"${region:pipe}\"},catalyst_node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lost packets per viewer per second",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((sum(increase(mist_packets_total{pkttype=\"lost\",region=~\"${region:pipe}\",catalyst_node=~\"${catalyst_node:pipe}\"}[5m])) by (catalyst_node) / 300) / on(catalyst_node) (mist_outputs{output=\"WebRTC\",region=~\"${region:pipe}\",catalyst_node=~\"${catalyst_node:pipe}\"} > 100)) > 10000",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "(Objectively) biggest losers",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(mist_packets_total{pkttype=\"lost\",region=~\"${region:pipe}\",catalyst_node=~\"${catalyst_node:pipe}\"}[10m])) by (catalyst_node) / 600",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Lost percentage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(mist_packets_total{pkttype=\"lost\",region=~\"${region:pipe}\",catalyst_node=~\"${catalyst_node:pipe}\"}[1m])) by (catalyst_node) / sum(increase(mist_packets_total{pkttype=\"sent\",region=~\"${region:pipe}\",catalyst_node=~\"${catalyst_node:pipe}\"}[1m])) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  }
 ]
}