{
 "title": "Network Outage Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "networkd messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"systemd-journal\", unit=\"systemd-networkd.service\"}[5m])) by (region)  > 14",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "networkd logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", unit=\"systemd-networkd.service\"} | regexp \"(?P<line>.*)\" |  line_format \"{{ .region }} {{ .node_name }} {{ .ts }} {{ .line }}\""
    }
   ]
  },
  {
   "title": "Link DOWN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"systemd-journal\", unit=\"systemd-networkd.service\"} |~ \"Link DOWN\" [1m])) by (region)  ",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "networkd-dispatcher.service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"systemd-journal\", unit=\"networkd-dispatcher.service\"}[1m])) by (region)"
    }
   ]
  }
 ]
}