{
 "title": "OOM killer",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {}
   },
   {
    "name": "node_name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Out-of-memory killed processes",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(region, node_name, process_name) (count_over_time({job=\"systemd-journal\", region=~\"${region:pipe}\", node_name=~\"${node_name:pipe}\"} |~ `(?i)out of memory` | regexp `ut of memory\\: Killed process .+ \\((?P<process_name>.+)\\)` [$__auto]))",
     "legendFormat": "{{region}} {{node_name}} {{process_name}}"
    }
   ]
  },
  {
   "title": "journal logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", region=~\"${region:pipe}\", node_name=~\"${node_name:pipe}\"} |~ `Out of memory|oom-kill|Killed`"
    }
   ]
  },
  {
   "title": "Containers high memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",region=~\"${region:pipe}\",kubernetes_io_hostname=~\"${node_name:pipe}\"}) by (container_name, pod_name) > 4294967296",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",region=~\"${region:pipe}\",kubernetes_io_hostname=~\"${node_name:pipe}\"}) by (kubernetes_io_hostname, name, image) > 4294967296",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",region=~\"${region:pipe}\",kubernetes_io_hostname=~\"${node_name:pipe}\"}) by (kubernetes_io_hostname, rkt_container_name) > 4294967296",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  }
 ]
}