{
 "title": "Orchestrator swaps",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(livepeer_orchestrator_swaps,region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "swaps per minute by region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(region) (rate(livepeer_orchestrator_swaps{region!~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(region) (rate(livepeer_orchestrator_swaps{region=~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval]))",
     "legendFormat": "VOD {{region}}"
    }
   ]
  },
  {
   "title": "swaps per minute by node_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(region, node_id) (rate(livepeer_orchestrator_swaps{region!~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval]))",
     "legendFormat": "{{region}} {{node_id}}"
    },
    {
     "expr": "sum by(region, node_id) (rate(livepeer_orchestrator_swaps{region=~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval]))",
     "legendFormat": "VOD {{region}} {{node_id}}"
    }
   ]
  },
  {
   "title": "swaps by region over the number of source segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(region) (rate(livepeer_orchestrator_swaps{region!~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval])) / sum by (region) (rate(livepeer_segment_source_emerged_total{region!~\"atl|mad\", region=~\"${region:pipe}\"}))",
     "legendFormat": "{{region}}"
    },
    {
     "expr": "sum by(region) (rate(livepeer_orchestrator_swaps{region=~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval])) / sum by (region) (rate(livepeer_segment_source_emerged_total{region=~\"atl|mad\", region=~\"${region:pipe}\"}))",
     "legendFormat": "VOD {{region}}"
    }
   ]
  },
  {
   "title": "swaps by node_id over the number of source segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(region, node_id) (rate(livepeer_orchestrator_swaps{region!~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval])) / sum by (region, node_id) (rate(livepeer_segment_source_emerged_total{region!~\"atl|mad\", region=~\"${region:pipe}\"}))",
     "legendFormat": "{{region}} {{node_id}}"
    },
    {
     "expr": "sum by(region, node_id) (rate(livepeer_orchestrator_swaps{region=~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval])) / sum by (region, node_id) (rate(livepeer_segment_source_emerged_total{region=~\"atl|mad\", region=~\"${region:pipe}\"}))",
     "legendFormat": "VOD {{region}} {{node_id}}"
    }
   ]
  },
  {
   "title": "VOD vs live swaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(livepeer_orchestrator_swaps{region!~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval]))",
     "legendFormat": "live"
    },
    {
     "expr": "sum(rate(livepeer_orchestrator_swaps{region=~\"atl|mad\", region=~\"${region:pipe}\"}[$__interval]))",
     "legendFormat": "VOD"
    }
   ]
  },
  {
   "title": "Broadcaster logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"prod-livepeer-broadcaster\", region=~\"${region:pipe}\"} |~ `Removing orch=.*session list|Swapping from orch=`"
    }
   ]
  },
  {
   "title": "Transcode Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_transcode_failed_total{region=~\"${region:pipe}\"}[1m])) by (error_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Streams",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(region) (mist_sessions{catalyst=\"true\", sessType=\"incoming\", region=~\"${region:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}