{
 "title": "Orchestrator versions",
 "time": { "from": "now-10d", "to": "now" },
 "panels": [
  {
   "title": "Orchestrator versions (from catalyst)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(orchestrator_version) (count by(orchestrator_version, orchestrator_uri) (increase(livepeer_transcode_overall_latency_seconds_sum{pod=~\".*catalyst.*\"}[$__rate_interval])))",
     "legendFormat": "{{orchestrator_version}}"
    }
   ]
  },
  {
   "title": "Orchestrator versions (from broadcasters)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "count by(orchestrator_version) (count by(orchestrator_version, orchestrator_uri) (increase(livepeer_transcode_overall_latency_seconds_sum{job=\"broadcaster\"}[$__rate_interval])))",
     "legendFormat": "{{orchestrator_version}}"
    }
   ]
  },
  {
   "title": "Orchestrator versions (from ai-gateway)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by(orchestrator_version) (count by(orchestrator_uri, orchestrator_version) (increase(livepeer_ai_request_latency_score{livepeer_live_app=~\".*-livepeer-ai-gateway\"}[$__rate_interval])))",
     "legendFormat": "{{orchestrator_version}}"
    }
   ]
  }
 ]
}