{
 "title": "Origin Analysis",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Origins",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(\n  {app=\"traefik\", region!=\"eu-metrics\", container=\"prod-traefik\"} \n  | json \n  | __error__!=\"JSONParserErr\"\n  | request_Origin != \"\"\n  | line_format \"{{.request_Origin}}\"[1m]\n)) by (request_Origin) > 100",
     "legendFormat": "{{ request_Origin }}"
    },
    {
     "expr": "sum(count_over_time({namespace=\"prod\", app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<originUrl>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | originUrl != \"-\" | line_format \"{{ .originUrl }}\" | pattern \"<originScheme>://<originDomain>/<originPath>\" | line_format \"{{ .originDomain }}\"[1m])) by (originDomain)",
     "legendFormat": "{{ originDomain }}"
    }
   ]
  },
  {
   "title": "Streams by Origin",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time(\n  {app=\"traefik\", region!=\"eu-metrics\", container=\"prod-traefik\"} \n  | json \n  | __error__!=\"JSONParserErr\"\n  | origin_Origin != \"\"\n  | OriginStatus != \"404\"\n  | regexp \"/hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\"\n  | playback_id != \"\" [1m]\n)) by (request_Origin, playback_id) ",
     "legendFormat": "{{ playback_id }} - {{ request_Origin }}"
    },
    {
     "expr": "sum(count_over_time({namespace=\"prod\", app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<origin>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | line_format \"{{ .url }}\" | pattern \"/hls/<base>+<playback_id>/\"[1m])) by (origin, playback_id)",
     "legendFormat": "{{ playback_id }} - {{ origin }}"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"prod\", app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<origin>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>`| origin != \"-\" [1m] )) by (userAgent)",
     "legendFormat": "{{ userAgent }}"
    }
   ]
  }
 ]
}