{
 "title": "papertrail alerts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "\"no sender deposit\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"prod-livepeer-secondary-broadcaster.+\"} |~ \"no sender deposit\"[1m])) by (region)",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "increased panics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"prod-.+\", container!=\"lpmonitoring\"} |= \"panic\" [1m]))"
    }
   ]
  },
  {
   "title": "etcd write failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (region) (count_over_time({app=\"mist\"} |~ \"Error creating etcd Traefik rule\"[1m]))"
    }
   ]
  },
  {
   "title": "zombie external dns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"external-dns\"} |= \"owner id does not match\"[1m])) by (region)"
    }
   ]
  },
  {
   "title": "request per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | line_format \"{{ .url }}\" | pattern \"/hls/<base>+<playback_id>/\"[1m])) by (region, playback_id)"
    }
   ]
  },
  {
   "title": "Stream Health Publish Error ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (region, app) (count_over_time({app=~\"prod-livepeer-broadcaster.*\"} |= \"Error publishing stream transcode event\"[1m]))"
    }
   ]
  },
  {
   "title": "API DB Connection Timeouts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (region) (count_over_time({app=\"prod-livepeer-api\"} |= \"Connection terminated due to connection timeout\"[1m]))"
    }
   ]
  },
  {
   "title": "RabbitMQ Network Partition By region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"prod-rabbitmq\",component=\"rabbitmq\"} |~ \"mnesia_event\" |~ \"inconsistent_database\" |~ \"running_partitioned_network\"[1m])) by (region)"
    }
   ]
  },
  {
   "title": "KRYPTONITE",
   "type": "timeseries",
   "description": "[LOPRI] KRYPTONITE DETECTED!!! 🦠",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"prod-livepeer-broadcaster.*\"} |~ \"Hit max transcode attempts: body timeout: context deadline exceeded\"[1m]))"
    }
   ]
  }
 ]
}