{
 "title": "Player experience",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Player User Experience",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(mist_playux_perfect) / ((sum(mist_playux_bad) + sum(mist_playux_perfect) + sum(mist_playux_okay)) > 10)",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Player User Experience",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 1 },
   "targets": [
    { "expr": "sum(mist_playux_bad)", "legendFormat": "Bad" },
    { "expr": "sum(mist_playux_okay)", "legendFormat": "Okay" },
    { "expr": "sum(mist_playux_perfect)", "legendFormat": "Perfect" }
   ]
  },
  {
   "title": "By type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UX: Flawless playback percentage per server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(mist_playux_perfect) by (catalyst_node) / ((sum(mist_playux_bad) by (catalyst_node) + sum(mist_playux_okay) by (catalyst_node) + sum(mist_playux_perfect) by (catalyst_node)) > 10)",
     "legendFormat": "{{ catalyst_node }}"
    }
   ]
  },
  {
   "title": "UX: Flawless playback percentage per protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(mist_playux_perfect{prot!=\"\"}) by (prot) / (sum(mist_playux_bad) by (prot) + sum(mist_playux_okay) by (prot) + sum(mist_playux_perfect) by (prot))",
     "legendFormat": "{{prot}}"
    }
   ]
  },
  {
   "title": "UX: Flawless playback percentage per quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(mist_playux_perfect{qual!=\"\"}) by (qual) / ((sum(mist_playux_bad) by (qual) + sum(mist_playux_okay) by (qual) + sum(mist_playux_perfect) by (qual)) > 5)",
     "legendFormat": "{{qual}}"
    }
   ]
  },
  {
   "title": "UX: Measurements by protocol",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mist_playux_bad{prot!=\"\"}) by (prot) + sum(mist_playux_okay{prot!=\"\"}) by (prot) + sum(mist_playux_perfect{prot!=\"\"}) by (prot)",
     "legendFormat": "{{prot}}"
    }
   ]
  },
  {
   "title": "UX: Measured streams by quality level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mist_playux_bad) by (qual) + sum(mist_playux_okay) by (qual) + sum(mist_playux_perfect) by (qual)",
     "legendFormat": "{{qual}}"
    }
   ]
  },
  {
   "title": "Geolocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Viewership Los Angeles",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "(sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-LosAngeles\"}) by (geo) / ((sum(mist_playux_bad{geo!=\"\",instance=\"PTV-OrigEdge-LosAngeles\"}) by (geo) + sum(mist_playux_okay{geo!=\"\",instance=\"PTV-OrigEdge-LosAngeles\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-LosAngeles\"}) by (geo))))*100",
     "legendFormat": "Quality"
    },
    {
     "expr": "((sum(mist_playux_bad{geo!=\"\",instance=\"PTV-OrigEdge-LosAngeles\"}) by (geo) + sum(mist_playux_okay{geo!=\"\",instance=\"PTV-OrigEdge-LosAngeles\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-LosAngeles\"}) by (geo)))"
    }
   ]
  },
  {
   "title": "Viewership Dallas",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "expr": "(sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-Dal\"}) by (geo) / ((sum(mist_playux_bad{geo!=\"\",instance=\"PTV-OrigEdge-Dal\"}) by (geo) + sum(mist_playux_okay{geo!=\"\",instance=\"PTV-OrigEdge-Dal\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-Dal\"}) by (geo))))*100",
     "legendFormat": "Quality"
    },
    {
     "expr": "((sum(mist_playux_bad{geo!=\"\",instance=\"PTV-OrigEdge-Dal\"}) by (geo) + sum(mist_playux_okay{geo!=\"\",instance=\"PTV-OrigEdge-Dal\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-Dal\"}) by (geo)))"
    }
   ]
  },
  {
   "title": "Viewership Miami",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "(sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-Miami\"}) by (geo) / ((sum(mist_playux_bad{geo!=\"\",instance=\"PTV-OrigEdge-Miami\"}) by (geo) + sum(mist_playux_okay{geo!=\"\",instance=\"PTV-OrigEdge-Miami\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-Miami\"}) by (geo))))*100",
     "legendFormat": "Quality"
    },
    {
     "expr": "((sum(mist_playux_bad{geo!=\"\",instance=\"PTV-OrigEdge-Miami\"}) by (geo) + sum(mist_playux_okay{geo!=\"\",instance=\"PTV-OrigEdge-Miami\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-Miami\"}) by (geo)))"
    }
   ]
  },
  {
   "title": "Viewership New York",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "expr": "(sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-NewYork\"}) by (geo) / ((sum(mist_playux_bad{geo!=\"\",instance=\"PTV-OrigEdge-NewYork\"}) by (geo) + sum(mist_playux_okay{geo!=\"\",instance=\"PTV-OrigEdge-NewYork\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-NewYork\"}) by (geo))))*100",
     "legendFormat": "Quality"
    },
    {
     "expr": "((sum(mist_playux_bad{geo!=\"\",instance=\"PTV-OrigEdge-NewYork\"}) by (geo) + sum(mist_playux_okay{geo!=\"\",instance=\"PTV-OrigEdge-NewYork\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\",instance=\"PTV-OrigEdge-NewYork\"}) by (geo)))"
    }
   ]
  },
  {
   "title": "Viewership global",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "(sum(mist_playux_perfect{geo!=\"\"}) by (geo) / ((sum(mist_playux_bad{geo!=\"\"}) by (geo) + sum(mist_playux_okay{geo!=\"\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\"}) by (geo))))*100",
     "legendFormat": "Quality"
    },
    {
     "expr": "((sum(mist_playux_bad{geo!=\"\"}) by (geo) + sum(mist_playux_okay{geo!=\"\"}) by (geo) + sum(mist_playux_perfect{geo!=\"\"}) by (geo)))"
    }
   ]
  },
  {
   "title": "Sub-par experience by region",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 41 },
   "targets": [
    {
     "expr": "sum(mist_playux_bad{geo!=\"\"}) by (geo) + sum(mist_playux_okay{geo!=\"\"}) by (geo)"
    }
   ]
  },
  {
   "title": "Troubled streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Viewers with a bad experience, per stream",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "(sum(mist_playux_bad) by (strm) + sum(mist_playux_okay) by (strm)) > ((sum(mist_playux_perfect) by (strm) + sum(mist_playux_bad) by (strm) + sum(mist_playux_okay) by (strm)) / 3) > 3",
     "legendFormat": "{{strm}}"
    }
   ]
  }
 ]
}