{
 "title": "pod-mon.sh",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "treshold", "label": "treshold", "query": "0.9" },
   {
    "name": "region",
    "query": {}
   },
   {
    "name": "catalyst",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(catalyst_node) (avg_over_time(mist_cpu{region=~\"${region:pipe}\", catalyst_node=~\".*${catalyst:pipe}.*\"}[180s])) / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg_cpu_per_core",
   "type": "timeseries",
   "description": "average number of cores used per process. 1.0 -> single CPU core used in 100%",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistController\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistController"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistProcLivepeer\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistProcLivepeer"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistUtilLoad\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistUtilLoad"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistOutWebRTC\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistOutWebRTC"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistInDTSC\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistInDTSC"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistOutDTSC\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistOutDTSC"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistOutFLV\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistOutFLV"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistInFLV\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistInFLV"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistInBuffer\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistInBuffer"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistOutHTTPTS\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistOutHTTPTS"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"catalyst-api\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} catalyst-api"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"catalyst-uploader\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": [\\d\\.]+, \"avg_mem_per_process\": [\\d\\.]+}` | unwrap avg_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} catalyst-uploader"
    }
   ]
  },
  {
   "title": "max_cpu_per_core",
   "type": "timeseries",
   "description": "max number of cores used per process",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistController\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistController"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistProcLivepeer\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>\\d+.\\d+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": \\d+.\\d+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistProcLivepeer"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistUtilLoad\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistUtilLoad"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistOutWebRTC\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistOutWebRTC"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistInDTSC\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistInDTSC"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistOutDTSC\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistOutDTSC"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistOutFLV\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistOutFLV"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistInFLV\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistInFLV"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistInBuffer\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistInBuffer"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"MistOutHTTPTS\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} MistOutHTTPTS"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"catalyst-api\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} catalyst-api"
    },
    {
     "expr": "sum by(pod, process, region) (avg_over_time({region!=\"eu-metrics\", region=~\"${region:pipe}\", app=\"catalyst\", pod=~\"${catalyst:pipe}\"} |= `[pod-mon]` | regexp `{\"process\": \"catalyst-uploader\", \"avg_cpu_per_core\": (?P<avg_cpu_per_core>[\\d\\.]+), \"max_cpu_per_core\": (?P<max_cpu_per_core>[\\d\\.]+), \"avg_mem_per_process\": [\\d\\.]+}` | unwrap max_cpu_per_core [$__auto])) > $treshold",
     "legendFormat": "{{region}}-{{pod}} catalyst-uploader"
    }
   ]
  }
 ]
}