{
 "title": "Referer Analysis",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Referes",
   "type": "timeseries",
   "description": "referer headers",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(\n  {app=\"traefik\", region!=\"eu-metrics\", container=\"prod-traefik\"} \n  | json \n  | __error__!=\"JSONParserErr\"\n  | request_Origin != \"\"\n  | line_format \"{{.request_Origin}}\"[1m]\n)) by (request_Origin) > 100",
     "legendFormat": "{{ request_Origin }}"
    },
    {
     "expr": "sum(count_over_time({app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | referer != \"-\" | line_format \"{{ .referer }}\" | pattern \"<refererScheme>://<refererDomain>/<refererPath>\" | line_format \"{{ .refererDomain }}\"[1m])) by (refererDomain)",
     "legendFormat": "{{ originDomain }}"
    }
   ]
  },
  {
   "title": "Streams by Referer",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(referer, playback_id, upstream) (count_over_time({namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"} != `51eebae3-9b8e-48bc-89ca-5340c4074a48.json` | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | line_format `{{ .url }}` | pattern `/hls/<base>+<playback_id>/` | playback_id != \"\" | upstream =~ `.*(catalyst|livepeer-api).*` [1m]))",
     "legendFormat": "{{ playback_id }} - {{ referer }}"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>`| referer != \"-\" [1m] )) by (userAgent)",
     "legendFormat": "{{ userAgent }}"
    }
   ]
  }
 ]
}