{
 "title": "Replication health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Problems reading stats on node / 5m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |= \"MistUtilLoad\" |= \".json\" != \"Monitoring\"[5m])) by (pod, region)",
     "legendFormat": "{{region}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Problems reading stats from node / 5m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(FromHostname) (count_over_time({app=\"catalyst\"} |= `MistUtilLoad` |= `.json` != `Monitoring` | pattern `<_>://<FromHostname>/<_>` [5m]))",
     "legendFormat": "{{FromHostname}}"
    }
   ]
  },
  {
   "title": "Replication attempts / 5m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |= \"Starting /usr/local/bin/MistInDTSC\"[5m])) by (region)",
     "legendFormat": "Total {{region}}"
    },
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |= \"Starting /usr/local/bin/MistInDTSC\" |= \"MistOutDTSC:\" [5m])) by (region)",
     "legendFormat": "Faulty {{region}}"
    }
   ]
  }
 ]
}