{
 "title": "Replication latency",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(mist_latency,region)"
    }
   },
   {
    "name": "catalyst_node",
    "label": "catalyst node",
    "query": {
     "query": "label_values(mist_latency{region=~\"$region\"},catalyst_node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Edge/origin pairs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(mist_latency{region=~\"${region:pipe}\", catalyst_node=~\"${catalyst_node:pipe}\"}) by (catalyst_node, source)",
     "legendFormat": "{{catalyst_node}} pulling from {{source}}"
    }
   ]
  },
  {
   "title": "Bandwidth usage in % of configured max",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(mist_bw_total{region=~\"${region:pipe}\", catalyst_node=~\"${catalyst_node:pipe}\"}[10s])) by (catalyst_node) / on (catalyst_node) mist_bw_limit{region=~\"${region:pipe}\"} * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System-wide bandwidth usage in % of configured max",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(stat_bw_total{region=~\"${region:pipe}\", catalyst_node=~\"${catalyst_node:pipe}\"}[10s])) by (catalyst_node) / on (catalyst_node) mist_bw_limit{region=~\"${region:pipe}\"} * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency increase per 5s",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(increase(mist_latency{region=~\"${region:pipe}\", catalyst_node=~\"${catalyst_node:pipe}\"}[5s])/1000 < 5 > -5) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  }
 ]
}