{
 "title": "Single-Stream Health",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "manifest_id" }
  ]
 },
 "panels": [
  {
   "title": "Concurrent Streams",
   "type": "stat",
   "description": "Number of concurrent streams across all broadcasters",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Total Playback Requests (viewership)",
   "type": "stat",
   "description": "Across region and mist_instance",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({app=\"traefik\"} |= \"GET /hls/\" | regexp \".+GET /hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\" |= \"$manifest_id\" [$__range])) by (playback_id)"
    }
   ]
  },
  {
   "title": "Requests 2XX vs 4XX vs 5XX",
   "type": "timeseries",
   "description": "Across region and mist_instance",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum (count_over_time({app=\"traefik\"} |= \"GET /hls/\" | regexp \".+GET /hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\" |= \"$manifest_id\" |~ `.*HTTP\\/[12]\\.[01]\" 2[0123][0123]` [$__range])) by (playback_id)",
     "legendFormat": "HTTP 2XX"
    },
    {
     "expr": "sum (count_over_time({app=\"traefik\"} |= \"GET /hls/\" | regexp \".+GET /hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\" |= \"$manifest_id\" |~ `.*HTTP\\/[12]\\.[01]\" 4[0123][0123]` [$__range])) by (playback_id)",
     "legendFormat": "HTTP 4XX"
    },
    {
     "expr": "sum (count_over_time({app=\"traefik\"} |= \"GET /hls/\" | regexp \".+GET /hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\" |= \"$manifest_id\" |~ `.*HTTP\\/[12]\\.[01]\" 5[0123][0123]` [$__range])) by (playback_id)",
     "legendFormat": "HTTP 5XX"
    }
   ]
  },
  {
   "title": "Playback Traefik",
   "type": "timeseries",
   "description": "Across region and mist_instance",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum (count_over_time({app=\"traefik\"} |= \"GET /hls/\" | regexp \".+GET /hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\" |= \"$manifest_id\" [1m])) by (playback_id)"
    }
   ]
  },
  {
   "title": "HTTP push realtime ratio",
   "type": "graph",
   "description": "Percentage of segments transcoded faster than 3x realtime speed, 3x, 1x,  half realtime and more than two time slower than realtime",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_3x{manifest_id=\"$manifest_id\"}))/sum(increase(livepeer_segment_source_emerged_unprocessed_total{manifest_id=\"$manifest_id\"}))",
     "legendFormat": "3x"
    },
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_2x{manifest_id=\"$manifest_id\"}))/sum(increase(livepeer_segment_source_emerged_unprocessed_total{manifest_id=\"$manifest_id\"}))",
     "legendFormat": "2x"
    },
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_1x{manifest_id=\"$manifest_id\"}))/sum(increase(livepeer_segment_source_emerged_unprocessed_total{manifest_id=\"$manifest_id\"}))",
     "legendFormat": "1x"
    },
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_half{manifest_id=\"$manifest_id\"}))/sum(increase(livepeer_segment_source_emerged_unprocessed_total{manifest_id=\"$manifest_id\"}))",
     "legendFormat": "half realtime"
    },
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_slow{manifest_id=\"$manifest_id\"}))/sum(increase(livepeer_segment_source_emerged_unprocessed_total{manifest_id=\"$manifest_id\"}))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Transcode duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Segment/sequence number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livepeer_segment_source_emerged_unprocessed_total{manifest_id=\"$manifest_id\"}"
    }
   ]
  },
  {
   "title": "Orchestrator swap count",
   "type": "stat",
   "description": "Number of orchestrator swaps mid-stream",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livepeer_orchestrator_swaps{manifest_id=\"$manifest_id\"}[1m]"
    }
   ]
  },
  {
   "title": "Orchestrators",
   "type": "piechart",
   "description": "Number of orchestrator swaps mid-stream",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livepeer_upload_time_seconds_count{manifest_id=\"$manifest_id\"}",
     "legendFormat": "{{orchestrator_uri}}"
    }
   ]
  },
  {
   "title": "Multistream Usage (Time)",
   "type": "timeseries",
   "description": "Multistream usage in minutes by stream manifestId",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "increase(mistconnector_multistream_usage_minutes{manifest_id = \"$manifest_id\"} [1d])"
    }
   ]
  },
  {
   "title": "Multistream Usage (Data)",
   "type": "timeseries",
   "description": "Multistream usage in megabytes by stream manifestId",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "increase(mistconnector_multistream_usage_megabytes{manifest_id = \"$manifest_id\"} [1d])"
    }
   ]
  }
 ]
}