{
 "title": "Stream Drop Investigation",
 "time": { "from": "2023-05-11T08:00:54.000Z", "to": "2023-05-11T09:00:53.000Z" },
 "templating": {
  "list": [
   { "name": "playback_id", "query": "dd918sysogpo3wfv" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "mist_sessions{}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\", stream!~\"catalyst_vod.+\", stream=~\".+$playback_id\"}[1m] ) by (region) or on() vector(0), \"stream_id\", \"$1\", \"stream\", \".*\\\\+(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "options": {
    "content": "# mist_session{}\n\nIn this chart, we see the mist_session count for this stream. Seems pretty bad after we deploy!"
   }
  },
  {
   "title": "Websocket requests per minute per IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {app=~\"ingress-nginx\", stream=\"stdout\"}\n        |~ \"json_\" \n        | pattern \"<ip> - -\"\n        [1m]\n    )\n) by (ip) > 500",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "options": {
    "content": "# Websocket Requests\n\nThis panel tracks the number of requests for a `json_stream.js` websocket from the same IP addresses. This should be a small number, but it's huge!"
   }
  },
  {
   "title": "HTTP Requests per minute for playback_id",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"}\n        != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\"\n        | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>`\n        | line_format \"{{ .url }}\"\n        | pattern \"/hls/<base>+<playback_id>/\"\n        | playback_id = \"$playback_id\"\n        [1m]\n    )\n) by (status, playback_id)",
     "legendFormat": "{{ playback_id }} ({{ status }})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "options": {
    "content": "# nginx requests\n\nBut in this chart, we can see that there weren't actually actually very many HTTP requests going out; not many users were actually watching the stream!"
   }
  },
  {
   "title": "nginx unique IPs for playback_id",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum(count_over_time(\n\n        {namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"}\n        != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\"\n        | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>`\n        | line_format \"{{ .url }}\"\n        | pattern \"/hls/<base>+<playback_id>/\"\n        | playback_id = \"$playback_id\"\n        | line_format \"{{ .ip }}\"\n        [1m]\n\n)) by (ip) ^ 0)",
     "legendFormat": "Unique IPs"
    }
   ]
  },
  {
   "title": "nginx outbound bandwidth for playback_id",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(\n\n        {namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"}\n        != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\"\n        | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>`\n        | line_format \"{{ .url }}\"\n        | pattern \"/hls/<base>+<playback_id>/\"\n        | playback_id = \"$playback_id\"\n        | unwrap bytes\n        [1m]\n\n)) * 8 / 60",
     "legendFormat": "{{ playback_id }} ({{ status }})"
    }
   ]
  }
 ]
}