{
 "title": "Studio Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "E2E Streams Test Success Rate (past 12h)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n    sum(count_over_time({region=\"sandbox\", app=~\"base-record-tester-prod-.*\"} |~ \"Test of .+ ended with some err\" | label_format rut=\"{{ Replace .app \\\"record-tester-prod-\\\" \\\"\\\" -1 }}\" [12h]))\n    / \n    sum(count_over_time({region=\"sandbox\", app=~\"base-record-tester-prod-.*\"} |~ \"Starting .+ recordings test stream\" | label_format rut=\"{{ Replace .app \\\"record-tester-prod-\\\" \\\"\\\" -1 }}\" [12h]))\n)"
    }
   ]
  },
  {
   "title": "Success Rate over time",
   "type": "timeseries",
   "description": "It's only not by region because there's no way to coalesce values in LogQL and then there would be a lot of whole in the graph.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1 - (\n    sum(count_over_time({region=\"sandbox\", app=~\"base-record-tester-prod-.*\"} |~ \"Test of .+ ended with some err\" | label_format rut=\"{{ Replace .app \\\"record-tester-prod-\\\" \\\"\\\" -1 }}\" [12h]))\n    / \n    sum(count_over_time({region=\"sandbox\", app=~\"base-record-tester-prod-.*\"} |~ \"Starting .+ recordings test stream\" | label_format rut=\"{{ Replace .app \\\"record-tester-prod-\\\" \\\"\\\" -1 }}\" [12h]))\n)",
     "resolution": 10
    }
   ]
  },
  {
   "title": "New Users Email Validations",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=~\".+-livepeer-api\"} |= \"Email address validation result\" | logfmt | label_format verdict=`{{(fromJson .body).result.verdict}}`, score=`{{(fromJson .body).result.score}}` | label_format body=\"\", app=\"\", job=\"\", pod=\"\", node_name=\"\", region=\"\""
    }
   ]
  },
  {
   "title": "Postgres Query Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_api_pgsql_query_duration_seconds_count{result=\"success\", query!~\"CREATE INDEX.+\"} [3m])) by (region) / sum(increase(livepeer_api_pgsql_query_duration_seconds_count{query!~\"CREATE INDEX.+\"} [3m])) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multistream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total multistream time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mistconnector_multistream_usage_minutes{} [$__range]))"
    }
   ]
  },
  {
   "title": "Total multistream data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mistconnector_multistream_usage_megabytes{} [$__range]))"
    }
   ]
  },
  {
   "title": "Multistream Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum(increase(mistconnector_multistream_usage_minutes{} [1d]))",
     "legendFormat": "Minutes"
    },
    {
     "expr": "sum(increase(mistconnector_multistream_usage_megabytes{} [1d]))",
     "legendFormat": "GiB"
    }
   ]
  }
 ]
}