{
 "title": "Transcode issues Mist",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Transcode timeouts / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"catalyst\"} |= \"MistProcLivepeer\" |= \"timed out after\")[2m])) by (region)/2",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Explanation",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "# Timeouts per minute\nThis measures the amount of attempted-transcoded-segments that are timing out, per region. The region here is the region where the transcode is being requested (e.g. the media server region), **not** the region where the transcoder is."
   }
  },
  {
   "title": "Transcode rejects / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(increase(mist_trigger_count{trigger=\"LIVEPEER_SEGMENT_REJECTED\"}[5m])) by (region)) / 5",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Explanation",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": {
    "content": "# Rejections per minute\nThis measures the amount of attempted-transcoded-segments that are rejected by the transcoder(s), per region.\n\nRejections are segments the transcoder says cannot be transcoded (e.g. invalid, unsupported, etc) and should not be retried."
   }
  },
  {
   "title": "Broadcasts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"incoming\"}[10m])) by (region)",
     "legendFormat": "{{region}} total"
    }
   ]
  },
  {
   "title": "Explanation",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
   "options": {
    "content": "# Context\nThis graph gives the context of how many streams are being processed by the MistServer nodes.\n\nIt shows both the total live streams and the stream tester related live streams.\n\nThe expectation is that broadcasts and failures are correlated. They don't seem to be, though."
   }
  }
 ]
}