{
 "title": "Alerts - Nodes",
 "description": "Alerts for Nodes using prometheus and node_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [
  "alerts",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Alerts Status", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 } },
  { "title": "Alerts Log", "type": "alertlist", "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "Nodes CPU Usage (> 50%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance, region) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\".+:9100\"}[1m])) * 100 * on(instance) group_left(nodename) node_uname_info < 50 ) \n",
     "legendFormat": "{{region}}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "Nodes Memory Usage (> 50%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * on(instance, region) group_left(nodename) node_uname_info > 50\n\n\n",
     "legendFormat": "{{ region }}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "Nodes Disk Usage (> 90%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (region, mountpoint, nodename) (\n    ((100.0 - 100 * ((node_filesystem_avail_bytes[1m] / 1000 / 1000 ) / (node_filesystem_size_bytes[1m]  / 1024 / 1024))) > 90)\n        * on(instance) group_left(nodename) node_uname_info\n    )",
     "legendFormat": "{{region}}-{{nodename}}: {{mountpoint}}"
    }
   ]
  }
 ]
}