{
 "title": "Global Usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Ingest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Streams by Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"}) by (region)"
    }
   ]
  },
  { "title": "Transcoding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Segments Transcoded per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_transcoded_total{node_type=\"orch\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Segments Transcoded per second by region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (region) (rate(livepeer_segment_transcoded_total{node_type=\"orch\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Real-time ratio p95 by broadcaster region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum by (le, region) (rate(livepeer_http_client_segment_transcoded_realtime_ratio_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Real-time ratio p95 by orchestrator region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, sum by (le, region) (rate(livepeer_transcode_score_bucket{node_type=\"orch\"}[$__rate_interval])))"
    }
   ]
  },
  { "title": "Playback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Playback requests per minute per region",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum (count_over_time({app=\"traefik\"} |= \"GET /hls/\" [10m])) by (region) / 10"
    }
   ]
  },
  {
   "title": "Highest Playback Traffic Streams (past 10min)",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum (count_over_time({app=\"traefik\"} |= \"GET /hls/\" \n| regexp \".+GET /hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\" \n| regexp \".+playback-792e3a71a26-(?P<mist_instance>.+)-livepeer-com@kubernetes.+\" [10m])\n) by (playback_id, region, mist_instance) / 10",
     "legendFormat": "{{playback_id}}"
    }
   ]
  },
  { "title": "Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Count of regions with telemetry",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(sum(max_over_time(prometheus_build_info{}[1m])) by (region))",
     "legendFormat": "Regions"
    }
   ]
  },
  {
   "title": "Regions with Telemetry",
   "type": "status-history",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(min_over_time(prometheus_build_info{}[1m])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}