{
 "title": "Kube API Alerts",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{}[15m])>1) by (region)",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas Unavailable",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{}) by (region)"
    }
   ]
  },
  {
   "title": "Pod Restarts by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{}[15m])>1) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Node DiskPressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"} > 0",
     "legendFormat": "{{ region }}-{{ node }}"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"false\"} > 0",
     "legendFormat": "{{ region }}-{{ node }}"
    }
   ]
  },
  {
   "title": "Pods Evicted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_status_reason{reason=\"Evicted\"}==1)) by (region)"
    }
   ]
  },
  {
   "title": "Node PIDPressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"PIDPressure\", status=\"true\"} > 0",
     "legendFormat": "{{ region }}-{{ node }}"
    }
   ]
  },
  {
   "title": "Node MemoryPressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"} > 0",
     "legendFormat": "{{ region }}-{{ node }}"
    }
   ]
  }
 ]
}