{
 "title": "Loki Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unrecoverable Orchestrators",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\".*prod.+orchestrator.*\"} |= \"Unrecoverable state\" [150s])) by (region, pod)",
     "legendFormat": "{{region}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Excessive MistProcLivepeer restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (manifest_id, region, pod) (count_over_time(\n  {app=\"mist\", container=\"mist\"} \n  |= \"Starting process: /usr/bin/MistProcLivepeer\" \n  | pattern `<_>\"source\":\"video<_>+<manifest_id>\"` [4m]\n)) > 1",
     "legendFormat": "{{manifest_id}} @ {{region}}-{{pod}}"
    }
   ]
  },
  {
   "title": "RabbitMQ broken client credentials",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"prod-.+\",app!=\"prod-livepeer-monitoring\"} |= \"username or password not allowed\" [1m])) by (app, region)",
     "legendFormat": "{{region}}-{{app}}"
    }
   ]
  },
  { "title": "Tasks/VOD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Task Queue Accumulation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "count by (region) (count by (region, taskId) (\n  count_over_time({app=\"prod-livepeer-api\",region!=\"sin\"} |= \"publishing message to task.trigger\" | pattern \"<_>task.trigger.<type>.<taskId> on exchange<_>\" [15m])\n))\n- \ncount by (region) (count by (region, taskId) (\n  count_over_time({app=\"prod-task-runner\"} |= \"Starting task\" | logfmt | label_format taskId=id [15m])\n))"
    }
   ]
  },
  {
   "title": "Poison Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "count by (id, region) (count_over_time({app=\"prod-task-runner\"} |= \"Starting task\" | logfmt [2h])) > 2"
    }
   ]
  },
  {
   "title": "Assets with considerable start_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max_over_time({app=\"prod-task-runner\"} |= \"Probed video file\" | logfmt | maxStreamStartTime > 0.1 | unwrap maxStreamStartTime [10m]) by (assetId)"
    }
   ]
  },
  {
   "title": "Task failures by region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"prod-task-runner\"} |= \"Task handler processed task\" | logfmt | error != \"%!q(<nil>)\" [2m])) by (region)"
    }
   ]
  },
  {
   "title": "Recent unknown VOD task errors",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "{app=\"prod-task-runner\"} |= \"Task handler processed task\" | logfmt | error != \"%!q(<nil>)\" \n| error !~ \".+unexpected EOF\" \n| error !~ \".+stream error: stream ID.+\" \n| error !~ \"error processing ffprobe output: unsupported .+\"\n| error !~ \"(?s).*context deadline exceeded.*\" \n| error !~ \".+mp4io: parse error:.+TagSizeInvalid.+\"\n| error != \"error probing file: error running ffprobe [] exit status 1\"\n| error !~ \"bad status code from import request:.+\"\n| line_format \"{{ .error }}\""
    }
   ]
  }
 ]
}