{
 "title": "Mist Global Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total viewers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"})"
    }
   ]
  },
  {
   "title": "Active streamers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"incoming\"})"
    }
   ]
  },
  {
   "title": "Protocol usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mist_outputs{catalyst_node=~\".*studio\",output!=\"HTTP\"}) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Viewers per server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mist_sessions_total{sessType=\"viewers\",catalyst_node=~\".*studio\"}) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Broadcasts in the last 30 days",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{catalyst_node=~\".*studio\",sessType=~\"incoming\"}[30d]))"
    }
   ]
  },
  {
   "title": "Viewtime in the last 30 days",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"}[30d]))*720"
    }
   ]
  },
  {
   "title": "Broadcast time in the last 30 days",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"incoming\"}[30d]))*720"
    }
   ]
  },
  {
   "title": "Bandwidth (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate((sum(mist_bw_total{catalyst_node=~\".*studio\"}) by (catalyst_node))[10m])*8)",
     "legendFormat": "External"
    },
    {
     "expr": "sum(rate((sum(mist_bw_other{catalyst_node=~\".*studio\"}) by (catalyst_node))[10m])*8)",
     "legendFormat": "Internal"
    }
   ]
  },
  {
   "title": "Incoming streams per server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mist_sessions_total{sessType=\"incoming\",catalyst_node=~\".*studio\"}) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Viewers / Broadcasters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"})",
     "legendFormat": "Viewers"
    },
    {
     "expr": "sum(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"incoming\"})",
     "legendFormat": "Broadcasters"
    }
   ]
  },
  {
   "title": "Bandwidth (per server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mist_bw_total{catalyst_node=~\".*studio\"}[10m])*8) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    },
    {
     "expr": "sum(rate(mist_bw_other{catalyst_node=~\".*studio\"}[10m])*8) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}} internal"
    }
   ]
  },
  {
   "title": "CPU per server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_cpu{catalyst_node=~\".*studio\"}[180s])/10) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Memory per server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(mist_shm_used{catalyst_node=~\".*studio\"} / mist_shm_total{catalyst_node=~\".*studio\"} * 100 > mist_mem_used{catalyst_node=~\".*studio\"} / mist_mem_total{catalyst_node=~\".*studio\"} * 100) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}} SHM"
    },
    {
     "expr": "sum(mist_mem_used{catalyst_node=~\".*studio\"} / mist_mem_total{catalyst_node=~\".*studio\"} * 100 > mist_shm_used{catalyst_node=~\".*studio\"} / mist_shm_total{catalyst_node=~\".*studio\"} * 100) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}} RAM"
    }
   ]
  },
  {
   "title": "Log rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mist_logs{catalyst_node=~\".*studio\"}[5m])) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Reconnects per 10 minutes per user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mist_sessions_count{catalyst_node=~\".*studio\",sessType=\"viewers\"}[30m])*600 / mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"}) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Viewers per broadcaster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"}) / sum(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"incoming\"})",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Edge bandwidth per user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mist_bw_total{catalyst_node=~\".*studio\",direction=\"up\"}[1m])*8 / on (catalyst_node) mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"}) by (catalyst_node)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Origin sessions per day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{catalyst_node=~\".*studio\",sessType=\"incoming\"}[1d])) by (catalyst_node, sessType)",
     "legendFormat": "{{catalyst_node}}: {{sessType}}"
    }
   ]
  },
  {
   "title": "Average per week",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"}[7d]))",
     "legendFormat": "Viewers"
    },
    {
     "expr": "sum(avg_over_time(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"incoming\"}[7d]))",
     "legendFormat": "Broadcasters"
    }
   ]
  },
  {
   "title": "Trigger failure rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_fails{catalyst_node=~\".*studio\"}[15m])) by (catalyst_node, trigger) / on(trigger, catalyst_node) sum(rate(mist_trigger_count{catalyst_node=~\".*studio\"}[15m])) by (catalyst_node, trigger)",
     "legendFormat": "{{catalyst_node}} {{trigger}}"
    }
   ]
  },
  {
   "title": "Trigger runtime",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_time{catalyst_node=~\".*studio\"}[15m])) by (catalyst_node, trigger) / on(trigger, catalyst_node) sum(rate(mist_trigger_count{catalyst_node=~\".*studio\"}[15m])) by (catalyst_node, trigger)",
     "legendFormat": "{{catalyst_node}} {{trigger}}"
    }
   ]
  },
  {
   "title": "Trigger rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_count{catalyst_node=~\".*studio\"}[10m])) by (catalyst_node,trigger)",
     "legendFormat": "{{catalyst_node}} {{trigger}}"
    }
   ]
  },
  {
   "title": "Total viewers per protocol",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mist_outputs{catalyst_node=~\".*studio\"}) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Total incoming sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mist_sessions_count{catalyst_node=~\".*studio\",sessType=~\"incoming\"}) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Views per hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{catalyst_node=~\".*studio\",sessType=\"viewers\"}[1h])) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Views per day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{catalyst_node=~\".*studio\",sessType=\"viewers\"}[1d]))by(catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    },
    {
     "expr": "sum(increase(mist_sessions_count{catalyst_node=~\".*studio\",sessType=\"viewers\"}[1d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU per 100 viewers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_cpu{catalyst_node=~\".*studio\"}[1d])*10) by (catalyst_node) / on(catalyst_node) sum(avg_over_time(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"}[1d])) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Peak viewers in 24h period",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(sum(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"viewers\"})[1d])",
     "legendFormat": "Viewers"
    }
   ]
  },
  {
   "title": "Peak broadcasts in 24h period",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(sum(mist_sessions_total{catalyst_node=~\".*studio\",sessType=\"incoming\"})[1d])",
     "legendFormat": "Viewers"
    }
   ]
  },
  {
   "title": "Bandwidth used per month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mist_bw_total{catalyst_node=~\".*studio\"}[30d])) by (catalyst_node)",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  }
 ]
}