{
 "title": "node-alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ram per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=~\"kubernetes-service-endpoints\"} * 100) / node_memory_MemTotal_bytes{job=~\"kubernetes-service-endpoints\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU load (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load5{job=~\"kubernetes-service-endpoints\"}) by (instance) /\ncount(count(node_cpu_seconds_total{job=~\"kubernetes-service-endpoints\"}) by (cpu, instance)) by (instance) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "FS Disk loads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=~\"kubernetes-service-endpoints\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=~\"kubernetes-service-endpoints\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}