{
 "title": "Video Product",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "New Users Email Validations",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\".+-livepeer-api\"} |= \"Email address validation result\" | logfmt | label_format verdict=`{{(fromJson .body).result.verdict}}`, score=`{{(fromJson .body).result.score}}` | label_format body=\"\", app=\"\", job=\"\", pod=\"\", node_name=\"\", region=\"\""
    }
   ]
  },
  { "title": "Multistream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total multistream time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mistconnector_multistream_usage_minutes{} [$__range]))"
    }
   ]
  },
  {
   "title": "Total multistream data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mistconnector_multistream_usage_megabytes{} [$__range]))"
    }
   ]
  },
  {
   "title": "Multistream Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "m", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mistconnector_multistream_usage_minutes{} [1d]))",
     "legendFormat": "Minutes"
    },
    {
     "expr": "sum(increase(mistconnector_multistream_usage_megabytes{} [1d]))",
     "legendFormat": "GiB"
    }
   ]
  }
 ]
}