{
 "title": "Mist",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "stream", "query": "mist_bw" }
  ]
 },
 "panels": [
  { "title": "stream $stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "stream" },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(mist_bw{stream=~\"$stream\"}) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "viewcount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mist_viewcount{stream=~\"$stream\"}",
     "legendFormat": "viewcount"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    { "expr": "mist_mem_used / mist_mem_total" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "targets": [
    { "expr": "mist_cpu" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(mist_bw_total) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "unique streams count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(mist_sessions{sessType=\"incoming\"}) by (stream))",
     "legendFormat": "streams"
    }
   ]
  },
  {
   "title": "Mist CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mist_cpu", "legendFormat": "{{livepeer_node_type}}" }
   ]
  }
 ]
}