apiVersion: 1
deleteDatasources: []
datasources:
  - access: proxy
    isDefault: true
    name: Prometheus
    type: prometheus
    url: $LP_PROMETHEUS_ENDPOINT
  - access: proxy
    isDefault: false
    name: Loki
    type: loki
    url: $LP_LOKI_URL