{
 "title": "K8s Livepeer Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Overload, streams",
   "type": "stat",
   "description": "Number of current streams on across Broadcasters minus maximum sessions across Orchestrators",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"}) - sum(livepeer_max_sessions_total{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Concurrent Streams",
   "type": "stat",
   "description": "Number of concurrent streams across all broadcasters",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Broadcasters Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{livepeer_node_type=~\"^.*broadcaster.*$\"})"
    }
   ]
  },
  {
   "title": "Emerged segments",
   "type": "stat",
   "description": "Total number of segments emerged from segmenter.",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_emerged_unprocessed_total)"
    }
   ]
  },
  {
   "title": "Transcoded Segments",
   "type": "stat",
   "description": "Total number of transcoded segments.",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcoded_unprocessed_total)"
    }
   ]
  },
  {
   "title": "Orchestrators Utilisation",
   "type": "gauge",
   "description": "Percentage of streams running on Orchestrators to maxSessions of Orchestrator",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"}) / sum(livepeer_max_sessions_total{node_type=\"orch\"})*100"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Orchestrators Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{livepeer_node_type=~\"^.*orchestrator.*$\"})"
    }
   ]
  },
  {
   "title": "Broadcasters Increase in Current Sessions (1m)",
   "type": "graph",
   "description": "shows the currently total active sessions for each Broadcaster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_current_sessions_total{node_type=\"bctr\"}[1m])) by (node_id)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "ORCHs Total Increase in Current Sessions (1m)",
   "type": "graph",
   "description": "shows the currently total active sessions for each orchestrator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "sessions" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_current_sessions_total{node_type=\"orch\"}[1m])) by (node_id)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "True Success rate (1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_transcoded_all_appeared_total[1m])) by (node_id) / sum(rate(livepeer_segment_source_emerged_total[1m])) by (node_id)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Average Overall Latency (B -> OT -> B)",
   "type": "graph",
   "description": "Latency is calculated on Broadcaster, from time source segment goes out from segmenter till transcoded segment gets inserted into manifest.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_transcode_overall_latency_seconds_sum{node_type=\"bctr\"}[1m])) by (node_id) / sum(rate(livepeer_transcode_overall_latency_seconds_count{node_type=\"bctr\"}[1m])) by (node_id)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "O Average Transcode Time",
   "type": "graph",
   "description": "Orchestrator Average Transcode Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{node_id}}/{{profiles}}"
    }
   ]
  },
  {
   "title": "Overall Transcode Latency, percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "O Transcode time, percentiles",
   "type": "graph",
   "description": "Transcode times, measured at transcoder.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "B Success Rate (Client, 1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "livepeer_success_rate{node_type=\"bctr\"} and max_over_time(livepeer_current_sessions_total{node_type=\"bctr\"}[1m]) > 0",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Upload Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_upload_failed_total[1m])) by (error_code)",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Transcode Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_transcode_failed_total[1m])) by (error_code, node_id)",
     "legendFormat": "{{node_id}} {{error_code}}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_retried[1m])",
     "legendFormat": "{{instance}} - try={{try}}"
    }
   ]
  },
  {
   "title": "Discovery Errors ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(livepeer_discovery_errors_total[30s])",
     "legendFormat": "{{instance}} {{error_code}}"
    }
   ]
  },
  {
   "title": "Upload Errors Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_upload_failed_total) by (node_id, error_code)",
     "legendFormat": "{{node_id}} {{error_code}}"
    }
   ]
  },
  {
   "title": "Transcode Errors Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcode_failed_total) by (node_id, error_code)",
     "legendFormat": "{{node_id}} {{error_code}}"
    }
   ]
  },
  {
   "title": "Not Uploaded Segments, rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_appeared_total[30s])) - sum(increase(livepeer_segment_source_uploaded_total[30s]))\n"
    },
    {}
   ]
  },
  {
   "title": "Orchestrators Sessions Distribution",
   "type": "graph",
   "description": "Number of sessions per orchestrator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "livepeer_current_sessions_total{node_type=\"orch\"}"
    }
   ]
  },
  {
   "title": "Segments Number",
   "type": "graph",
   "description": "Total number of segments emerged from segmenter and total number of segments transcoded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_emerged_unprocessed_total)",
     "legendFormat": "emerged"
    },
    {
     "expr": "sum(livepeer_segment_transcoded_unprocessed_total)",
     "legendFormat": "transcoded"
    }
   ]
  },
  {
   "title": "Broascasters Sessions Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "livepeer_current_sessions_total{node_type=\"bctr\"}"
    }
   ]
  }
 ]
}