apiVersion: 1
deleteDatasources: []
datasources:
  - access: proxy
    isDefault: true
    name: Prometheus
    type: prometheus
    url: $LP_PROMETHEUS_ENDPOINT
  - access: proxy
    isDefault: false
    name: Loki
    type: loki
    url: $LP_LOKI_URL
    basicAuth: true
    basicAuthUser: $LP_LOKI_BASIC_AUTH_USER
    secureJsonData:
      basicAuthPassword: $LP_LOKI_BASIC_AUTH_PASS
  - access: proxy
    isDefault: false
    name: Loki-report
    type: loki
    url: $LP_LOKI_REPORT_URL
    basicAuth: true
    basicAuthUser: $LP_LOKI_BASIC_AUTH_USER
    secureJsonData:
      basicAuthPassword: $LP_LOKI_BASIC_AUTH_PASS
