{
 "title": "Regression Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Exception While Decoding",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(region) (rate({container=~\"ai-gateway|live-video-to-video_comfyui_.*\"} != `Sending input frame` != `message=frame_type=Video` != `message=Output image received` |~ `Exception while decoding` [$__auto]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Process Join Error",
   "type": "timeseries",
   "description": "Monitors for any ComfyUI pipeline cleanups that have process join errors.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(region) (rate({container=~\"ai-gateway|live-video-to-video_comfyui_.*\"} != `Sending input frame` != `message=frame_type=Video` != `message=Output image received` |~ `Process join error:` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fail to Terminate or Killing",
   "type": "timeseries",
   "description": "Monitors for any ComfyUI pipeline cleanups that have process failing in killing or terminate errors.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(region) (rate({container=~\"ai-gateway|live-video-to-video_comfyui_.*\"} != `Sending input frame` != `message=frame_type=Video` != `message=Output image received` |~ `Failed to terminate process, killing` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fail to kill process",
   "type": "timeseries",
   "description": "Monitors for any ComfyUI pipeline cleanups that have process failing to kill errors.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(region) (rate({container=~\"ai-gateway|live-video-to-video_comfyui_.*\"} != `Sending input frame` != `message=frame_type=Video` != `message=Output image received` |~ `Failed to kill process` [$__auto]))"
    }
   ]
  },
  {
   "title": "FPS Distribution Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(\n  (\n    avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name)\n  )\n  and\n  (\n    count(avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name, container)) by (node_name) == 1\n  )\n)",
     "legendFormat": "fps_1_stream"
    },
    {
     "direction": "backward",
     "expr": "avg(\n  (\n    avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name)\n  )\n  and\n  (\n    count(avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name, container)) by (node_name) == 2\n  )\n)",
     "legendFormat": "fps_2_streams"
    },
    {
     "direction": "backward",
     "expr": "avg(\n  (\n    avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name)\n  )\n  and\n  (\n    count(avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name, container)) by (node_name) == 3\n  )\n)",
     "legendFormat": "fps_3_streams"
    }
   ]
  },
  {
   "title": "Orchestrator Selection Time Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time(\n  {app=~\".*gateway.*\"} \n  |~ `Received GetOrchInfo RPC Response`\n  | pattern `<_> latency=<latency>` \n  | unwrap duration(latency) [1m]\n) by (app)",
     "legendFormat": "avg"
    },
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.80,\n  {app=~\".*gateway.*\"} \n  |~ `Received GetOrchInfo RPC Response`\n  | pattern `<_> latency=<latency>` \n  | unwrap duration(latency) [1m]\n) by (app)",
     "legendFormat": "p80"
    }
   ]
  },
  {
   "title": "Decoder Crash",
   "type": "timeseries",
   "description": "This chart shows the occurrence rate of the decoder crash.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container=~\"live-video-to-video.*\"} |= \"Error in decode_av, maximum retries reached\" [1m])",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}