{
 "title": "LP Debugger",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Broadcasters Number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{livepeer_node_type=~\"^.*broadcaster.*$\"})"
    }
   ]
  },
  {
   "title": "Orchestrators Number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{livepeer_node_type=~\"^.*orchestrator.*$\"})"
    }
   ]
  },
  {
   "title": "Concurrent Streams",
   "type": "singlestat",
   "description": "Number of concurrent streams across all broadcasters",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Emerged vs Transcoded (rate 1m)",
   "type": "graph",
   "description": "Rate of segments emerged from segmenter vs Rate of segments transcoded over 1 minute period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_source_emerged_unprocessed_total[1m]))",
     "legendFormat": "emerged"
    },
    {
     "expr": "sum(rate(livepeer_segment_transcoded_unprocessed_total[1m]))",
     "legendFormat": "transcoded"
    }
   ]
  },
  {
   "title": "% of Segments transcoded",
   "type": "graph",
   "description": "rate of transcoded segments / rate of emerged segments",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_transcoded_unprocessed_total[1m])) by (node_id) / sum(rate(livepeer_segment_source_emerged_unprocessed_total[1m])) by (node_id)",
     "legendFormat": "% transcoded {{node_id}}"
    }
   ]
  },
  {
   "title": "B Success Rate (1m avg)",
   "type": "graph",
   "description": "Broadcaster's success rate over 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "livepeer_success_rate{node_type=\"bctr\"} and max_over_time(livepeer_current_sessions_total{node_type=\"bctr\"}[1m]) > 0",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Average B Latency",
   "type": "graph",
   "description": "Latency is calculated on Broadcaster, from time source segment goes out from segmenter till transcoded segment gets inserted into manifest.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_transcode_overall_latency_seconds_sum{node_type=\"bctr\"}[1m])) by (node_id) / sum(rate(livepeer_transcode_overall_latency_seconds_count{node_type=\"bctr\"}[1m])) by (node_id)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Upload Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_upload_failed_total[1m])) by (node_id, error_code)",
     "legendFormat": "{{node_id}} - {{error_code}}"
    }
   ]
  },
  {
   "title": "Transcode Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_transcode_failed_total[1m])) by (error_code, node_id)",
     "legendFormat": "{{node_id}}/{{error_code}}"
    }
   ]
  },
  {
   "title": "Discovery Errors ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(livepeer_discovery_errors_total[30s])",
     "legendFormat": "{{node_id}} {{error_code}}"
    }
   ]
  },
  {
   "title": "O Average Transcode Time",
   "type": "graph",
   "description": "Orchestrator Average Transcode Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{node_id}}/{{profiles}}"
    }
   ]
  }
 ]
}