{
 "title": "Broadcaster details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "broadcaster",
    "query": "livepeer_success_rate{node_type=\"bctr\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Concurrent Streams",
   "type": "singlestat",
   "description": "Number of concurrent streams across all broadcasters",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_id=\"$broadcaster\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Orchestrators Number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{livepeer_node_type=~\"^.*orchestrator.*$\"})"
    }
   ]
  },
  {
   "title": "Emerged segments",
   "type": "singlestat",
   "description": "Total number of segments emerged from segmenter.",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_emerged_unprocessed_total{node_id=\"$broadcaster\"})"
    }
   ]
  },
  {
   "title": "Transcoded Segments",
   "type": "singlestat",
   "description": "Total number of transcoded segments.",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcoded_unprocessed_total{node_id=\"$broadcaster\"})"
    }
   ]
  },
  {
   "title": "Overall Transcode Latency, percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_overall_latency_seconds_bucket{node_id=\"$broadcaster\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_overall_latency_seconds_bucket{node_id=\"$broadcaster\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_overall_latency_seconds_bucket{node_id=\"$broadcaster\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_overall_latency_seconds_bucket{node_id=\"$broadcaster\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Average Overall Latency (B -> OT -> B)",
   "type": "graph",
   "description": "Latency is calculated on Broadcaster, from time source segment goes out from segmenter till transcoded segment gets inserted into manifest.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_transcode_overall_latency_seconds_sum{node_id=\"$broadcaster\"}[1m])) by (node_id) / sum(rate(livepeer_transcode_overall_latency_seconds_count{node_id=\"$broadcaster\"}[1m])) by (node_id)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "B Success Rate (Client, 1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "livepeer_success_rate{node_id=\"$broadcaster\"} and max_over_time(livepeer_current_sessions_total{node_id=\"$broadcaster\"}[1m]) > 0",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "O Average Transcode Time",
   "type": "graph",
   "description": "Orchestrator Average Transcode Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{node_id}}/{{profiles}}"
    }
   ]
  },
  {
   "title": "Upload Errors (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_upload_failed_total{node_id=\"$broadcaster\"}[1m])) by (error_code)",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Upload Errors Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_upload_failed_total{node_id=\"$broadcaster\"}) by (error_code)",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Transcode Errors (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_transcode_failed_total{node_id=\"$broadcaster\"}[1m])) by (error_code)",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Transcode Errors Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcode_failed_total{node_id=\"$broadcaster\"}) by (error_code)",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Segments Number",
   "type": "graph",
   "description": "Total number of segments emerged from segmenter and total number of segments transcoded",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_emerged_unprocessed_total{node_id=\"$broadcaster\"})",
     "legendFormat": "emerged"
    },
    {
     "expr": "sum(livepeer_segment_transcoded_unprocessed_total{node_id=\"$broadcaster\"})",
     "legendFormat": "transcoded"
    }
   ]
  },
  {
   "title": "Not Uploaded Segments, rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_appeared_total{node_id=\"$broadcaster\"}[30s])) - sum(increase(livepeer_segment_source_uploaded_total{node_id=\"$broadcaster\"}[30s]))\n",
     "legendFormat": "rate of segments appeared - uploaded (30s)"
    },
    {}
   ]
  }
 ]
}