{
 "title": "Ai Ingest Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "stream_id",
    "label": "Select Stream ID",
    "query": "SELECT stream_id FROM network_events.stream_status\nwhere $__timeFilter(timestamp_ts)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "gauge",
     "description": "This indicates the current temperature of the GPU.  It assess the thermal performance and health of the GPU, as elevated temperatures can indicate potential overheating issues",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{region}} - {{Hostname}}" }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "gauge",
     "description": "This measures the power consumption of the GPU. This metric helps to understand the energy efficiency and operational costs associated with the GPU usage",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{region}} - {{Hostname}}" }
     ]
    },
    {
     "title": "GPU Power Violation",
     "type": "stat",
     "description": "This indicates a power violation event related to the GPU. A power violation occurs when the GPU exceeds its specified power limit or threshold, which can lead to throttling, instability, or potential hardware damage.\n\nPower Limit Exceeded: -\nIf the GPU exceeds its configured power limit, it may trigger a power violation. This can happen during periods of high workload when the GPU is drawing more power than allowed.\n\nThrottling: -\nWhen a power violation occurs, the GPU may automatically throttle its performance to reduce power consumption. This can lead to decreased performance and increased latency in applications relying on the GPU.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "DCGM_FI_DEV_POWER_VIOLATION", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GPU Memory Usage",
     "type": "timeseries",
     "description": "This indicates the amount of framebuffer memory currently being utilized by the GPU. Framebuffer memory is critical for storing textures, frame data, and other graphical information that the GPU needs to render images and perform computations.\n\nIt gives trend of memory usage over time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "{{region}}" }
     ]
    },
    {
     "title": "# GPUs Online",
     "type": "stat",
     "description": "This shows the number of GPUs online. i.e that are actively running and reporting power metrics\n\n",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(DCGM_FI_DEV_POWER_USAGE{gpu!=\"\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "# GPUs Available",
     "type": "stat",
     "description": "This indicates the availability of the GPU i.e check whether basic requirements needed for it to run is satisfied",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(DCGM_FI_DEV_POWER_USAGE) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Capacity",
     "type": "stat",
     "description": "This measure the total capacity of the GPU",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(DCGM_FI_DEV_FB_FREE + DCGM_FI_DEV_FB_USED)",
       "legendFormat": "{{region}} - {{Hostname}}"
      }
     ]
    },
    {
     "title": "GPU Encode/Decode Utilization",
     "type": "timeseries",
     "description": "This indicates the utilization of the GPU's Encoding/Decoding resources\n\nIf the encoding/decoding utilization is consistently near 100%, it may indicate that the GPU is being overutilized.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "rate(DCGM_FI_DEV_ENC_UTIL[1m])", "legendFormat": "{{region}} - Encode" },
      { "expr": "rate(DCGM_FI_DEV_DEC_UTIL[1m])", "legendFormat": "{{region}} - Decode" }
     ]
    },
    {
     "title": "GPU Free Memory not in use",
     "type": "bargauge",
     "description": "This display the current amount of free framebuffer memory available on the GPU",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "DCGM_FI_DEV_FB_FREE", "legendFormat": "{{region}} - {{Hostname}}" }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "description": "This indicates the utilization of the GPU itself. It reflects the percentage of time the GPU is actively processing tasks compared to the total time it is available.\n\nA high utilization percentage (close to 100%) indicates that the GPU is being heavily used.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{region}}" }
     ]
    }
   ]
  },
  {
   "title": "CPU Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "This chart visualizes the CPU usage percentage for nodes in specified regions, with a threshold set at 80%.\n\nA CPU usage percentage greater than 80% indicates that the system is heavily loaded, with most of the CPU resources actively in use.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (1 - (sum(irate(node_cpu_seconds_total{region=~\".*-ai$\", mode=\"idle\", instance=~\".+:9100\"}[1m])) by (region) / sum(irate(node_cpu_seconds_total{instance=~\".+:9100\"}[1m])) by (region)))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Memory Usage (> 50%)",
     "type": "timeseries",
     "description": "This chart visualizes the CPU usage percentage for nodes in specified regions, with a threshold set at 50%.\n\nA CPU usage percentage greater than 50% indicates that more than half of the CPU resources are actively being utilized. ",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (1 - (sum(irate(node_cpu_seconds_total{region=~\".*-ai$\", mode=\"idle\", instance=~\".+:9100\"}[1m])) by (region) / sum(irate(node_cpu_seconds_total{instance=~\".+:9100\"}[1m])) by (region)))",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Ingest Disk I/O Per Minute",
     "type": "timeseries",
     "description": "This shows the disk I/O performance for various regions, specifically focusing on the rates of data being written to and read from disk.\n\nNormal Operation:-\nWhen the disk write and read rates are within expected ranges based on usage over time , the system is functioning normally. You should see stable lines on the graph, indicating consistent disk I/O performance.\n\nHigh Disk Write/Read Rates:- If the lines show significantly high values, it may indicate heavy disk usage. This could be due data ingestion processes. \n\nSudden spikes or drops in disk I/O can indicate issues that need further investigation of the node",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{region=~\".*-ai$\"}[1m])) by (region) / 1000000",
       "legendFormat": "{{region}} - Disk Write"
      },
      {
       "expr": "sum(rate(node_disk_read_bytes_total{region=~\".*-ai$\"}[1m])) by (region) / 1000000",
       "legendFormat": "{{region}} - Disk Read"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "description": "This  indicates how much of the total disk capacity is being utilized.\n\nA higher percentage indicates that a significant portion of the disk space is in use, which may suggest that the filesystem is nearing capacity.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", region=~\".*-ai$\"} - node_filesystem_avail_bytes{mountpoint=\"/\", region=~\".*-ai$\"}) / node_filesystem_size_bytes{mountpoint=\"/\", region=~\".*-ai$\"} * 100",
       "legendFormat": "{{region}}"
      }
     ]
    }
   ]
  },
  { "title": "Stream Ingest Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Online Streams",
   "type": "stat",
   "description": "This chart displays the current count of online streams\n\nMetric: The metric being tracked is the number of streams that are currently in the 'ONLINE' state. This indicates that these streams are actively receiving data and functioning as expected.\n\nTime Frame: The count is based on streams that have had activity within the last 30 seconds. This ensures that the data reflects the most recent status of the streams.\n\nThe data is sourced from the network_events.stream_status table, which contains the current state and last input time for each stream.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS online_count\r\nFROM network_events.stream_status\r\nWHERE state = 'ONLINE' AND\r\n      last_input_time_ts >= now() - INTERVAL 30 SECOND;"
    }
   ]
  },
  {
   "title": "Stream Error Logs",
   "type": "table",
   "description": "This chart displays the most recent events related to errors and restarts within the streaming system.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    stream_id, \r\n    timestamp_ts, \r\n    event_type, \r\n    message, \r\n    restart_count, \r\n    gateway,\r\n    type, \r\n    capability, \r\n    pipeline, \r\n    pipeline_id, \r\n    params, \r\n    orchestrator_address, \r\n    orchestrator_url\r\nFROM \r\n    network_events.stream_events\r\nWHERE \r\n    sub_type IN ('error', 'restart')\r\n    AND $__timeFilter(timestamp_ts)\r\nORDER BY \r\n    timestamp_ts DESC\r\nLIMIT 100;\r\n"
    }
   ]
  },
  {
   "title": "Stream Health Status",
   "type": "timeseries",
   "description": "This chart visualizes the counts of 'restart' and 'error' events occurring in a stream over time\n\nRestart Count: This metric indicates the number of times a 'restart' event occurred within the specified minute. A higher count may suggest frequent restarts, which could indicate potential issues with service stability or performance.\n\nError Count: This metric represents the number of 'error' events logged during the same minute. An increase in error counts may signal underlying problems that require investigation, such as system failures or misconfigurations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfMinute(se.timestamp_ts) AS timestamp_ts,\r\n    ss.state,\r\n    sum(se.restart_count) AS Restart_Count,\r\n    countIf(se.sub_type = 'error') AS Error_Count       \r\nFROM \r\n    network_events.stream_events AS se\r\nJOIN \r\n    network_events.stream_status AS ss ON se.stream_id = ss.stream_id\r\nWHERE \r\n    se.stream_id IN (SELECT DISTINCT stream_id FROM network_events.stream_events)\r\n    AND $__timeFilter(se.timestamp_ts)\r\nGROUP BY \r\n    timestamp_ts, ss.state\r\nORDER BY \r\n    timestamp_ts ASC;\r\n"
    }
   ]
  },
  {
   "title": "Stream Status [Error/Restart Count with Stream ID]",
   "type": "barchart",
   "description": "This visualizes the count of'restart' and 'error' events for the latest 15 distinct streams in the network_events.stream_events dataset.\nIt identifies streams with the number of restarts and errors.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    stream_id, \r\n    countIf(event_type = 'restart') AS restart_count,\r\n    countIf(event_type = 'error') AS error_count\r\nFROM (\r\n    SELECT DISTINCT stream_id\r\n    FROM network_events.stream_events\r\n    WHERE event_type IN ('restart', 'error')\r\n    ORDER BY timestamp_ts DESC\r\n    LIMIT 15\r\n) AS latest_streams\r\nJOIN network_events.stream_events USING (stream_id)\r\nGROUP BY stream_id\r\nORDER BY stream_id ASC;\r\n"
    }
   ]
  }
 ]
}