{
 "title": "Ai Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stream_id",
    "label": "Select Stream ID",
    "query": "SELECT DISTINCT stream_id FROM network_events.stream_events where $__timeFilter(timestamp_ts)"
   },
   {
    "name": "stream_key",
    "label": "Stream Key",
    "query": "SELECT DISTINCT Streams.stream_key\nFROM network_events.stream_events\nLEFT JOIN network_events.streams AS Streams ON stream_events.stream_id = Streams.id\nWHERE $__timeFilter(timestamp_ts);"
   },
   {
    "name": "region",
    "label": "Ingest Region",
    "query": {
     "query": "label_values(node_cpu_seconds_total{region=~\".*-ai$\"}, region)"
    }
   },
   {
    "name": "Hostname",
    "label": "Inference Region",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_USED, Hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stream Monitoring - Ingest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online Streams",
   "type": "stat",
   "description": "This chart displays the current count of online streams\n\nMetric: The metric being tracked is the number of streams that are currently in the 'ONLINE' state. This indicates that these streams are actively receiving data and functioning as expected.\n\nTime Frame: The count is based on streams that have had activity within the last 10 seconds. This ensures that the data reflects the most recent status of the streams.\n\nThe data is sourced from the network_events.stream_status table, which contains the current state and last input time for each stream.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS online_count\r\nFROM network_events.stream_status\r\nWHERE state = 'ONLINE' AND\r\n      last_input_time_ts >= now() - INTERVAL 10 SECOND;"
    }
   ]
  },
  {
   "title": "Total Stream Counts",
   "type": "timeseries",
   "description": "Provides information on the number of AI livestreams currently live in staging.",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{gpu!=\"\"} > 0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Streams W/Errors",
   "type": "stat",
   "description": "This chart indicates the percentage of streams that experience errors.\n\nGreen = < 10% of streams with errors\n\nYellow = > 10% of streams with errors\n\nRed = > 20% of streams with errors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(CASE WHEN last_error_time_ts IS NOT NULL THEN 1 ELSE 0 END) / COUNT(*) * 100 AS `Error Percentage`\r\nFROM (\r\n  SELECT\r\n    stream_id,\r\n    MAX(last_error_time_ts) AS last_error_time_ts\r\n  FROM\r\n    network_events.stream_status\r\n  WHERE\r\n    $__timeFilter(timestamp_ts)\r\n  GROUP BY\r\n    stream_id\r\n) AS stream_errors"
    }
   ]
  },
  {
   "title": "Start Up Time",
   "type": "barchart",
   "description": "The chart show the average number of seconds spent for each of the event.\n- gateway_recieve",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH all_subtypes AS (\n    SELECT 'app_receive_first_segment' AS sub_type\n    UNION ALL SELECT 'gateway_recieve_stream_request' AS sub_type\n    UNION ALL SELECT 'gateway_send_first_ingest_segment' AS sub_type\n    UNION ALL SELECT 'runner_receive_first_ingest_segment' AS sub_type\n)\nSELECT\n  `all_subtypes`.`sub_type` AS `sub_type`,\n  COALESCE(`toFloat64`(AVG(`filtered_data`.`time_diff_ms`)) / 1000.0, 0) AS `Average of Time Seconds`\nFROM\n  all_subtypes\nLEFT JOIN\n  (\n    SELECT\n      `network_events`.`stream_trace`.`sub_type` AS `sub_type`,\n      `network_events`.`stream_trace`.`time_diff_ms` AS `time_diff_ms`\n    FROM\n      `network_events`.`stream_trace`\n    WHERE\n      (`network_events`.`stream_trace`.`sub_type` = 'app_receive_first_segment'\n      OR `network_events`.`stream_trace`.`sub_type` = 'gateway_recieve_stream_request'\n      OR `network_events`.`stream_trace`.`sub_type` = 'gateway_send_first_ingest_segment'\n      OR `network_events`.`stream_trace`.`sub_type` = 'runner_receive_first_ingest_segment')\n      AND `network_events`.`stream_trace`.`timestamp_ts` >= toDateTime($__from/1000)\n      AND `network_events`.`stream_trace`.`timestamp_ts` <= toDateTime($__to/1000)\n  ) AS `filtered_data` ON `all_subtypes`.`sub_type` = `filtered_data`.`sub_type`\nGROUP BY\n  `all_subtypes`.`sub_type`\nORDER BY\n  `all_subtypes`.`sub_type` ASC"
    }
   ]
  },
  {
   "title": "Start Up Time with Stream Id",
   "type": "table",
   "description": "The chart shows the sub-type with stream Ids of the time spent for each of the event.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  `source`.`timestamp` AS `timestamp`,\n  `source`.`event_timestamp_ts` AS `event_timestamp_ts`,\n  `source`.`stream_id` AS `stream_id`,\n  `source`.`sub_type` AS `sub_type`,\n  `source`.`time_diff_ms` AS `time_diff_ms`,\n  `source`.`request_id` AS `request_id`,\n  `source`.`Pipelines__name` AS `Pipelines__name`,\n  `source`.`pipeline_id` AS `pipeline_id`,\n  `source`.`event_timestamp` AS `event_timestamp`,\n  `source`.`last_timestamp` AS `last_timestamp`,\n  `source`.`event_order` AS `event_order`,\n  `source`.`orch_address` AS `orch_address`,\n  `source`.`orch_url` AS `orch_url`,\n  `source`.`Pipelines__key` AS `Pipelines__key`,\n  `source`.`Pipelines__author` AS `Pipelines__author`\nFROM\n  (\n    SELECT\n      `network_events`.`stream_trace`.`timestamp` AS `timestamp`,\n      `network_events`.`stream_trace`.`event_timestamp_ts` AS `event_timestamp_ts`,\n      `network_events`.`stream_trace`.`sub_type` AS `sub_type`,\n      `network_events`.`stream_trace`.`stream_id` AS `stream_id`,\n      `network_events`.`stream_trace`.`request_id` AS `request_id`,\n      `network_events`.`stream_trace`.`pipeline_id` AS `pipeline_id`,\n      `network_events`.`stream_trace`.`event_timestamp` AS `event_timestamp`,\n      `network_events`.`stream_trace`.`last_timestamp` AS `last_timestamp`,\n      `network_events`.`stream_trace`.`event_order` AS `event_order`,\n      `network_events`.`stream_trace`.`orch_address` AS `orch_address`,\n      `network_events`.`stream_trace`.`orch_url` AS `orch_url`,\n      `network_events`.`stream_trace`.`time_diff_ms` AS `time_diff_ms`,\n      `Pipelines`.`key` AS `Pipelines__key`,\n      `Pipelines`.`name` AS `Pipelines__name`,\n      `Pipelines`.`author` AS `Pipelines__author`\n    FROM\n      `network_events`.`stream_trace`\n     \nLEFT JOIN `network_events`.`pipelines` AS `Pipelines` ON `network_events`.`stream_trace`.`pipeline_id` = `Pipelines`.`id`\n  ) AS `source`\nWHERE\n  (\n    `source`.`sub_type` = 'gateway_send_first_ingest_segment'\n    OR `source`.`sub_type` = 'runner_receive_first_ingest_segment'\n    OR `source`.`sub_type` = 'gateway_recieve_stream_request'\n  )\n \n   AND (\n    `source`.`event_timestamp_ts` >= toDateTime($__from/1000)\n  )\n  AND (\n    `source`.`event_timestamp_ts` < toDateTime($__to/1000)\n  )\n  AND (`source`.`Pipelines__key` = 'comfyui')\n  AND `source`.`stream_id` IN (${stream_id:singlequote})"
    }
   ]
  },
  {
   "title": "Stream Error/Restart Count by Stream ID",
   "type": "table",
   "description": "This visualizes the count of'restart' and 'error' events for the latest 15 distinct streams in the network_events.stream_events dataset.\nIt identifies streams with the number of restarts and errors.",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT stream_id, \r\ncountIf(event_type = 'restart') AS restart_count, \r\ncountIf(event_type = 'error') AS error_count\r\nFROM \r\n    network_events.stream_events\r\nWHERE \r\n    sub_type IN ('error', 'restart')\r\n    AND stream_id IN (${stream_id:singlequote})\r\n    AND $__timeFilter(timestamp_ts)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Stream Logs",
   "type": "table",
   "description": "This chart displays the most recent events related to errors and restarts within the streaming system.",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    stream_id, \r\n    timestamp_ts,\r\n    restart_count,\r\n    event_type, \r\n    message, \r\n    gateway,\r\n    type, \r\n    capability, \r\n    pipeline, \r\n    pipeline_id, \r\n    params, \r\n    orchestrator_address, \r\n    orchestrator_url\r\nFROM \r\n    network_events.stream_events\r\nWHERE \r\n    sub_type IN ('error', 'restart')\r\n    AND stream_id IN (${stream_id:singlequote})\r\n    AND $__timeFilter(timestamp_ts)\r\n    AND pipeline = 'comfyui'\r\nORDER BY \r\n    timestamp_ts DESC\r\nLIMIT 100;\r\n"
    }
   ]
  },
  {
   "title": "Gateway Stream Logs",
   "type": "logs",
   "description": "Log information of all the streams of selected streams during the gateway process.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\".*-livepeer-ai-gateway\"} |~ \"${stream_id}\""
    }
   ]
  },
  {
   "title": "MediaMTX Logs",
   "type": "logs",
   "description": "Log information of all the streams of selected streams during the MediaMTX process.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"mediamtx\"} |~ \"${stream_key}\""
    }
   ]
  },
  {
   "title": "CPU Monitoring - Ingest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "This chart visualizes the CPU usage percentage for nodes in specified regions, with a threshold set at 80%.\n\nA CPU usage percentage greater than 80% indicates that the system is heavily loaded, with most of the CPU resources actively in use.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (instance, region) (irate(node_cpu_seconds_total{region=~\"${region:regex}\", mode=\"idle\", instance=~\".+:9100\"}[1m])) * 100 * on(instance) group_left(nodename) node_uname_info) ",
       "legendFormat": "{{region}}-{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Memory Usage (> 50%)",
     "type": "timeseries",
     "description": "This chart visualizes the CPU usage percentage for nodes in specified regions, with a threshold set at 50%.\n\nA CPU usage percentage greater than 50% indicates that more than half of the CPU resources are actively being utilized. ",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (1 - (node_memory_MemAvailable_bytes{region=~\"${region:regex}\"} / node_memory_MemTotal_bytes{region=~\"${region:regex}\"}))",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "description": "This  indicates how much of the total disk capacity is being utilized.\n\nA higher percentage indicates that a significant portion of the disk space is in use, which may suggest that the filesystem is nearing capacity.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", region=~\"${region:regex}\"} - node_filesystem_avail_bytes{mountpoint=\"/\", region=~\"${region:regex}\"}) / node_filesystem_size_bytes{mountpoint=\"/\", region=~\"${region:regex}\"} * 100",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Ingest Disk I/O Per Minute",
     "type": "timeseries",
     "description": "This shows the disk I/O performance for various regions, specifically focusing on the rates of data being written to and read from disk.\n\nNormal Operation:-\nWhen the disk write and read rates are within expected ranges based on usage over time , the system is functioning normally. You should see stable lines on the graph, indicating consistent disk I/O performance.\n\nHigh Disk Write/Read Rates:- If the lines show significantly high values, it may indicate heavy disk usage. This could be due data ingestion processes. \n\nSudden spikes or drops in disk I/O can indicate issues that need further investigation of the node",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{region=~\"${region:regex}\"}[1m])) by (region) / 1000000",
       "legendFormat": "{{region}} - Disk Write"
      },
      {
       "expr": "sum(rate(node_disk_read_bytes_total{region=~\"${region:regex}\"}[1m])) by (region) / 1000000",
       "legendFormat": "{{region}} - Disk Read"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Monitoring - Inference",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPUs",
     "type": "stat",
     "description": "This shows the number of GPUs online. i.e that are actively running and reporting power metrics\n\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(livepeer_ai_current_live_pipelines[$__rate_interval]))",
       "legendFormat": "GPUs in Use"
      },
      {
       "expr": "count(DCGM_FI_DEV_POWER_USAGE{gpu!=\"\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Usage",
     "type": "timeseries",
     "description": "Monitoring VRAM usage helps ensure that tasks aren't running out of memory, which can cause significant performance degradation or crashes. It's important to know if the GPU's memory is sufficient for the tasks or if you need to scale up.",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg((DCGM_FI_DEV_FB_USED / (DCGM_FI_DEV_FB_USED{Hostname=~\"${Hostname:regex}\"} + DCGM_FI_DEV_FB_FREE))* 100 ) by (Hostname, region)",
       "legendFormat": "{{region}} - {{Hostname}}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "description": "This is crucial to understand how effectively the GPU is being used. High utilization is good for performance but could indicate potential bottlenecks if consistently at 100%. Low utilization might suggest that the GPU is oversized for the task or there's an inefficiency in workload distribution.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${Hostname:regex}\"}) by (Hostname, region)",
       "legendFormat": "{{region}}{{Hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inference Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "FPS Output",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  `network_events`.`stream_status`.`stream_id` AS `stream_id`,\r\n  AVG(`network_events`.`stream_status`.`output_fps`) AS `avg`\r\nFROM\r\n  `network_events`.`stream_status`\r\nWHERE\r\n  (\r\n    `network_events`.`stream_status`.`timestamp_ts` >= `toStartOfHour`((`now64`(9, 'UTC') + INTERVAL -24 hour))\r\n  )\r\n  AND (\r\n    `network_events`.`stream_status`.`timestamp_ts` < `toStartOfHour`((`now64`(9, 'UTC') + INTERVAL 1 hour))\r\n  )\r\n  AND (\r\n    `network_events`.`stream_status`.`pipeline` = 'comfyui'\r\n  )\r\n  AND (\r\n    `network_events`.`stream_status`.`stream_id` IN (${stream_id:singlequote})\r\n  )\r\nGROUP BY\r\n  `network_events`.`stream_status`.`stream_id`\r\nORDER BY\r\n  `avg` ASC;"
      }
     ]
    },
    {
     "title": "Error Count by Type",
     "type": "table",
     "description": "This table displays the number of errors for each type that is being reported.\n\nGreen = below 20 errors\nYellow = 20 - 50 errors\nRed = > 50 errors\n",
     "gridPos": { "h": 9, "w": 8, "x": 6, "y": 58 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  `source`.`stream_id` AS `stream_id`,\r\n  `source`.`short_message` AS `short_message`,\r\n  COUNT(*) AS `count`\r\nFROM\r\n  (\r\n    SELECT\r\n      `network_events`.`stream_events`.`sub_type` AS `sub_type`,\r\n      `network_events`.`stream_events`.`timestamp_ts` AS `timestamp_ts`,\r\n      `network_events`.`stream_events`.`message` AS `message`,\r\n      `network_events`.`stream_events`.`stream_id` AS `stream_id`,\r\n      `substring`(\r\n        `toString`(`network_events`.`stream_events`.`message`),\r\n        1,\r\n        70\r\n      ) AS `short_message`\r\n    FROM\r\n      `network_events`.`stream_events`\r\n    WHERE\r\n      `network_events`.`stream_events`.`sub_type` = 'error'\r\n      AND $__timeFilter(timestamp_ts)\r\n      AND `network_events`.`stream_events`.`stream_id` IN (${stream_id:sqlstring})\r\n      AND pipeline = 'comfyui'\r\n  ) AS `source`\r\nWHERE\r\n  `source`.`short_message` != ''\r\nGROUP BY\r\n  `source`.`short_message`,\r\n  `source`.`stream_id`\r\nORDER BY\r\n  count DESC;"
      }
     ]
    },
    {
     "title": "Error count by type",
     "type": "barchart",
     "description": "This chart displays the distinct types of stream errors that occurs most frequently, along with their corresponding counts.\n\n0-5 counts: Needs Minor Attention\n\n4-9 counts: Needs Medium Attention\n\n10 or more counts: Needs Urgent Attention",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  `source`.`short_message` AS `short_message`,\r\n  COUNT(*) AS `count`\r\nFROM\r\n  (\r\n    SELECT\r\n      `network_events`.`stream_events`.`sub_type` AS `sub_type`,\r\n      `network_events`.`stream_events`.`timestamp_ts` AS `timestamp_ts`,\r\n      `network_events`.`stream_events`.`message` AS `message`,\r\n      `substring`(\r\n        `toString`(`network_events`.`stream_events`.`message`),\r\n        1,\r\n        70\r\n      ) AS `short_message`\r\n    FROM\r\n      `network_events`.`stream_events`\r\n    WHERE\r\n      `network_events`.`stream_events`.`sub_type` = 'error'\r\n      AND $__timeFilter(timestamp_ts)\r\n      AND pipeline = 'comfyui'\r\n  ) AS `source`\r\nWHERE\r\n  `source`.`short_message` != ''\r\nGROUP BY\r\n  `source`.`short_message`\r\nORDER BY\r\n  count DESC;"
      }
     ]
    },
    {
     "title": "Inference  Logs",
     "type": "table",
     "description": "This chart displays the most recent events related to errors in the inference process.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "rawSql": "SELECT stream_id, timestamp_ts, event_type, pipeline, pipeline_id, message, gateway, type, capability, params, orchestrator_address, orchestrator_url\nFROM network_events.stream_events\nWHERE sub_type IN ('error', 'restart')\nAND stream_id IN (${stream_id:singlequote})\nAND $__timeFilter(timestamp_ts)\nAND pipeline = 'comfyui'\nORDER BY timestamp_ts DESC LIMIT 100;"
      }
     ]
    },
    {
     "title": "Inference Stream Logs",
     "type": "logs",
     "description": "Log information of all the streams of selected streams during the inference process. Using {container=\"live-video-to-video_comfyui_8900\"}",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container=\"live-video-to-video_comfyui_8900\"} |~ \"${stream_id}\""
      }
     ]
    },
    {
     "title": "Stream's Pipeline Data",
     "type": "table",
     "description": "This table contains information on the stream and the pipeline it is using.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "rawSql": "SELECT\n    stream_status.stream_id,\n    timestamp_ts,\n    Streams.id AS `Streams__id`,\n    Streams.pipeline_id AS `Streams__pipeline_id`,\n    Streams.output_playback_id AS `Streams__output_playback_id`,\n    Streams.author AS `Streams__author`,\n    Streams.stream_key AS `Streams__stream_key`,\n    Streams.output_stream_url AS `Streams__output_stream_url`,\n    Streams.created_at AS `Streams__created_at`,\n    Streams.pipeline_params AS `Streams__pipeline_params`,\n    Streams.from_playground AS `Streams__from_playground`,\n    Streams.gateway_host AS `Streams__gateway_host`,\n    Pipelines.id AS `Pipelines__id`,\n    Pipelines.name AS `Pipelines__name`,\n    Pipelines.version AS `Pipelines__version`,\n    Pipelines.description AS `Pipelines__description`,\n    Pipelines.author AS `Pipelines__author`,\n    Pipelines.type AS `Pipelines__type`,\n    Pipelines.created_at AS `Pipelines__created_at`,\n    Pipelines.updated_at AS `Pipelines__updated_at`\nFROM network_events.stream_status\n    LEFT JOIN network_events.streams AS Streams ON stream_status.stream_id = Streams.id\n    LEFT JOIN network_events.pipelines AS Pipelines ON stream_status.pipeline_id = Pipelines.id\n    LEFT JOIN network_events.users AS `Users - Author` ON Pipelines.author = `Users - Author`.id\nWHERE $__timeFilter(timestamp_ts) \nAND stream_status.stream_id IN (${stream_id:singlequote})\nAND pipeline = 'comfyui'\nORDER BY timestamp_ts ASC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "description": "This measures the power consumption of the GPU. This metric helps to understand the energy efficiency and operational costs associated with the GPU usage\n\n450W :- This is the maximum power that the GPU can draw\n\n315W :- This is the average consumption of the GPU when running a job\n\n19 W :- This is the amount of power the GPU consumes when it is not actively being used",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_POWER_USAGE) by (region,Hostname)",
       "legendFormat": "{{region}} - {{Hostname}}"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "description": "This indicates the current temperature of the GPU.  It assess the thermal performance and health of the GPU, as elevated temperatures can indicate potential overheating issues\n\nIdle Temperature 30°C - 50°C \n\nLoad Temperature 70°C - 85°C \n\nMaximum Safe Temperature 90°C - 100°C \n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_TEMP) by (region, Hostname)",
       "legendFormat": "{{region}} - {{Hostname}}"
      }
     ]
    },
    {
     "title": "SM Clock Speed",
     "type": "timeseries",
     "description": "2520 MHz (Boost Clock Speed):\nThis is the maximum clock speed that the GPU can achieve under optimal conditions, known as the boost clock speed. It represents the peak performance capability of the RTX 4090 when the GPU is under heavy load and has adequate cooling and power supply. Monitoring this value helps us understand the upper limits of the GPU's performance during demanding tasks.\n\n2235 MHz (Base Clock Speed):\nThis is the minimum clock speed at which the GPU operates under normal conditions. The base clock speed indicates the performance level the GPU should maintain during standard workloads. If the SM clock speed consistently operates at or near this value, it is functioning as expected. Monitoring this value helps ensure that the GPU is performing adequately during typical usage scenarios.\n\n2000 MHz (Threshold for Concern):\nThis is the threshold we have set to identify potential performance issues. If the SM clock speed drops below 2000 MHz during demanding tasks, it may indicate that the GPU is experiencing problems such as thermal throttling (overheating), power limitations, or other issues that could affect performance. Monitoring for values below this threshold allows us to take proactive measures to investigate and resolve any underlying issues before they impact the overall performance of the GPU.\n\nNote: The mean value on the chart should also be taking a close look at. Drop below 2000 MHz during demanding tasks may indicate issues such as thermal throttling, power limitations, or driver problems",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_SM_CLOCK) by (region, Hostname)",
       "legendFormat": "{{region}} - {{Hostname}}"
      }
     ]
    },
    {
     "title": "GPU Encode/Decode Utilization",
     "type": "timeseries",
     "description": "This indicates the utilization of the GPU's Encoding/Decoding resources\n\nIf the encoding/decoding utilization is consistently near 100%, it may indicate that the GPU is being overutilized.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "rate(DCGM_FI_DEV_ENC_UTIL[1m])", "legendFormat": "{{region}} - Encode" },
      { "expr": "rate(DCGM_FI_DEV_DEC_UTIL[1m])", "legendFormat": "{{region}} - Decode" }
     ]
    },
    {
     "title": "GPU Free Memory not in use",
     "type": "bargauge",
     "description": "This displays the current amount of free framebuffer memory available on the GPU.\n\nGreen = < 50%\nYellow = > 50%\nRed = > 80%",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "DCGM_FI_DEV_FB_FREE", "legendFormat": "{{region}} - {{Hostname}}" }
     ]
    },
    {
     "title": "GPU Max Capacity",
     "type": "bargauge",
     "description": "This measures the total capacity of the GPU",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(DCGM_FI_DEV_FB_FREE + DCGM_FI_DEV_FB_USED)",
       "legendFormat": "{{region}} - {{Hostname}}"
      }
     ]
    },
    {
     "title": "Error count by type Per hour",
     "type": "barchart",
     "description": "This chart displays the distinct types of stream errors that occur, along with their corresponding counts within a 1-hour period:\n\n0-3 counts: Needs Minor Attention\n\n4-9 counts: Needs Medium Attention\n\n10 or more counts: Needs Urgent Attention",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 138 },
     "targets": [
      {
       "rawSql": "SELECT\r\n    `toStartOfHour`(`toTimeZone`(`source`.`timestamp_ts`, 'UTC')) AS `timestamp_ts`,\r\n    `source`.`short_message` AS `short_message`,\r\n    COUNT(*) AS `count`\r\nFROM (\r\n    SELECT\r\n        `network_events`.`stream_events`.`sub_type` AS `sub_type`,\r\n        `network_events`.`stream_events`.`timestamp_ts` AS `timestamp_ts`,\r\n        `network_events`.`stream_events`.`message` AS `message`,\r\n        `substring`(`toString`(`network_events`.`stream_events`.`message`), 1, 70) AS `short_message`\r\n    FROM\r\n        `network_events`.`stream_events`\r\n    WHERE\r\n        `network_events`.`stream_events`.`sub_type` = 'error'\r\n) AS `source`\r\nWHERE\r\n    `source`.`short_message` != ''\r\nGROUP BY\r\n    `toStartOfHour`(`toTimeZone`(`source`.`timestamp_ts`, 'UTC')),\r\n    `source`.`short_message`\r\nHAVING\r\n    COUNT(*) >= 5  -- Filter for counts of 5 or more\r\nORDER BY\r\n    `toStartOfHour`(`toTimeZone`(`source`.`timestamp_ts`, 'UTC')) DESC,\r\n    `source`.`short_message` DESC\r\nLIMIT 20;\r\n"
      }
     ]
    },
    {
     "title": "Stream Health Status",
     "type": "timeseries",
     "description": "This chart visualizes the counts of 'restart' and 'error' events occurring in a stream over time\n\nRestart Count: This metric indicates the number of times a 'restart' event occurred within the specified minute. A higher count may suggest frequent restarts, which could indicate potential issues with service stability or performance.\n\nError Count: This metric represents the number of 'error' events logged during the same minute. An increase in error counts may signal underlying problems that require investigation, such as system failures or misconfigurations.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \r\n    toStartOfMinute(se.timestamp_ts) AS timestamp_ts,\r\n    ss.state,\r\n    sum(se.restart_count) AS Restart_Count,\r\n    countIf(se.sub_type = 'error') AS Error_Count       \r\nFROM \r\n    network_events.stream_events AS se\r\nJOIN \r\n    network_events.stream_status AS ss ON se.stream_id = ss.stream_id\r\nWHERE \r\n    se.stream_id IN (SELECT DISTINCT stream_id FROM network_events.stream_events)\r\n    AND $__timeFilter(se.timestamp_ts)\r\nGROUP BY \r\n    timestamp_ts, ss.state\r\nORDER BY \r\n    timestamp_ts ASC;\r\n"
      }
     ]
    },
    {
     "title": "FPS Output",
     "type": "barchart",
     "description": "FPS(Frame Per Seconds) \n\nAVG Output < 10 :- Needs investigation\n\nAVG Output between 10 -15 :-  Needs to be monitored closely\n\nAVG Output equals to or greater than 15 :- Good Health",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  `network_events`.`stream_status`.`stream_id` AS `stream_id`,\r\n  AVG(`network_events`.`stream_status`.`output_fps`) AS `avg`\r\nFROM\r\n  `network_events`.`stream_status`\r\nWHERE\r\n  (\r\n    `network_events`.`stream_status`.`timestamp_ts` >= `toStartOfHour`((`now64`(9, 'UTC') + INTERVAL -24 hour))\r\n  )\r\n  AND (\r\n    `network_events`.`stream_status`.`timestamp_ts` < `toStartOfHour`((`now64`(9, 'UTC') + INTERVAL 1 hour))\r\n  )\r\n  AND (\r\n    `network_events`.`stream_status`.`pipeline` = 'comfyui'\r\n  )\r\nGROUP BY\r\n  `network_events`.`stream_status`.`stream_id`\r\nHAVING\r\n  AVG(`network_events`.`stream_status`.`output_fps`) < 10\r\nORDER BY\r\n  `avg` ASC,\r\n  `network_events`.`stream_status`.`stream_id` ASC\r\nLIMIT 60;\r\n"
      }
     ]
    }
   ]
  }
 ]
}