{
 "title": "AI Overview (Livestream)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "All Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\".*-livepeer-ai-gateway\"} != \"Polling blocks\""
    }
   ]
  },
  {
   "title": "MediaMTX unsupported codec",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"mediamtx\"} |~ `the stream doesn't contain any supported codec|closed: codec`"
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Stream Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_live_attempt[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(normalized_error_code) (label_replace(label_replace(increase(livepeer_ai_request_errors{pipeline=~\"live-.*\"}[$__rate_interval]), \"normalized_error_code\", \"no orchestrators available\", \"error_code\", \"no orchestrators available.*\"), \"normalized_error_code\", \"$1\", \"error_code\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_request_errors{pipeline=~\"live-.*\"}[$__rate_interval])) / sum(increase(livepeer_ai_live_attempt[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "First segment delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(orchestrator_uri) (increase(livepeer_ai_first_segment_delay_ms_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Orchestrators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Orchestrator Capacity by Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{job=\"orchestrator\"}) by (livepeerversion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-Use Orchestrators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (livepeer_ai_current_live_pipelines)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Capacity Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(pipeline, model_name) (increase(livepeer_ai_request_errors{error_code=~\"no orchestrators available.*\", pipeline=~\"live-.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}