{
 "title": "Alerts - Nodes",
 "description": "Alerts for Nodes using prometheus and node_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [
  "alerts",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Nodes CPU Usage (> 50%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance, region) (irate(node_cpu_seconds_total{region != \"eu-metrics\", mode=\"idle\", instance=~\".+:9100\"}[1m])) * 100 * on(instance) group_left(nodename) node_uname_info) \n",
     "legendFormat": "{{region}}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "Nodes Memory Usage (> 50%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * on(instance, region) group_left(nodename) node_uname_info > 50\n\n\n",
     "legendFormat": "{{ region }}-{{ nodename }}"
    }
   ]
  },
  {
   "title": "Nodes Disk Usage (> 90%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (region, mountpoint, nodename) (\n    ((100.0 - 100 * ((node_filesystem_avail_bytes[1m] / 1000 / 1000 ) / (node_filesystem_size_bytes{mountpoint != \"/var/mnt/core-dump-handler/cores\"}[1m]  / 1024 / 1024))) > 90)\n        * on(instance) group_left(nodename) node_uname_info\n    )",
     "legendFormat": "{{region}}-{{nodename}}: {{mountpoint}}"
    }
   ]
  }
 ]
}