{
 "title": "App Versions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Catalyst", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Catalyst API (Standalone)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(version,pod) (version{app=\"catalyst-api\",app_kubernetes_io_name=\"catalyst-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalyst API (Catalyst Live)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by(version,pod) (version{app=\"catalyst-api\",catalyst=\"true\", region!=\"sin-staging\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalyst API (Catalyst VOD)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(version,pod) (version{app=\"catalyst-api\",catalyst=\"true\", region=\"sin-staging\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task runner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (version) (livepeer_task_runner_version{livepeer_live_app=~\".+-task-runner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MistServer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(version{app=\"MistServer\", pod!=\"canary-catalyst-0\"}) by (version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Livepeer Studio API",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (version) (version{app=\"studio-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "go-livepeer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "go-livepeer (Catalyst Broadcasters)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{catalyst=\"true\", pod != \"canary-catalyst-0\"}) by (livepeerversion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-livepeer (Non-Recording Broadcasters)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{catalyst!=\"true\", node_type=\"bctr\", livepeer_node_type!=\"staging-livepeer-recording\", livepeer_node_type!=\"staging-livepeer-ai-gateway\"}) by (livepeerversion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go-livepeer (Recording Broadcasters)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{catalyst!=\"true\", node_type=\"bctr\", livepeer_node_type=~\".+-livepeer-recording\"}) by (livepeerversion)",
     "legendFormat": "{{ livepeerversion }}"
    }
   ]
  },
  {
   "title": "go-livepeer (AI Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{catalyst!=\"true\", node_type=\"bctr\", livepeer_node_type=~\".+-livepeer-ai-gateway\"}) by (livepeerversion)",
     "legendFormat": "{{ livepeerversion }}"
    }
   ]
  },
  {
   "title": "go-livepeer (Orchestrator)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(livepeer_versions{node_type=\"orch\"}) by (livepeerversion)",
     "legendFormat": "{{ livepeerversion }}"
    }
   ]
  }
 ]
}