{
 "title": "Catalyst Multi-Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "exclude", "label": "Exclude streams:", "query": ".+-test" }
  ]
 },
 "panels": [
  {
   "title": "Current Viewers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Current Streams",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"incoming\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Nodes Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mist_cpu{catalyst=\"true\"})"
    }
   ]
  },
  {
   "title": "Viewers by Stream",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\", stream!~\"catalyst_vod.+\"}[1m] ) by (stream) or on() vector(0), \"stream_id\", \"$1\", \"stream\", \".*\\\\+(.*)\")",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Current Streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"incoming\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Total Viewers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\"})"
    }
   ]
  },
  {
   "title": "Viewers by Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!~\"$exclude\", stream!~\"$exclude\"}) by (region)",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Viewers by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\"}[1m] ) by (catalyst_node) ",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Key duration mismatch; disconnecting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"catalyst\"} |~ \"FAIL: onFail\" |~ \"Key duration mismatch; disconnecting\" | pattern \"<_> '<_>+<playback_id>': Key duration mismatch; disconnecting <ip> to recover\"[30m])) by (playback_id)",
     "legendFormat": "{{ playback_id }}"
    }
   ]
  },
  {
   "title": "VoD Segments Transcoded",
   "type": "timeseries",
   "description": "vod_transcoded_segments",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(catalyst_node) (increase(vod_transcoded_segments[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"Could not retrieve\" replications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"Could not retrieve\" | pattern \"<_> https://<host>/\"[5m]))",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "sum(count_over_time({app=\"ingress-nginx\", namespace=\"default\", stream=\"stderr\"} != \"sent data after final chunk\" |~ \"[error]\" | pattern `<_> upstream: \"<protocol>://<ip>:<port>/<code>.<ext>\", host: \"<upstreamHost>:<upstreamPort>\"` | port = \"4242\" | ext = \"json\"[1m])) ",
     "legendFormat": "Retrieval Errors"
    }
   ]
  },
  {
   "title": "Streams by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"incoming\", stream!=\"000reallylongnonexistenstreamnamethatreallyshouldntexist000\", stream!~\"$exclude\"}[1m] ) by (catalyst_node) ",
     "legendFormat": "{{ stream }}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "count(mist_cpu{catalyst=\"true\"}) ",
     "legendFormat": "{{ catalyst_node }}"
    }
   ]
  },
  {
   "title": "Node Count (by node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "count(mist_cpu{catalyst=\"true\"}) by (catalyst_node) or on() vector(0)",
     "legendFormat": "{{ catalyst_node }}"
    }
   ]
  },
  {
   "title": "\"Could not retrieve\" replications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"Could not retrieve\" | pattern \"<_> https://<host>/\"[5m])) by (host)",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "sum(count_over_time({app=\"ingress-nginx\", namespace=\"default\", stream=\"stderr\"} != \"sent data after final chunk\" |~ \"[error]\" | pattern `<_> upstream: \"<protocol>://<ip>:<port>/<code>.<ext>\", host: \"<upstreamHost>:<upstreamPort>\"` | port = \"4242\" | ext = \"json\"[1m])) by (upstreamHost)",
     "legendFormat": "{{ upstreamHost }}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<originUrl>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | originUrl != \"-\" | line_format \"{{ .originUrl }}\" | pattern \"<originScheme>://<originDomain>/<originPath>\" | line_format \"{{ .originDomain }}\"[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Packet Loss detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"catalyst\"} |~ \"Packet loss detected\" | pattern \"<_> MistOutTSSRT:<playback_id> \"[1m])) by (playback_id)",
     "legendFormat": "{{ playback_id }}"
    },
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"catalyst\"} |~ \"Packet loss detected\" | pattern \"<_> MistOutTSSRT:<playback_id> \"[1m]))",
     "legendFormat": "{{ playback_id }}"
    }
   ]
  },
  {
   "title": "Gated HLS Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"not allowed\"[1m])) by (region)",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Shutting down on Serf client failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"Shutting down on Serf client failure\"[1m])) by (region, pod)",
     "legendFormat": "{{ region }}-{{ pod }}"
    }
   ]
  },
  {
   "title": "Global configuration options not ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\", namespace=\"default\"} |~ \"Global configuration options not ready\"[1m])) by (region, pod)",
     "legendFormat": "{{ region }}-{{ pod }}"
    }
   ]
  },
  {
   "title": "videorec with no audio selection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum(count_over_time(\n  {app=\"catalyst\", namespace=\"default\"}\n  |~ \"MistProcLivepeer\"\n  |~ \"videorec\"\n  |~ \"Adding 1 tracks\"\n  | pattern \"<_> MistProcLivepeer:videorec+<playbackId> <_> MEDIUM: Adding 1 tracks\"[1m]\n)) by (playbackId)"
    }
   ]
  }
 ]
}