{
 "title": "CDN redirects",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "requests redirected to CDN (by playbackID)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(playbackID) (increase(cdn_redirect_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 0 },
   "options": {
    "content": "Number of `/hls/.....m3u8` requests that were redirected to the external CDN (Bunny)."
   }
  },
  {
   "title": "webRTC requests redirected to HLS (per playbackId)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(playbackID) (increase(cdn_redirect_webrtc_406[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 8 },
   "options": {
    "content": "Number of `/webrtc/...` requests that were rejected with HTTP `406 Not Acceptable`. Player should fall back to `/hls` after receiving 406"
   }
  },
  {
   "title": "mist HLS .m3u8 requests from CDN (per playbackId)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(playbackId) (count_over_time({app=\"ingress-nginx\"} |~ `GET /mist/.*\\.m3u8` | regexp `.*/mist/hls/(?P<playbackId>[^/]*)/.*` [1m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 16 },
   "options": {
    "content": "Number of `/mist/hls/...m3u8` requests from CDN (based on ingress-nginx logs). These requests aren't cached by CDN - they pass-through."
   }
  },
  {
   "title": "mist HLS .ts requests from CDN (per playbackId)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(playbackId) (count_over_time({app=\"ingress-nginx\"} |~ `GET /mist/.*\\.ts` | regexp `.*/mist/hls/(?P<playbackId>[^/]*)/.*` [1m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 24 },
   "options": {
    "content": "Number of `/mist/hls/...ts` requests from CDN (based on ingress-nginx logs)"
   }
  }
 ]
}