{
 "title": "Federated Livepeer Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Overload, streams",
   "type": "stat",
   "description": "Number of current streams on across Broadcasters minus maximum sessions across Orchestrators",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"}) - sum(livepeer_max_sessions_total{node_type=\"orch\"})"
    }
   ]
  },
  {
   "title": "Concurrent Streams",
   "type": "stat",
   "description": "Number of concurrent streams across all broadcasters",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Broadcasters Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{livepeer_node_type=~\"^.*broadcaster.*$\"})"
    }
   ]
  },
  {
   "title": "Emerged segments",
   "type": "stat",
   "description": "Total number of segments emerged from segmenter.",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_emerged_unprocessed_total)"
    }
   ]
  },
  {
   "title": "Success rate (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_transcoded_all_appeared_total[1m])) by (node_id,region) / sum(rate(livepeer_segment_source_emerged_total[1m])) by (node_id,region)",
     "legendFormat": "{{region}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Orchestrators Utilisation",
   "type": "gauge",
   "description": "Percentage of streams running on Orchestrators to maxSessions of Orchestrator",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"orch\"}) / sum(livepeer_max_sessions_total{node_type=\"orch\"})*100"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Orchestrators Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{livepeer_node_type=~\"^.*orchestrator.*$\"})"
    }
   ]
  },
  {
   "title": "Transcoded Segments",
   "type": "stat",
   "description": "Total number of transcoded segments.",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcoded_unprocessed_total)"
    }
   ]
  },
  {
   "title": "Success Rate (Client, 1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "livepeer_success_rate{node_type=\"bctr\"} and max_over_time(livepeer_current_sessions_total{node_type=\"bctr\"}[1m]) > 0",
     "legendFormat": "{{region}}-{{node_id}}"
    }
   ]
  },
  {
   "title": "Transcode time, percentiles",
   "type": "graph",
   "description": "Transcode times, measured at transcoder.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_time_seconds_bucket{node_type=\"orch\"}[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Latency, percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by ( le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by ( le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Average Transcode Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])",
     "legendFormat": "{{node_id}}/{{profiles}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "description": "Latency is calculated on Broadcaster, from time source segment goes out from segmenter till transcoded segment gets inserted into manifest.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_transcode_overall_latency_seconds_sum{node_type=\"bctr\"}[1m])) by (instance) / sum(rate(livepeer_transcode_overall_latency_seconds_count{node_type=\"bctr\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upload Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_upload_failed_total{error_code!=\"DuplicateSegment\"}[1m])) by (error_code)",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Transcode Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_transcode_failed_total{error_code!=\"DuplicateSegment\"}[1m])) by (error_code)",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Duplicate Segments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_upload_failed_total{error_code=\"DuplicateSegment\"}[1m]))",
     "legendFormat": "UploadFailed"
    },
    {
     "expr": "sum(increase(livepeer_segment_transcode_failed_total{error_code=\"DuplicateSegment\"}[1m]))",
     "legendFormat": "TranscodeFailed"
    }
   ]
  },
  {
   "title": "Discovery Errors ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_discovery_errors_total[30s])) by (region, error_code)",
     "legendFormat": "{{region}} {{error_code}}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_retried[1m])",
     "legendFormat": "{{instance}} - try={{try}}"
    }
   ]
  },
  {
   "title": "Transcode Errors Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcode_failed_total) by (error_code)",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Upload Errors Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_upload_failed_total) by (region, error_code)",
     "legendFormat": "{{region}} {{error_code}}"
    }
   ]
  },
  {
   "title": "HTTP Client Timeout 1",
   "type": "graph",
   "description": "Number of times HTTP push connection was dropped before transcoding complete",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_http_client_timeout_1[1m])) by (node_id)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Not Uploaded Segments, rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_appeared_total[30s])) - sum(increase(livepeer_segment_source_uploaded_total[30s]))\n"
    },
    {}
   ]
  },
  {
   "title": "HTTP Client timeout 2",
   "type": "graph",
   "description": "Number of times HTTP push connection was dropped before transcoded segments was sent back to client",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_http_client_timeout_2[1m])) by (node_id)",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "HTTP push realtime ratio",
   "type": "graph",
   "description": "Percentage of segments transcoded faster than 3x realtime speed, 3x, 1x,  half realtime and more than two time slower than realtime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_3x[1m]))/sum(increase(livepeer_segment_source_emerged_unprocessed_total[1m]))",
     "legendFormat": "3x"
    },
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_2x[1m]))/sum(increase(livepeer_segment_source_emerged_unprocessed_total[1m]))",
     "legendFormat": "2x"
    },
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_1x[1m]))/sum(increase(livepeer_segment_source_emerged_unprocessed_total[1m]))",
     "legendFormat": "1x"
    },
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_half[1m]))/sum(increase(livepeer_segment_source_emerged_unprocessed_total[1m]))",
     "legendFormat": "half realtime"
    },
    {
     "expr": "sum(increase(livepeer_http_client_segment_transcoded_realtime_slow[1m]))/sum(increase(livepeer_segment_source_emerged_unprocessed_total[1m]))",
     "legendFormat": "slow"
    }
   ]
  },
  {
   "title": "Segments Number",
   "type": "graph",
   "description": "Total number of segments emerged from segmenter and total number of segments transcoded",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_emerged_unprocessed_total)",
     "legendFormat": "emerged"
    },
    {
     "expr": "sum(livepeer_segment_transcoded_unprocessed_total)",
     "legendFormat": "transcoded"
    }
   ]
  },
  {
   "title": "Orchestrator Swaps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_orchestrator_swaps[1m]))",
     "legendFormat": "SwapsPerMinute"
    }
   ]
  },
  {
   "title": "Recording Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(livepeer_recording_save_errors[30s])"
    }
   ]
  },
  {
   "title": "Saved segments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_recording_saved_segments[30s]))"
    }
   ]
  },
  {
   "title": "Recording save latency, percentiles",
   "type": "graph",
   "description": "Time it takes to save segment to object storage (GCP)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(livepeer_recording_save_latency_bucket[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(livepeer_recording_save_latency_bucket[1m])) by ( le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(livepeer_recording_save_latency_bucket[1m])) by ( le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(livepeer_recording_save_latency_bucket[1m])) by ( le))",
     "legendFormat": "99th"
    }
   ]
  }
 ]
}