{
 "title": "Grafana Image Rendering Service",
 "description": "Monitor the Grafana Image Renderer plugin when running it as a remote rendering service.",
 "tags": [
  "grafana",
  "image renderer"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<h5>This dashboard measures the performance of Grafana's image rendering service. For more information on the image renderer, measurement and performance optimization, refer to the <a href=\"https://grafana.com/docs/grafana/next/image-rendering/\" target=0>Grafana docs</a>. </h5>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(grafana_image_renderer_browser_info > 0)"
    }
   ]
  },
  {
   "title": "Browser version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, grafana_image_renderer_browser_info)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Requests per second (by status)",
   "type": "graph",
   "description": "Average requests per second during past interval grouped by status codes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (label_replace(label_replace(rate(grafana_image_renderer_service_http_request_duration_seconds_count[$__rate_interval]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance,status_code)(\n    rate(grafana_image_renderer_service_http_request_duration_seconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance,status_code)(\n    rate(grafana_image_renderer_service_http_request_duration_seconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance,status_code) (rate(grafana_image_renderer_service_http_request_duration_seconds_sum[$__rate_interval])) \n/ \nsum without(instance,status_code) (rate(grafana_image_renderer_service_http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Requests per second (by instance)",
   "type": "graph",
   "description": "Average requests per second during past interval grouped by instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(grafana_image_renderer_service_http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request latency distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(grafana_image_renderer_service_http_request_duration_seconds_bucket[$__interval]) * $__interval_ms / 1000) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests in flight (by instance)",
   "type": "graph",
   "description": "Number of concurrent requests grouped by instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (grafana_image_renderer_http_request_in_flight)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request latency compared to steps latency (avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"launch\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"launch\"}[$__rate_interval]))",
     "legendFormat": "launch"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"newPage\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"newPage\"}[$__rate_interval]))",
     "legendFormat": "newPage"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"prepare\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"prepare\"}[$__rate_interval]))",
     "legendFormat": "prepare"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"navigate\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"navigate\"}[$__rate_interval]))",
     "legendFormat": "navigate"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"panelsRendered\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"panelsRendered\"}[$__rate_interval]))",
     "legendFormat": "panelsRendered"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"screenshot\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"screenshot\"}[$__rate_interval]))",
     "legendFormat": "screenshot"
    },
    {
     "expr": "sum without(instance,status_code) (rate(grafana_image_renderer_service_http_request_duration_seconds_sum[$__rate_interval])) \n/ \nsum without(instance,status_code) (rate(grafana_image_renderer_service_http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Request latency (avg)"
    }
   ]
  },
  {
   "title": "Launch latency",
   "type": "graph",
   "description": "The duration of launching the Chromium browser. This is null for \"clustered\" or \"reusable\" modes.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"launch\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"launch\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"launch\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"launch\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "New page latency",
   "type": "graph",
   "description": "The duration of opening a Chromium incognito page. This is null for \"clustered\" mode.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"newPage\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"newPage\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"newPage\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"newPage\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Prepare page latency",
   "type": "graph",
   "description": "The duration of preparing the Chromium page (setting the viewport, the cookie, the timezone and the extra HTTP headers if needed).",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"prepare\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"prepare\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"prepare\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"prepare\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Navigate latency",
   "type": "graph",
   "description": "The duration of navigating to the Grafana page (including waiting for all network requests to end).",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"navigate\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"navigate\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"navigate\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"navigate\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Panels rendered latency",
   "type": "graph",
   "description": "The duration of waiting for the panel(s) to be rendered. ",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"panelsRendered\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"panelsRendered\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"panelsRendered\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"panelsRendered\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Screenshot latency",
   "type": "graph",
   "description": "The duration of taking the screenshot of the page. ",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"screenshot\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance)(\n    rate(grafana_image_renderer_step_duration_seconds_bucket{step=\"screenshot\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance) (rate(grafana_image_renderer_step_duration_seconds_sum{step=\"screenshot\"}[$__rate_interval])) \n/ \nsum without(instance) (rate(grafana_image_renderer_step_duration_seconds_count{step=\"screenshot\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}