{
 "title": "Kube API Alerts",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{}[15m])>1) by (region)",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Pod Restarts by Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{}[15m])>1) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas Unavailable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node DiskPressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"} > 0",
     "legendFormat": "{{ region }}-{{ node }}"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=~\"false|unknown\"} > 0",
     "legendFormat": "{{ region }}-{{ node }}"
    }
   ]
  },
  {
   "title": "Pods Evicted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_status_reason{reason=\"Evicted\"}==1)) by (region)"
    }
   ]
  },
  {
   "title": "Node MemoryPressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"} > 0",
     "legendFormat": "{{ region }}-{{ node }}"
    }
   ]
  },
  {
   "title": "Node PIDPressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"PIDPressure\", status=\"true\"} > 0",
     "legendFormat": "{{ region }}-{{ node }}"
    }
   ]
  },
  {
   "title": "CrashLoopBackoff (by container)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(container) (kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"})"
    }
   ]
  }
 ]
}