{
 "title": "Livepeer Fast Verification",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Unverified : Verified Segment Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": ": 1" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg(livepeer_segment_transcoded_total{trusted=\"untrusted\", verified=\"verified\",node_type=\"bctr\"}) / 2) / avg(livepeer_segment_transcoded_total{trusted=\"untrusted\", verified=\"unverified\",node_type=\"bctr\"})) * 100"
    }
   ]
  },
  {
   "title": "Streams using public orchestrators, %",
   "type": "gauge",
   "description": "Percentage of streams using public orchestrators",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_fast_verification_using_current_sessions_total{node_type=\"bctr\"})/sum(livepeer_fast_verification_enabled_current_sessions_total{node_type=\"bctr\"})*100\n"
    }
   ]
  },
  {
   "title": "Streams with fast verification enabled, %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_fast_verification_enabled_current_sessions_total{node_type=\"bctr\"})/sum(livepeer_current_sessions_total{node_type=\"bctr\"})*100\n"
    }
   ]
  },
  {
   "title": "Segments transcoded trusted/untrusted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_transcoded_total{node_type=\"bctr\"}[30s])) by (trusted, verified)"
    }
   ]
  },
  {
   "title": "Fast Verification Session Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(livepeer_fast_verification_using_current_sessions_total{node_type=\"bctr\"})",
     "legendFormat": "Using fast verification"
    },
    {
     "expr": "sum(livepeer_fast_verification_enabled_current_sessions_total{node_type=\"bctr\"})-sum(livepeer_fast_verification_using_current_sessions_total{node_type=\"bctr\"})",
     "legendFormat": "Enabled but not using"
    },
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"})-sum(livepeer_fast_verification_enabled_current_sessions_total{node_type=\"bctr\"})",
     "legendFormat": "Not enabled fast verification"
    }
   ]
  },
  {
   "title": "FV success rate per Orchestrator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vector(1)- rate(livepeer_fast_verification_failed[1m])",
     "legendFormat": "FV success rate {{orchestrator_uri}} "
    }
   ]
  },
  {
   "title": "Fast Verification success rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(livepeer_fast_verification_done[1m])) - (sum(rate(livepeer_fast_verification_failed[1m])) or vector(0))) / sum(rate(livepeer_fast_verification_done[1m]))",
     "legendFormat": "fast verification success rate"
    }
   ]
  },
  {
   "title": "FV Signature Comparison fail rate per Orchestrator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(livepeer_fast_verification_failed{fverror_type!=\"2\"}[1m]))",
     "legendFormat": "FV Type1 fail rate {{orchestrator_uri}} {{region}}"
    }
   ]
  },
  {
   "title": "FV Video Comparison fail rate per Orchestrator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(livepeer_fast_verification_failed{fverror_type!=\"1\"}[1m]))",
     "legendFormat": "FV Type2 fail rate {{orchestrator_uri}} {{region}}"
    }
   ]
  },
  {
   "title": "Transcoded segments - trusted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcoded_total{trusted=\"trusted\",node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Transcoded segments - trusted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcoded_total{trusted=\"trusted\",node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Transcoded segments - untrusted/unverified",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcoded_total{trusted=\"untrusted\", verified=\"unverified\",node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Fast Verification Fails Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fast_verification_failed{})"
    }
   ]
  }
 ]
}