{
 "title": "MediaMTX",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region name",
    "query": {
     "query": "label_values(rtmp_conns{kubernetes_name=~\".+-mediamtx\"},region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RTMP connections by state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(state) (rtmp_conns{kubernetes_name=~\".+-mediamtx\", region=~\"${region:pipe}\", state!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTMP data sent/received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rtmp_conns_bytes_sent{kubernetes_name=~\".+-mediamtx\", region=~\"${region:pipe}\"})",
     "legendFormat": "rtmp_conns_bytes_sent"
    },
    {
     "expr": "sum(rtmp_conns_bytes_received{kubernetes_name=~\".+-mediamtx\", region=~\"${region:pipe}\"})",
     "legendFormat": "rtmp_conns_bytes_received"
    }
   ]
  },
  {
   "title": "WebRTC Sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by() (webrtc_sessions{kubernetes_name=~\".+-mediamtx\", region=~\"${region:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebRTC data received/sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(webrtc_sessions_bytes_received{kubernetes_name=~\".+-mediamtx\", region=~\"${region:pipe}\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(webrtc_sessions_bytes_sent{kubernetes_name=~\".+-mediamtx\", region=~\"${region:pipe}\"})",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "ready paths",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(name) (paths{kubernetes_name=~\".+-mediamtx\", state=\"ready\", region=~\"${region:pipe}\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by(name) (paths{kubernetes_name=~\".+-mediamtx\", state=\"notReady\", region=~\"${region:pipe}\"})",
     "legendFormat": "{{name}} notReady"
    }
   ]
  }
 ]
}