{
 "title": "Mist Global Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodesel",
    "query": "catalyst_node=~\".*monster\""
   },
   { "name": "nodegrp", "query": " by (catalyst_node)" },
   { "name": "nodeon", "query": "catalyst_node" }
  ]
 },
 "panels": [
  {
   "title": "Total viewers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mist_sessions_total{sessType=\"viewers\",$nodesel})"
    }
   ]
  },
  {
   "title": "Active streamers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mist_sessions_total{sessType=\"incoming\",$nodesel})"
    }
   ]
  },
  {
   "title": "Protocol usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mist_outputs{output!=\"HTTP\",$nodesel}) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Viewers per server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mist_sessions_total{sessType=\"viewers\",$nodesel}) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  },
  {
   "title": "Broadcasts in the last 30 days",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{sessType=~\"incoming\",$nodesel}[30d]))"
    }
   ]
  },
  {
   "title": "Viewtime in the last 30 days",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_sessions_total{sessType=\"viewers\",$nodesel}[30d]))*720"
    }
   ]
  },
  {
   "title": "Broadcast time in the last 30 days",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_sessions_total{sessType=\"incoming\",$nodesel}[30d]))*720"
    }
   ]
  },
  {
   "title": "Bandwidth (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate((sum(mist_bw_total{$nodesel}) $nodegrp)[10m])*8)",
     "legendFormat": "External"
    },
    {
     "expr": "sum(rate((sum(mist_bw_other{$nodesel}) $nodegrp)[10m])*8)",
     "legendFormat": "Internal"
    }
   ]
  },
  {
   "title": "Incoming streams per server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mist_sessions_total{sessType=\"incoming\",$nodesel}) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  },
  {
   "title": "Viewers / Broadcasters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mist_sessions_total{sessType=\"viewers\",$nodesel})",
     "legendFormat": "Viewers"
    },
    {
     "expr": "sum(mist_sessions_total{sessType=\"incoming\",$nodesel})",
     "legendFormat": "Broadcasters"
    }
   ]
  },
  {
   "title": "Bandwidth (per server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(mist_bw_total{$nodesel}[10m])*8) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    },
    {
     "expr": "sum(rate(mist_bw_other{$nodesel}[10m])*8) $nodegrp",
     "legendFormat": "{{$nodeon}} internal"
    }
   ]
  },
  {
   "title": "CPU per server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_cpu{$nodesel}[180s])/10) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  },
  {
   "title": "Memory per server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(mist_shm_used{$nodesel} / mist_shm_total{$nodesel} * 100 > mist_mem_used{$nodesel} / mist_mem_total{$nodesel} * 100) $nodegrp",
     "legendFormat": "{{$nodeon}} SHM"
    },
    {
     "expr": "sum(mist_mem_used{$nodesel} / mist_mem_total{$nodesel} * 100 > mist_shm_used{$nodesel} / mist_shm_total{$nodesel} * 100) $nodegrp",
     "legendFormat": "{{$nodeon}} RAM"
    }
   ]
  },
  {
   "title": "Log rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mist_logs{$nodesel}[5m])) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  },
  {
   "title": "Reconnects per 10 minutes per user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(mist_sessions_count{sessType=\"viewers\",$nodesel}[30m])*600 / mist_sessions_total{sessType=\"viewers\",$nodesel}) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  },
  {
   "title": "Viewers per broadcaster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mist_sessions_total{sessType=\"viewers\",$nodesel}) / sum(mist_sessions_total{sessType=\"incoming\",$nodesel})",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Edge bandwidth per user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(mist_bw_total{direction=\"up\",$nodesel}[1m])*8 / on ($nodeon) mist_sessions_total{sessType=\"viewers\",$nodesel}) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  },
  {
   "title": "Origin sessions per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{sessType=\"incoming\",$nodesel}[1d])) by (sessType,$nodeon)",
     "legendFormat": "{{$nodeon}}: {{sessType}}"
    }
   ]
  },
  {
   "title": "Average per week",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_sessions_total{sessType=\"viewers\",$nodesel}[7d]))",
     "legendFormat": "Viewers"
    },
    {
     "expr": "sum(avg_over_time(mist_sessions_total{sessType=\"incoming\",$nodesel}[7d]))",
     "legendFormat": "Broadcasters"
    }
   ]
  },
  {
   "title": "Trigger failure rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_fails{$nodesel}[15m])) by (trigger,$nodeon) / on(trigger,$nodeon) sum(rate(mist_trigger_count{$nodesel}[15m])) by (trigger,$nodeon)",
     "legendFormat": "{{$nodeon}} {{trigger}}"
    }
   ]
  },
  {
   "title": "Trigger runtime",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_time{$nodesel}[15m])) by (trigger,$nodeon) / on(trigger,$nodeon) sum(rate(mist_trigger_count{$nodesel}[15m])) by (trigger,$nodeon)",
     "legendFormat": "{{$nodeon}} {{trigger}}"
    }
   ]
  },
  {
   "title": "Trigger rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mist_trigger_count{$nodesel}[10m])) by (trigger,$nodeon)",
     "legendFormat": "{{$nodeon}} {{trigger}}"
    }
   ]
  },
  {
   "title": "Total viewers per protocol",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mist_outputs{$nodesel}) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Total incoming sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mist_sessions_count{sessType=~\"incoming\",$nodesel}) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  },
  {
   "title": "Views per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{sessType=\"viewers\",$nodesel}[1h])) $nodegrp",
     "legendFormat": "{{catalyst_node}}"
    }
   ]
  },
  {
   "title": "Views per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mist_sessions_count{sessType=\"viewers\",$nodesel}[1d])) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    },
    {
     "expr": "sum(increase(mist_sessions_count{sessType=\"viewers\",$nodesel}[1d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU per 100 viewers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(mist_cpu{$nodesel}[1d])*10) $nodegrp / on($nodeon) sum(avg_over_time(mist_sessions_total{sessType=\"viewers\",$nodesel}[1d])) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  },
  {
   "title": "Peak viewers in 24h period",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(sum(mist_sessions_total{sessType=\"viewers\",$nodesel})[1d])",
     "legendFormat": "Viewers"
    }
   ]
  },
  {
   "title": "Peak broadcasts in 24h period",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(sum(mist_sessions_total{sessType=\"incoming\",$nodesel})[1d])",
     "legendFormat": "Viewers"
    }
   ]
  },
  {
   "title": "Bandwidth used per month",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(mist_bw_total{$nodesel}[30d])) $nodegrp",
     "legendFormat": "{{$nodeon}}"
    }
   ]
  }
 ]
}