{
 "title": "nginx 5XX",
 "tags": [ "nginx" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "status",
    "label": "status code",
    "query": "5XX : 5.., 4XX : 4.., 3XX : 3.., 2XX : 2.., 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511"
   },
   {
    "name": "ingress",
    "label": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{status=~\"${status:pipe}\"},ingress)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{ingress=~\"$ingress\", status=~\"${status:pipe}\"},region)"
    }
   },
   {
    "name": "host",
    "label": "hostname",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{ingress=~\"$ingress\", region=~\"$region\", status=~\"${status:pipe}\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate (2XX-4XX response percentage)",
   "type": "timeseries",
   "description": "Number of 5XX over the number of all requests per ingress",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(ingress) (rate(nginx_ingress_controller_requests{ingress=~\"${ingress:pipe}\", region=~\"${region:pipe}\", host=~\"${host:pipe}\", status!~\"[5].*\"}[$__interval])) / sum by(ingress) (rate(nginx_ingress_controller_requests{ingress=~\"${ingress:pipe}\", region=~\"${region:pipe}\", host=~\"${host:pipe}\"}[$__interval]))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Total req/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum by(ingress) (irate(nginx_ingress_controller_requests{ingress=~\"${ingress:pipe}\", region=~\"${region:pipe}\", host=~\"${host:pipe}\"}[$__interval])), 0.01)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  { "title": "Status: $status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "${status} per host/method/path",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(path, host, method) (increase(nginx_ingress_controller_requests{ingress=~\"${ingress:pipe}\", region=~\"${region:pipe}\", host=~\"${host:pipe}\", status=~\"${status:pipe}\"}[$__interval]))",
     "legendFormat": "{{ host }} {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "${status} requests per ingress",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(ingress) (increase(nginx_ingress_controller_requests{ingress=~\"${ingress:pipe}\", region=~\"${region:pipe}\", host=~\"${host:pipe}\", status=~\"${status:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "${status} per region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(region) (increase(nginx_ingress_controller_requests{ingress=~\"${ingress:pipe}\", region=~\"${region:pipe}\", host=~\"${host:pipe}\", status=~\"${status:pipe}\"}[$__interval]))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "${status} per status code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(nginx_ingress_controller_requests{ingress=~\"${ingress:pipe}\", region=~\"${region:pipe}\", host=~\"${host:pipe}\", status=~\"${status:pipe}\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Nginx logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{app=\"ingress-nginx\", namespace=\"default\", stream=\"stdout\", region=~\"${region:pipe}\"} | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<origin>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | upstream =~ `default-(${ingress:pipe})-.*` | status =~ `${status:pipe}`"
    }
   ]
  },
  {
   "title": "429 code - IP-address rate limited",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(ingress) (increase(nginx_ingress_controller_requests{region!=\"fra\", status=\"429\", ingress=~\"$ingress\"}[$__interval]))",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "options": {
    "content": "* We don't collect `/health`, `/healthz`, `/{{ UUID }}.json`, `/loki/api/v1/push`, `/insert/420/prometheus` logs.\nSo even you can see prometheus metrics related to these endpoints the logs are missing\n* Too narrow time range may filter out some logs while showing prometheus metrics on charts as metrics and logs might have slightly different datetimes.\n* 503 may come from pods or be returned from nginx when per IP address limits are hit\n* [Explore nginx logs](https://eu-metrics-monitoring.livepeer.live/grafana/explore?schemaVersion=1&panes=%7B%22D32%22:%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22ingress-nginx%5C%22,%20namespace%3D%5C%22default%5C%22,%20stream%3D%5C%22stdout%5C%22,%20region%3D~%5C%22${region:pipe}%5C%22%7D%20%7C%20pattern%20%60%3Cip%3E%20-%20-%20%3Ctimestamp%3E%20%5C%22%3Cmethod%3E%20%3Curl%3E%20%3Cprotocol%3E%5C%22%20%3Cstatus%3E%20%3Cbytes%3E%20%5C%22%3Corigin%3E%5C%22%20%5C%22%3CuserAgent%3E%5C%22%20%3Cwtf1%3E%20%3Cwtf2%3E%20%5B%3Cupstream%3E%5D%20%5B%3Cwtf3%3E%5D%20%3CupstreamAddr%3E%20%3Cwtf4%3E%20%3Cwtf5%3E%20%3CupstreamStatus%3E%20%3CrequestId%3E%60%20%7C%20upstream%20%3D~%20%60default-%28${ingress:pipe}%29-.%2A%60%20%7C%20status%20%3D~%20%60${status:pipe}%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22${__from}%22,%22to%22:%22${__to}%22%7D%7D%7D&orgId=1)"
   }
  }
 ]
}