{
 "title": "papertrail alerts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "etcd write failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (region) (count_over_time({app=\"mist\"} |~ \"Error creating etcd Traefik rule\"[1m]))"
    }
   ]
  },
  {
   "title": "increased panics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"prod-livepeer-[^(secondary|monitoring)].*\"} |= \"panic\"[1m]))"
    }
   ]
  },
  {
   "title": "request per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time(\n  {app=\"traefik\", region!=\"eu-metrics\", container=\"prod-traefik\", region!=\"mdw\"} \n  | json \n  | __error__!=\"JSONParserErr\"\n  | line_format \"{{.RequestPath}}\" \n  | regexp \"/hls/(\\\\w+\\\\+)?(?P<playback_id>[^/]+).+\"\n  [1m]\n )) by (playback_id, region) > 60000"
    }
   ]
  },
  {
   "title": "zombie external dns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"external-dns\"} |= \"owner id does not match\"[1m])) by (region)"
    }
   ]
  },
  {
   "title": "bgp unreachable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"bgpm-exporter\"} |= \"The following nodes were unreachable in\"[1m])) by (reigon)"
    }
   ]
  },
  {
   "title": "Stream Health Publish Error ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (region) (rate({app=~\"prod-livepeer-broadcaster.*\"} |= \"Error publishing stream transcode event\"[1m]))"
    }
   ]
  },
  {
   "title": "unknown panics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({app!=\"bgpm-exporter\",region=~\"^(sgp|eu-metrics).+\"} |= \"panic\"[1m])) by (region)"
    }
   ]
  },
  {
   "title": "RabbitMQ Network Partition By region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"prod-rabbitmq\",component=\"rabbitmq\"} |~ \"mnesia_event\" |~ \"inconsistent_database\" |~  \"running_partitioned_network\"[1m])) by (region)"
    }
   ]
  },
  {
   "title": "API DB Connection Timeouts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (region) (count_over_time({app=\"prod-livepeer-api\"} |= \"Connection terminated due to connection timeout\"[1m]))"
    }
   ]
  },
  {
   "title": "KRYPTONITE",
   "type": "timeseries",
   "description": "[LOPRI] KRYPTONITE DETECTED!!! 🦠",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"prod-livepeer-broadcaster.*\"} |~ \"Hit max transcode attempts: body timeout: context deadline exceeded\"[1m]))"
    }
   ]
  }
 ]
}