{
 "title": "Traefik Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "503s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=\"503\"}[1m])) by (region)"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_sum{}[1m])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Open Connections?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_open_connections{}[1m])) by (region)"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"5.+\"}[1m])) by (region)"
    }
   ]
  },
  {
   "title": "Status Code != 200",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code != \"200\", code != \"404\"}[1m])) by (code)"
    }
   ]
  },
  {
   "title": "All Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{}[1m])) by (region)"
    }
   ]
  }
 ]
}