{
 "title": "VoD Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "query": "mist,external|aws-mediaconvert,catalyst_ffmpeg"
   }
  ]
 },
 "panels": [
  {
   "title": "$pipeline - Overall VOD Success",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pipeline"
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(vod_count{stage=\"failed\", pipeline=~\"${pipeline:raw}\"})[5m]) or vector(0)"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum (increase(vod_count{stage=\"failed\", pipeline=~\"${pipeline:raw}\"}[15m]) or vector(0)) / sum(increase(vod_count{pipeline=~\"${pipeline:raw}\"}[15m]) or vector(0)))",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Latest Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "{namespace=~\"default\", app=\"catalyst\"} |~ \"Updated transcode status\" |~ \"handler=${pipeline:raw}\" | logfmt | status = \"error\" | line_format \"{{ .request_id }} - {{ .error }}\""
    }
   ]
  },
  {
   "title": "Successful Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(vod_count{stage=\"completed\", pipeline=~\"${pipeline:raw}\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of VOD Jobs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(vod_count{pipeline=~\"${pipeline:raw}\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Object Store Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg(increase(object_store_request_duration_sum[1m])) by (host, operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingests by audio/video Codec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(vod_count[15m])) by (source_codec_video, source_codec_audio)",
     "legendFormat": "{{source_codec_video}}  {{source_codec_audio}} "
    }
   ]
  },
  {
   "title": "Count of Fallback Jobs",
   "type": "stat",
   "description": "This stat counts the entries where in_fallback_mode == true to indicate how many jobs are entering the fallback external pipeline after failing the primary Mist/Livepeer pipeline",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(vod_count{is_fallback_mode=\"true\"})[15m]) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs In Flight",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 37 },
   "targets": [
    { "expr": "sum(jobs_in_flight) by(region)", "legendFormat": "__auto" }
   ]
  }
 ]
}