{
 "title": "Trovo viewership",
 "tags": [
  "viewership",
  "metrics",
  "observe",
  "2023",
  "trovo"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "TROVO_USER_ID",
    "query": "a7833805-e313-452b-8c72-18923137f48d"
   }
  ]
 },
 "panels": [
  { "title": "Viewership breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Viewers globally",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", user_id=\"${TROVO_USER_ID}\"})",
     "legendFormat": "Trovo"
    }
   ]
  },
  {
   "title": "Viewers per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", user_id=\"${TROVO_USER_ID}\"}[1m] ) by (catalyst_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Viewers per stream",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", user_id=\"${TROVO_USER_ID}\"}[1m] ) by (stream) or on() vector(0), \"stream_id\", \"$1\", \"stream\", \".*\\\\+(.*)\")",
     "legendFormat": "{{stream_id}}"
    }
   ]
  },
  {
   "title": "Viewers per region",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", user_id=\"${TROVO_USER_ID}\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Origin server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "count by(catalyst_node) (mist_sessions{sessType=\"incoming\", user_id=\"${TROVO_USER_ID}\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}