{
 "title": "Fishtank 3.0 viewership",
 "tags": [
  "fishtank",
  "viewership",
  "metrics",
  "observe",
  "2023"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ROOMS",
    "query": "Bar : f77b5hz939s8z89b,Flat : 4fb8to1674q6ht0m,Greenroom : 110bhp7ka9dbr86h,Bedroom 1 : b65269ekvyvfkous,Bedroom 2 : 36708jd80gr91018,Bedroom 3 : 44daqjc6r1dfxd2e,Vanity : 68f8q4hl8cys37n2,Hallway : 3760543f053u6c5m,Mail Room : 84485q0ve58ckwm2,Kitchen : 8c8btla37r6nux8f,Kitchen PTZ : eac7ihz7d6ya9v1y,Dining Room : afacw5eipuyfsfny,Confessional : 21aflvcz5puavd2e,Lounge : 9f41r40060icglir,Locker Room : 7d3e7e9s5qm5l1uf,Penthouse : 0c0bun9tebd65k3j,Jacuzzi : 122bkgvyrj1f7pk4,Loft : 9d5ckl8snb01ba6i,Den : d678xcnkn2slngkx,Den PTZ : 8e1arf44e86qa7ru,Deck : b4e4iknxyd1u4g0c,Catwalk : 580elsslerqmt28u,Front Yard : 4ab29ayc51cmiu7k,Back Yard : 38847hg4plyxhzlf"
   }
  ]
 },
 "panels": [
  {
   "title": "Status code (nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" |~ \"${ROOMS:pipe}\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | line_format \"{{ .referer }}\" | pattern \"<refererScheme>://<refererDomain>/<refererPath>\" | line_format \"{{ .refererDomain }}\"[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Access Control Allow vs Deny",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |~ \"Playback access control\" |~ \"${ROOMS:pipe}\" | pattern `<_> Playback access control <status> `[1m])) by (status)"
    }
   ]
  },
  { "title": "Viewership breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Viewers globally",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m])",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Viewers per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m] ) by (catalyst_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Viewers per room",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m] ) by (stream) or on() vector(0), \"stream_id\", \"$1\", \"stream\", \".*\\\\+(.*)\")",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Viewers per region",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Origin server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(catalyst_node) (mist_sessions{sessType=\"incoming\", stream=~\"video(rec)?\\\\+(${ROOMS:pipe})\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}