{
 "title": "Fishtank 2.5 viewership",
 "tags": [
  "fishtank",
  "viewership",
  "metrics",
  "observe",
  "2023"
 ],
 "time": { "from": "2024-06-25T12:00:00.000Z", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ROOMS",
    "query": "player-1 : 07fch8nrf09oduwq,player-2 : 4f5emzrc3tdk2z0f,player-3 : 58d0z7ikrmex1cf4,player-4 : 1eb96gqvcvdkvpxn,player-5 : d462hhgt0dm70v4i,player-6 : c1c1gl1g3hatuqxy,Director : fce7bmzmyigqg3s7,Basecamp : 6265nisbyp5yzb1y,Schitty : a100z3up7fjutopo,Merchant : 1588xv96xxrzf58t,The Downs : 9437407ypzr2rtb9,Campgrounds : 052ejcod22mw7dm3,Soda Tent : eeb1bdrakm4jms72,Beaver Street : 47adl83vpkg634z5,Bus : 96c2sfx928fptosp,Area A : 58b6y7otmf3nz3m2,Area B : b03e3glkp2h91ivm,Wildlands Cave : e9b4a7e4l397sngc,Gulch : c801faefbhz3zeoj"
   }
  ]
 },
 "panels": [
  {
   "title": "Status code (nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" |~ \"${ROOMS:pipe}\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | line_format \"{{ .referer }}\" | pattern \"<refererScheme>://<refererDomain>/<refererPath>\" | line_format \"{{ .refererDomain }}\"[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Access Control Allow vs Deny",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |~ \"Playback access control\" |~ \"${ROOMS:pipe}\" | pattern `<_> Playback access control <status> `[1m])) by (status)"
    }
   ]
  },
  { "title": "Viewership breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Viewers globally",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m])",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Viewers per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m] ) by (catalyst_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Viewers per room",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m] ) by (stream) or on() vector(0), \"stream_id\", \"$1\", \"stream\", \".*\\\\+(.*)\")",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Viewers per region",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Origin server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(catalyst_node) (mist_sessions{sessType=\"incoming\", stream=~\"video(rec)?\\\\+(${ROOMS:pipe})\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}