{
 "title": "Fishtank viewership",
 "tags": [
  "fishtank",
  "viewership",
  "metrics",
  "observe",
  "2023"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ROOMS",
    "query": "Living Room : 2289jf6f37kq3put,Upstairs Bathroom : c00a95tv3rysf9ji,Kitchen : f355shnx2w9xkhxo,Upstairs Hallway : 1bcd83gg4ang03l8,Bar : 9cfeeodtu023cb91,Lounge : 33d25dz3mqilw1lp,Bedroom 1 : a12bmexn0h5td3kh,Downstairs Hallway : cc92intolqvyf117,Master Bathroom : 052cnzsasax9c10b,Bedroom 3 : d7a07saeijthkqqk,Dog House : 2ef11errf17as0df,Bedroom 2 : d01cpugvvx04448x,Downstairs Bathroom : b0739nzrqm6m8k1k,The Bunk : cbcbvq7hgf5vwti2,Attic : 0b6a2wuaxm56yhkr,Launch : c0967lxltr0zkftj,Confessionals : b905oqz6q3czq6pb"
   }
  ]
 },
 "panels": [
  {
   "title": "Status code (nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"default\", app=\"ingress-nginx\", stream=\"stdout\"} != \"51eebae3-9b8e-48bc-89ca-5340c4074a48.json\" |~ \"${ROOMS:pipe}\" | pattern `<ip> - - <timestamp> \"<method> <url> <protocol>\" <status> <bytes> \"<referer>\" \"<userAgent>\" <wtf1> <wtf2> [<upstream>] [<wtf3>] <upstreamAddr> <wtf4> <wtf5> <upstreamStatus> <requestId>` | line_format \"{{ .referer }}\" | pattern \"<refererScheme>://<refererDomain>/<refererPath>\" | line_format \"{{ .refererDomain }}\"[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Access Control Allow vs Deny",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"catalyst\"} |~ \"Playback access control\" |~ \"${ROOMS:pipe}\" | pattern `<_> Playback access control <status> `[1m])) by (status)"
    }
   ]
  },
  { "title": "Viewership breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Viewers globally",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m])",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Viewers per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m] ) by (catalyst_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Viewers per room",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}[1m] ) by (stream) or on() vector(0), \"stream_id\", \"$1\", \"stream\", \".*\\\\+(.*)\")",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Viewers per region",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "sum(mist_sessions{catalyst=\"true\", sessType=\"viewers\", stream=~\".*(${ROOMS:pipe})\"}) by (region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Origin server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "count by(catalyst_node) (mist_sessions{sessType=\"incoming\", stream=~\"video(rec)?\\\\+(${ROOMS:pipe})\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}