{
 "title": "AI Gateway",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "eth", "label": "Eth price", "query": "2068.37" },
   {
    "name": "pipeline",
    "query": {
     "query": "label_values({livepeer_live_app=~\".*livepeer-ai-gateway\"},pipeline)"
    }
   },
   {
    "name": "model",
    "label": "Model",
    "query": {
     "query": "label_values({pipeline=~\"${pipeline:pipe}\", livepeer_live_app=~\".*livepeer-ai-gateway\"},model_name)"
    }
   },
   { "name": "job_livepeer", "label": "Job filter: Gateway" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 }, "options": { "content": "--------\n# Tickets\n-------" } },
  { "type": "text", "gridPos": { "h": 3, "w": 18, "x": 6, "y": 0 }, "options": { "content": "_____\n# Model stats\n_____" } },
  {
   "title": "Ticket value sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Eth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (increase(livepeer_ticket_value_sent{job=~\"^.*$job_livepeer.*$\"}[$__range])) / 1000000000",
     "legendFormat": "eth"
    },
    { "expression": "$A * $eth", "type": "math" }
   ]
  },
  {
   "title": "Completed",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 9, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pipeline, model_name) (increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]))",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    }
   ]
  },
  {
   "title": "Missing supply",
   "type": "piechart",
   "description": "Requests that failed due to no supply being available",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name) (\n    increase(\n        livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", error_code=~\"no orchestrators available.*\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]\n    )\n)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    }
   ]
  },
  {
   "title": "💵 Daily/Monthly Fees",
   "type": "timeseries",
   "description": "Based on the moving average with an interval of 24 hours",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum((rate(livepeer_ticket_value_sent{job=~\"^.*$job_livepeer.*$\"}[1d])*(60*60*24*365)/12)*1e-9 * $eth) or on() vector(0)",
     "legendFormat": "Monthly"
    },
    {
     "expr": "sum((rate(livepeer_ticket_value_sent{job=~\"^.*$job_livepeer.*$\"}[1d])*(60*60*24))*1e-9 * $eth) or on() vector(0)",
     "legendFormat": "Daily"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 }, "options": { "content": "_____\n# Job stats\n_____" } },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Missing supply",
   "type": "stat",
   "description": "Requests that failed due to no supply being available",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", error_code=~\"no orchestrators available.*\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", error_code!~\"no orchestrators available.*\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests completed",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name) (increase(livepeer_ai_models_requested{job=~\"^.*$job_livepeer.*$\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__interval]))",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    }
   ]
  },
  {
   "title": "Average price",
   "type": "stat",
   "description": "What was charged for the average job:\n- upscale: from 512x512 to 1024x1024\n- txt2img: per 1024x1024 frame\n- img2img: per 1024x1024 frame\n- txt2vid: per 25 frames of 1024x1024 \n- img2vid: per 25 frames of 1024x1024\n- audio2txt: per minute of audio",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]) * 1024 * 1024 * 1e-18 * $eth",
     "legendFormat": "Cost"
    },
    {
     "expr": "avg_over_time(livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]) * 1024 * 1024 * 1e-18 * $eth",
     "legendFormat": "Cost"
    },
    {
     "expr": "avg_over_time(livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]) * 1024 * 1024 * 25 * 1e-18 * $eth",
     "legendFormat": "Cost"
    },
    {
     "expr": "avg_over_time(livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]) * 1024 * 1024 * 25 * 1e-18 * $eth",
     "legendFormat": "Cost"
    },
    {
     "expr": "avg_over_time(livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]) * 1000 * 60 * 1e-18 * $eth",
     "legendFormat": "Cost"
    },
    {
     "expr": "avg_over_time(livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"upscale\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]) * 1024 * 1024 * 1e-18 * $eth",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "Errors by model ",
   "type": "piechart",
   "description": "excluding \"no orchestrators available\"",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name) (\n    increase(\n        livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", error_code!~\"no orchestrators available.*\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]\n    )\n)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    }
   ]
  },
  {
   "title": "Requests errors",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 18, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name, error_code) (\n  increase(livepeer_ai_request_errors{\n    job=~\"^.*$job_livepeer.*$\",\n    pipeline=~\"${pipeline:pipe}\",\n    model_name=~\"${model:pipe}\"\n  }[$__interval])\n)",
     "legendFormat": "{{pipeline}} | {{model_name}} | {{ error_code }}"
    }
   ]
  },
  {
   "title": "Error origin",
   "type": "piechart",
   "description": "Where did the error which caused the job to fail occur? (excluding \"no orchestrators available\")",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (orchestrator_address) (increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", error_code!~\"no orchestrators available.*\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]))",
     "legendFormat": "{{orchestrator_address}}"
    }
   ]
  },
  {
   "title": "Average cost",
   "type": "table",
   "description": "What was charged for the average job:\n- upscale: from 512x512 to 1024x1024\n- txt2img: per 1024x1024 frame\n- img2img: per 1024x1024 frame\n- txt2vid: per 25 frames of 1024x1024 \n- img2vid: per 25 frames of 1024x1024\n- audio2txt: per minute of audio",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\", model_name=~\"${model:pipe}\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\", model_name=~\"${model:pipe}\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\", model_name=~\"${model:pipe}\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\", model_name=~\"${model:pipe}\"} * 1024 * 1024 * 25 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\", model_name=~\"${model:pipe}\"} * 1000 * 60 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_price{job=~\"^.*$job_livepeer.*$\", pipeline=\"upscale\", model_name=~\"${model:pipe}\"} * 1024 * 1024 * 1e-18 * $eth)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    }
   ]
  },
  {
   "title": "Latency score",
   "type": "table",
   "description": "Processing times, the lower the better:\n- upscale: time to upscale from 512x512 to 1024x1024\n- txt2img: time to generate a 1024x1024 frame\n- img2img: time to generate a 1024x1024 frame\n- txt2vid: time to generate a 1024x1024 frame\n- img2vid: time to generate a 1024x1024 frame\n- audio2txt: time to process a second of audio",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\", model_name=~\"${model:pipe}\"} * 1)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    },
    {
     "expr": "avg by (pipeline, model_name) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"upscale\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{pipeline}} | {{model_name}}"
    }
   ]
  },
  {
   "title": "Error code",
   "type": "piechart",
   "description": "What's the error message? (excluding \"no orchestrators available\")",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (error_code) (increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", error_code!~\"no orchestrators available.*\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]))",
     "legendFormat": "{{orchestrator_address}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (orchestrator_address, error_code) (increase(livepeer_ai_request_errors{job=~\"^.*$job_livepeer.*$\", error_code!~\"no orchestrators available.*\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__range]))",
     "legendFormat": "{{orchestrator_address}}: {{error_code}}"
    }
   ]
  },
  {
   "title": "Latency score",
   "type": "timeseries",
   "description": "Processing times, the lower the better:\n- upscale: time to upscale from 512x512 to 1024x1024\n- txt2img: time to generate a 1024x1024 frame\n- img2img: time to generate a 1024x1024 frame\n- txt2vid: time to generate a 1024x1024 frame\n- img2vid: time to generate a 1024x1024 frame\n- audio2txt: time to process 1 second of audio",
   "gridPos": { "h": 16, "w": 15, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-image\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-image\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"text-to-video\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"image-to-video\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"audio-to-text\", model_name=~\"${model:pipe}\"} * 1)",
     "legendFormat": "{{orchestrator_address}}"
    },
    {
     "expr": "avg by (orchestrator_address) (livepeer_ai_request_latency_score{job=~\"^.*$job_livepeer.*$\", pipeline=\"upscale\", model_name=~\"${model:pipe}\"} * 1024 * 1024)",
     "legendFormat": "{{orchestrator_address}}"
    }
   ]
  },
  { "title": "Orchestrator versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "AI Orchestrator versions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "count by(orchestrator_version) (count by(orchestrator_uri, orchestrator_version, ) (increase(livepeer_ai_request_latency_score{livepeer_live_app=~\".*-livepeer-ai-gateway.*\", pipeline=~\"${pipeline:pipe}\", model_name=~\"${model:pipe}\"}[$__rate_interval])))",
     "legendFormat": "{{orchestrator_version}}"
    }
   ]
  },
  {
   "title": "AI Gateway logs",
   "type": "logs",
   "description": "excludes `Polling blocks` log lines",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 76 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"ai-gateway\"} != `Polling blocks`"
    }
   ]
  },
  {
   "title": "Livepeer API logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 86 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"prod-livepeer-api\"} |= `/api/beta/generate`"
    }
   ]
  }
 ]
}