{
 "title": "AI Overview (Livestream)",
 "tags": [
  "ai",
  "ai-gateway",
  "ai-runner"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "E2E Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PROD Load Test Success Rate",
   "type": "timeseries",
   "description": "This graph shows the percentage of successful load tests. Anything tests run with < 80% will trigger this alert.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 * (\n  sum (count_over_time({app=~\".*prod-ai-load-test.*\"} |= \"PASS: TestFeatures/Create_a_ComfyUI_Dreamshaper_Stream\" [1h]))\n) / (\n  sum (count_over_time({app=~\".*prod-ai-load-test.*\"} |= \"PASS: TestFeatures/Create_a_ComfyUI_Dreamshaper_Stream\" [1h])) +\n  (sum (count_over_time({app=~\".*prod-ai-load-test.*\"} |= \"FAIL: TestFeatures/Create_a_ComfyUI_Dreamshaper_Stream\" [1h])) or vector(0))\n)"
    }
   ]
  },
  {
   "title": "STAGING Load Test Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 * (\n  sum (count_over_time({app=~\".*staging-ai-load-test.*\"} |= \"PASS: TestFeatures/Create_a_ComfyUI_Dreamshaper_Stream\" [1h]))\n) / (\n  sum (count_over_time({app=~\".*staging-ai-load-test.*\"} |= \"PASS: TestFeatures/Create_a_ComfyUI_Dreamshaper_Stream\" [1h])) +\n  (sum (count_over_time({app=~\".*staging-ai-load-test.*\"} |= \"FAIL: TestFeatures/Create_a_ComfyUI_Dreamshaper_Stream\" [1h])) or vector(0))\n)\n"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(livepeer_ai_current_live_pipelines{livepeer_node_type=\"prod-livepeer-ai-gateway\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Available Capacity (Idle Runners)",
   "type": "timeseries",
   "description": "This graph shows the amount of idle containers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(livepeer_ai_container_idle{}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gateway Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "All Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{app=~\".*-livepeer-ai-gateway\"} != \"Polling blocks\""
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_request_errors{pipeline=~\"live-.*\"}[$__rate_interval])) / sum(increase(livepeer_ai_live_attempt[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ai Video Pipeline Errors by Type",
   "type": "timeseries",
   "description": "Shows the number of occurrences of each unique ‘Live video pipeline’ error in the last 15 minutes, grouped by error type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(\n    {container=\"ai-gateway\"} |= \"Live video pipeline finished with error\" | pattern \"<_>Live video pipeline finished with error: <errorr>\" \n[15m])) by (errorr)"
    }
   ]
  },
  {
   "title": "No Orchestrators Available errors per Region",
   "type": "timeseries",
   "description": "If O does not respond to a request from G within 45s, then G will not retry and flag this error.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pipeline, model_name, region) (increase(livepeer_ai_request_errors{error_code=~\"no orchestrators available.*\", pipeline=~\"live-.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Responses in 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(normalized_error_code, model_name) (label_replace(label_replace(increase(livepeer_ai_request_errors{pipeline=~\"live-.*\"}[1m]), \"normalized_error_code\", \"no orchestrators available\", \"error_code\", \"no orchestrators available.*\"), \"normalized_error_code\", \"$1\", \"error_code\", \"(.*)\"))",
     "legendFormat": "{{model_name}}: {{normalized_error_code}}"
    }
   ]
  },
  {
   "title": "First segment delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(orchestrator_uri) (increase(livepeer_ai_first_segment_delay_ms_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Attempts in 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(livepeer_ai_live_attempt[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Capacity Errors in 1m (no orchestrators available)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(pipeline, model_name) (increase(livepeer_ai_request_errors{error_code=~\"no orchestrators available.*\", pipeline=~\"live-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MediaMTX unsupported codec",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{app=\"mediamtx\"} |~ `the stream doesn't contain any supported codec|closed: codec`"
    }
   ]
  },
  { "title": "Orchestrators Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Total Orchestrator Capacity by Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by(livepeerversion, group) (label_replace(livepeer_versions{job=\"orchestrator\"}, \"group\", \"$1\", \"group\", \".*/(tensordock_.*)\"))",
     "legendFormat": "{{ group }} {{ livepeerversion }}"
    }
   ]
  },
  {
   "title": "CUDA/GPU Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "count by(region, node_name) (rate({container=~\"live-video-to-video.*\"} |~ `CUDA initialization failure with error` [$__auto]))",
     "splitDuration": "1d"
    }
   ]
  },
  {
   "title": "FPS per multistream concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(\n  (\n    avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name)\n  )\n  and\n  (\n    count(avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name, container)) by (node_name) == 1\n  )\n)",
     "legendFormat": "1 stream"
    },
    {
     "direction": "backward",
     "expr": "avg(\n  (\n    avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name)\n  )\n  and\n  (\n    count(avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name, container)) by (node_name) == 2\n  )\n)",
     "legendFormat": "2 streams"
    },
    {
     "direction": "backward",
     "expr": "avg(\n  (\n    avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name)\n  )\n  and\n  (\n    count(avg_over_time({container=~\"live-video-to-video_comfyui.+\", node_name=~\".+\"} |= \"Output FPS\" | pattern \"<_>Output FPS: <fps>\" | unwrap fps [1m]) by (node_name, container)) by (node_name) == 3\n  )\n)",
     "legendFormat": "3 streams"
    }
   ]
  },
  {
   "title": "In-Use Runners per Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum by(region) (sum_over_time(livepeer_ai_container_in_use{node_type=\"orch\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Runners per Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum by(region) (sum_over_time(livepeer_ai_container_idle{node_type=\"orch\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streams per Orchestrator",
   "type": "timeseries",
   "description": "This dashboard monitors the number of streams per orchestrator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sort_desc(sum(livepeer_ai_container_in_use{}) by (node_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle GPUs > 0",
   "type": "timeseries",
   "description": "This graph shows the number of idle GPUs. If it goes above 0 for 5 minutes, then this alert will go off.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "max(livepeer_ai_gpus_idle{}) by (node_id) > 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "timeseries",
   "description": "Measured in Gateways",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum by(livepeer_live_app) (sum_over_time(livepeer_ai_current_live_pipelines{livepeer_node_type=~\"livepeer-ai-gateway|livepeer-ai-gateway2\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Orchestrators",
   "type": "timeseries",
   "description": "SlowOrchestrator is a strong indicator of network connectivity issues between G/O and these tend to persist for a few hours until the tubes clear up or someone kicks something.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (host, region) (\n    count_over_time(\n        {container=\"ai-gateway\"} |= `slow orchestrator` | regexp `url=https?://(?P<host>[^/:]+)`\n    [1h])\n)",
     "legendFormat": "{{region}} host={{host}}"
    }
   ]
  },
  {
   "title": "Orchestrators In-Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "sum by(group) (label_replace(sum_over_time(livepeer_ai_container_in_use{job=\"orchestrator\"}[30s]), \"group\", \"$1\", \"group\", \".*/(tensordock_staging_.*)\"))",
     "legendFormat": "{{group}}-{{region}}"
    }
   ]
  },
  {
   "title": "Missing Capacity Errors in 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum by(pipeline, model_name) (increase(livepeer_ai_request_errors{error_code=~\"no orchestrators available.*\", pipeline=~\"live-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streams per Orchestrator",
   "type": "timeseries",
   "description": "This dashboard monitors the number of streams per orchestrator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sort_desc(sum(livepeer_ai_container_in_use{}) by (node_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orchestrators Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "sum by(group) (label_replace(sum_over_time(livepeer_ai_container_idle{job=\"orchestrator\"}[30s]), \"group\", \"$1\", \"group\", \".*/(tensordock_staging_.*)\"))",
     "legendFormat": "{{group}}-{{region}}"
    }
   ]
  }
 ]
}