{
 "title": "AI Public Os",
 "tags": [
  "ai",
  "orchestrator",
  "daydream"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Orchestrators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Median Output FPS",
   "type": "barchart",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(extract(`semantic`.`stream_status`.`orchestrator_url`, 'https://(.*)'), ' - ', `semantic`.`stream_status`.`pipeline_key`) as orchestrator_short_uri,\n  `median`(`semantic`.`stream_status`.`output_fps`) AS `median`,\n  MAX(`semantic`.`stream_status`.`output_fps`) AS `max`\nFROM\n  `semantic`.`stream_status`\nWHERE\n  $__timeFilter(event_timestamp_ts)\n  AND\n  event_timestamp_ts < now() - INTERVAL 5 minute  -- last minutes data is missing pipeline_* data\n  AND\n  `semantic`.`stream_status`.`orchestrator_url` NOT LIKE '%lvpr.io%' \nGROUP BY\n  orchestrator_short_uri, `semantic`.`stream_status`.`pipeline_key`\nORDER BY\n  `median` DESC,\n  orchestrator_short_uri ASC,\n  `semantic`.`stream_status`.`pipeline_key` ASC\n"
    }
   ]
  },
  {
   "title": "Stream count",
   "type": "barchart",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(extract(`semantic`.`stream_status`.`orchestrator_url`, 'https://(.*)'), ' - ', `semantic`.`stream_status`.`pipeline_key`) as orchestrator_short_uri,\n  COUNT(DISTINCT `semantic`.`stream_status`.`stream_key`) AS `streams_count`\nFROM\n  `semantic`.`stream_status`\nWHERE\n  $__timeFilter(event_timestamp_ts)\n  AND\n  event_timestamp_ts < now() - INTERVAL 5 minute  -- last minutes data is missing pipeline_* data\n  AND\n  `semantic`.`stream_status`.`orchestrator_url` NOT LIKE '%lvpr.io%' \nGROUP BY\n  orchestrator_short_uri\nORDER BY\n  `streams_count` DESC,\n  orchestrator_short_uri ASC\n"
    }
   ]
  },
  {
   "title": "Median Output FPS by Orchestrator URL",
   "type": "timeseries",
   "description": "showing last 7 days data at max",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  `semantic`.`stream_status`.event_timestamp_ts as time,\n  CONCAT(extract(`semantic`.`stream_status`.`orchestrator_url`, 'https://(.*:.+)'), ' - ', `semantic`.`stream_status`.`pipeline_key`) as pipeline,\n  `median`(`semantic`.`stream_status`.`output_fps`) AS ` `\nFROM\n  `semantic`.`stream_status`\nWHERE\n  $__timeFilter(event_timestamp_ts)\n  AND\n  event_timestamp_ts < now() - INTERVAL 5 minute  -- last minutes data is missing pipeline_* data\n  AND\n  `time` >= now() - INTERVAL 7 DAY -- too much data breaks Grafana\n  AND\n  `semantic`.`stream_status`.`orchestrator_url` NOT LIKE '%lvpr.io%' \nGROUP BY\n  `semantic`.`stream_status`.`orchestrator_url`, `semantic`.`stream_status`.`pipeline_key`, `semantic`.`stream_status`.event_timestamp_ts\nORDER BY\n  `semantic`.`stream_status`.event_timestamp_ts ASC,\n  `semantic`.`stream_status`.`orchestrator_url` ASC,\n  `semantic`.`stream_status`.`pipeline_key` ASC\n"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "state-timeline",
   "description": "Showing 7 last days at max",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  `semantic`.`stream_status`.event_timestamp_ts as `time`,\n  CONCAT(extract(`semantic`.`stream_status`.`orchestrator_url`, 'https://(.*)'), ' - ', `semantic`.`stream_status`.`pipeline_key`) as orchestrator_short_uri,\n  COUNT(DISTINCT `semantic`.`stream_status`.`stream_key`) AS ` `\nFROM\n  `semantic`.`stream_status`\nWHERE\n  $__timeFilter(event_timestamp_ts)\n  AND\n  event_timestamp_ts < now() - INTERVAL 5 minute  -- last minutes data is missing pipeline_* data\n  AND\n  `time` >= now() - INTERVAL 7 DAY\n  AND  \n  `semantic`.`stream_status`.`orchestrator_url` NOT LIKE '%lvpr.io%'\nGROUP BY\n  orchestrator_short_uri, `semantic`.`stream_status`.event_timestamp_ts\nORDER BY\n  `semantic`.`stream_status`.event_timestamp_ts ASC,\n  ` ` DESC,\n  orchestrator_short_uri ASC\n\n"
    }
   ]
  },
  {
   "title": "Number of orchestrators per pipeline/model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfHour(`semantic`.`stream_status`.event_timestamp_ts) as _time,\n  `semantic`.`stream_status`.pipeline_key,\n  count(DISTINCT `semantic`.`stream_status`.orchestrator_url ) AS ` `\nFROM\n  `semantic`.`stream_status`\nWHERE\n  $__timeFilter(event_timestamp_ts)\n  AND\n  event_timestamp_ts < now() - INTERVAL 5 minute  -- last minutes data is missing pipeline_* data\n  AND\n  `semantic`.`stream_status`.`orchestrator_url` NOT LIKE '%lvpr.io%'\n  AND\n  _time > '2025-09-17' -- we don't want to expose old models\nGROUP BY\n   pipeline_key, _time\nORDER BY\n  _time ASC,\n  pipeline_key ASC\n"
    }
   ]
  },
  {
   "title": "GPUs per model",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "targets": [
    {
     "rawSql": "SELECT\n     toStartOfHour(`semantic`.`network_capabilities`.timestamp_ts) as `_time`,\n     `semantic`.`network_capabilities`.`model_id` as model_id,\n     count(distinct gpu_id) as ` `\nFROM semantic.network_capabilities\nWHERE\n     $__timeFilter(timestamp_ts)\n     AND\n     timestamp_ts < now() - INTERVAL 5 minute  -- last minutes data is missing pipeline_* data\n     AND\n     orch_uri NOT LIKE '%lvpr.io%'\n     AND\n     _time > '2025-09-17' -- we don't want to expose old models\nGROUP by _time, model_id\nORDER BY _time, ` ` DESC"
    }
   ]
  },
  {
   "title": "GPUs per URL/model",
   "type": "timeseries",
   "description": "Showing max 1 month of data",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "targets": [
    {
     "rawSql": "SELECT\n     toStartOfHour(`semantic`.`network_capabilities`.timestamp_ts) as `_time`,\n     (extract(`semantic`.`network_capabilities`.`orch_uri`, 'https://(.*)') || ' (' || model_id || ')') as orchestrator_short_uri,\n     count(distinct gpu_id) as ` `\nFROM semantic.network_capabilities\nWHERE\n     `_time` >= now() - INTERVAL 31 DAY\n     AND\n     timestamp_ts < now() - INTERVAL 5 minute  -- last minutes data is missing pipeline_* data\n     AND\n     orch_uri NOT LIKE '%lvpr.io%' AND  $__timeFilter(timestamp_ts)\nGROUP by _time, orchestrator_short_uri\nORDER BY _time, ` ` DESC"
    }
   ]
  },
  {
   "title": "GPU idle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "max by(orchestrator_uri, model_name) (livepeer_ai_container_idle{livepeer_live_app=~\".*-livepeer-ai-gateway\", orchestrator_uri!~\".*lvpr.io.*\"})",
     "legendFormat": "{{orchestrator_uri}} ({{model_name}})"
    }
   ]
  },
  {
   "title": "Logs per node",
   "type": "timeseries",
   "description": "node_name may differ from the serviceURL",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(node_name) (count_over_time({node_name=~\".+\"} [$__auto]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Slow Orchestrators",
   "type": "timeseries",
   "description": "SlowOrchestrator is a strong indicator of network connectivity issues between G/O and these tend to persist for a few hours until the tubes clear up or someone kicks something.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(host) (count_over_time({container=\"ai-gateway\"} |= `Orchestrator is slow` !~ `.+lvpr.io.+` | regexp `url=https?://(?P<host>[^/]+)` [1h]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Slow Orchestrators By Region",
   "type": "timeseries",
   "description": "SlowOrchestrator is a strong indicator of network connectivity issues between G/O and these tend to persist for a few hours until the tubes clear up or someone kicks something.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(region) (count_over_time({container=\"ai-gateway\"} |= `Orchestrator is slow` !~ `.+lvpr.io.+` | regexp `url=https?://(?P<host>[^/]+)` [1h]))",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "First segment delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (orchestrator_uri) (\n  (\n    increase(livepeer_ai_first_segment_delay_ms_sum{orchestrator_uri!~\".*lvpr.io.*\"}[1m])\n    /\n    increase(livepeer_ai_first_segment_delay_ms_count{orchestrator_uri!~\".*lvpr.io.*\"}[1m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum by(orchestrator_uri) (increase(livepeer_ai_request_errors{livepeer_live_app=~\".*-livepeer-ai-gateway\", orchestrator_uri!~\".*lvpr.io.*\", orchestrator_uri!=\"\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Earnings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Expected Value ETH: All time",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "rawSql": "SELECT\n  extract(`semantic`.`network_payments`.`orchestrator`, 'https://(.*)') as orchestrator_short_uri,\n  SUM(`semantic`.`network_payments`.`expected_value_eth`) AS `expected_value_eth_sum`\nFROM\n  `semantic`.`network_payments`\nWHERE\n  `semantic`.`network_payments`.`orchestrator` NOT LIKE '%lvpr.io%' \nGROUP BY\n  orchestrator_short_uri\nORDER BY\n  `expected_value_eth_sum` DESC,\n  orchestrator_short_uri ASC\n"
    }
   ]
  },
  {
   "title": "Expected Value ETH: Hourly",
   "type": "timeseries",
   "description": "showing last 7 days data at max",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfHour(`semantic`.`network_payments`.timestamp_ts) as `time`,\n  extract(`semantic`.`network_payments`.`orchestrator`, 'https://(.*)') as orchestrator_short_uri,\n  SUM(`semantic`.`network_payments`.`expected_value_eth`) AS ` `\nFROM\n  `semantic`.`network_payments`\nWHERE\n  $__timeFilter(timestamp_ts)\n  AND\n  `semantic`.`network_payments`.`orchestrator` NOT LIKE '%lvpr.io%'\n  AND `time` >= now() - INTERVAL 7 DAY\nGROUP BY\n  orchestrator_short_uri, `time`\nORDER BY\n  `time` ASC,\n  ` ` DESC,\n  orchestrator_short_uri ASC\n\n\n"
    }
   ]
  },
  {
   "title": "Expected Value ETH: Daily",
   "type": "timeseries",
   "description": "showing last 31 days data at max",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfDay(`semantic`.`network_payments`.timestamp_ts) as `time`,\n  extract(`semantic`.`network_payments`.`orchestrator`, 'https://(.*)') as orchestrator_short_uri,\n  SUM(`semantic`.`network_payments`.`expected_value_eth`) AS ` `\nFROM\n  `semantic`.`network_payments`\nWHERE\n  $__timeFilter(timestamp_ts)\n  AND\n  `semantic`.`network_payments`.`orchestrator` NOT LIKE '%lvpr.io%'\n  AND `time` >= now() - INTERVAL 31 DAY\nGROUP BY\n  orchestrator_short_uri, `time`\nORDER BY\n  `time` ASC,\n  ` ` DESC,\n  orchestrator_short_uri ASC\n\n\n"
    }
   ]
  },
  {
   "title": "Expected Value ETH: Current time span ($__from - $__to)",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "rawSql": "SELECT\n  extract(`semantic`.`network_payments`.`orchestrator`, 'https://(.*)') as orchestrator_short_uri,\n  SUM(`semantic`.`network_payments`.`expected_value_eth`) AS `expected_value_eth_sum`\nFROM\n  `semantic`.`network_payments`\nWHERE\n  $__timeFilter(timestamp_ts)\n  AND\n  `semantic`.`network_payments`.`orchestrator` NOT LIKE '%lvpr.io%' \nGROUP BY\n  orchestrator_short_uri\nORDER BY\n  `expected_value_eth_sum` DESC,\n  orchestrator_short_uri ASC\n"
    }
   ]
  },
  { "title": "Livepeer's AI Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Livepeer's AI Gateway: Total Streams",
   "type": "timeseries",
   "description": "Measured in Gateways",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum by(pipeline) (max by(node_id, pipeline, region) (livepeer_ai_current_live_pipelines{livepeer_node_type=~\".*-livepeer-ai-gateway.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Livepeer's AI Gateway: Missing Capacity Errors in $__interval (no orchestrators available)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "sum by(model_name) (increase(livepeer_ai_request_errors{error_code=~\"no orchestrators available.*\", pipeline=~\"live-.*\", model_name!~\"streamdiffusion|streamdiffusion-sd15\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orchestrator selection latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "last_over_time({container=\"ai-gateway\"} |= `, latency=` != `lvpr.io` | logfmt | unwrap duration(latency) [$__auto]) by (uri, region)",
     "legendFormat": "{{uri}} {{region}} "
    }
   ]
  }
 ]
}