name: Backup dashboards from grafana

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 17 * * *'

# example query
# curl -H "Authorization: Bearer eyJrIjoidWUzaDNYQ01NVGxzcUNNOWYwaTE1YVZxcGxHbFduQUIiLCJuIjoiZGFzaGJvYXJkc19iYWNrdXAiLCJpZCI6MX0=" https://eu-metrics-monitoring.livepeer.live/grafana/api/dashboards/home

jobs:
  backup:
    name: Run backup script
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: update dashboards
        env:
          API_KEY: ${{ secrets.GRAFANA_READ_API_KEY }}
        run: |
          ./export.sh https://eu-metrics-monitoring.livepeer.live/grafana

      - name: Create a PR with the new dashboards
        uses: peter-evans/create-pull-request@v4
        if: ${{ success() }}
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: "[AUTO] Dashboard backup"
          labels: "grafana"
          commit-message: "This is an automated PR for backing up the Grafana dashboards in eu-metrics"
          branch: backup/grafana
          base: master
          delete-branch: true
          body: "This PR updates the values for the Grafana dashboards in eu-metrics"
