name: Backup dashboards from grafana

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3/6 * * *'

# example query
# curl -H "Authorization: Bearer eyJrIjoidWUzaDNYQ01NVGxzcUNNOWYwaTE1YVZxcGxHbFduQUIiLCJuIjoiZGFzaGJvYXJkc19iYWNrdXAiLCJpZCI6MX0=" https://eu-metrics-monitoring.livepeer.live/grafana/api/dashboards/home

jobs:
  backup:
    name: Run backup script
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Run script to update dashboards
        env:
          API_KEY: ${{ secrets.GRAFANA_READ_API_KEY }}
        run: |
          ./export.sh https://eu-metrics-monitoring.livepeer.live/grafana

      - name: Commit and push changes
        id: branch-commit
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          target_branch: backup/grafana
          commit_prefix: "[AUTO-COMMIT] "
          commit_message: 'Backup grafana dashboards'
          force: true

      - name: Create pull request with new dashboards
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          source_branch: ${{ steps.branch-commit.outputs.branch_name }}
          target_branch: master
          title: '[AUTO] Dashboards backup'
          label: grafana
          get_diff: true
          allow_no_diff: false
