name: Publish images to dockerhub

on:
  pull_request:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    name: Build and publish ${{ matrix.build.arg }} docker images
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - arg: prod
            suffix: ""
          - arg: staging
            suffix: "-staging"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            suffix=${{ matrix.build.suffix }},onlatest=true
          images: |
            livepeer/monitoring
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            type=sha,format=long
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            GRAFANA_ENV=${{ matrix.build.arg }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: notify successful build
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
